### ISSUE TITLE
apply styles inline break app

### ISSUE THREAD

**Issue by vallemar** [nativescript-vue/nativescript-vue#1011]
When I set the styles on Label for example my app break, example ` style="background-color: red"`: 

```html
       <Label text="Test text" class="text-2xl m-6" style="background-color: red"></Label>
```

Error: `View.style property is read-only`

I have noticed that this happens when hmr is enabled and makes a change with the styles. When the app is started for the first time, the exception does not appear, but the text does not appear in the app either.

Note: I am on Android

**Comment by rigor789** [comment]
> I have also noticed that the exception does not appear in the console or cli, I only see the error screen on mobile. I understand that this should appear in the console too

I've been seeing correct error logs in console, if you are still seeing that, open a new issue please with a sample I could investigate!
