### ISSUE TITLE
Don't work v-model

### ISSUE THREAD

**Issue by Ma1kaveli** [nativescript-vue/nativescript-vue#1023]
_I try this:_
`<TextField @textChange="onChangeValue" :text="modelValue" />`
_And this:_
`<TextField v-model="modelValue" />`

`modelValue` - it is ref

**This is my dependencies:**

"dependencies": {
     "@nativescript/core": "~8.4.0",
     "nativescript-vue": "3.0.0-beta.2",
     "vuex": "^4.1.0"
  },
  "devDependencies": {
     "@nativescript/android": "8.4.0",
     "@nativescript/types": "~8.4.0",
     "@nativescript/webpack": "~5.0.0",
     "@types/node": "~17.0.21",
     "sass": "^1.56.1",
     "typescript": "~4.8.4",
     "vue": "^3.2.45"
  }

How can I use TextField?

**Comment by rigor789** [comment]
```vue
<TextField
  :text="test"
  @textChange="test = $event.object.text"
/>
```

Should work (on latest beta.5) - need to check what's up with `v-model` though 🤔

**Comment by Ma1kaveli** [comment]
Empty. I've tried this...
I even tried using `v-model` right after installing the project, but nothing worked

**Comment by Ma1kaveli** [comment]
Now update to beta.5 this work:
`<TextField
  :text="test"
  @textChange="test = $event.object.text"
/>`
But the `v-model` still doesn't work
