### ISSUE TITLE
Axios not supported in Nativescript-Vue apps anymore

### ISSUE THREAD

**Issue by devnickramage** [nativescript-vue/nativescript-vue#1053]
I was reading somewhere that axios isnt supported for nativescript-vue apps anymore? just wondering if anyone can confirm this?

**Comment by vallemar** [comment]
You can use XX version, It looks very old but it is not.
https://discord.com/channels/603595811204366337/606457523574407178/1113557361420931133

Also, you can use redaxios

**Comment by devnickramage** [comment]
Awesome thanks for that
