### ISSUE TITLE
Vue DevTools on v3

### ISSUE THREAD

**Issue by vpiskunov** [nativescript-vue/nativescript-vue#1059]
Just reached for DevTools yet another time, and realising there's no implementation for V3 (AFAIK) - wondered if there is any plans of anyone or yourself @rigor789 or @vallemar to try giving this a go? 

Alternatively, I could try and see if I find some time to dig in myself - but in such case can I please ask for some pointers / intro / info on any previous attempts or just general hints on the differences between v2 & v3 in terms of devtools related aspects?

P.S. I know this probably belongs to nativescript-vue-devtools, but believe this repo is much more lively and kind of relates to the beta version of this repo, so let's discuss here (at least for now)?

**Comment by rigor789** [comment]
I haven't had the chance to look into it for v3 yet, but I presume it would be very similar to how it's handled in v2:
- establish a socket connection with the standalone devtools
- load the devtools library, and pass it this websocket connection

That's a rough overview. I believe someone from the community has started looking into it, I think it was mentioned on Discord - will have to search for it, as I'm not sure what the state of that attempt is.

As for the repo/location, I think it would make sense to implement it in this repo inside `packages/` so it's co-located with the rest of v3...

**Comment by vpiskunov** [comment]
This is great stuff! Thanks @rigor789 @vallemar.

Very excited to see the code from @heywhy - looks very promising in that discord thread!

Otherwise, @vallemar let me know if you think there's anything detached I could potentially work on, to help with some part of this, or maybe a theory/concept-based challenge you have from your previous discussion on Discord?

**Comment by rigor789** [comment]
Just released initial support from @heywhy in beta.9! Added a note in the readme. Give it a try, and let me know if you run into issues - I'll be trying it out on some apps too.
