### ISSUE TITLE
How do you programmatically trigger a tap event on a button ?

### ISSUE THREAD

**Issue by pb321** [nativescript-vue/nativescript-vue#1062]
Ive tried all sorts but cant seem to get it work and there seems to be very little on the subject..

i currently have this
<Button text="Retrieve" @tap="handleRetrieve" ref="btnRetrieve" class="my-button"  row="1" col="0" />

and in a textchange function event, i have this bit of code.  its my attempt to trigger the tap event on the above button, but it doesnt work..

this.$refs.btnRetrieve.$emit('tap')

i get the message "$emit is not a function".  Is there anything else i should try ?

**Comment by vallemar** [comment]
you can directly call handleRetrieve
```js
this.$refs.btnRetrieve.$emit('toque')

to

handleRetrieve()
```

**Comment by pb321** [comment]
> you can directly call handleRetrieve
> 
> ```js
> this.$refs.btnRetrieve.$emit('toque')
> 
> to
> 
> handleRetrieve()
> ```

Hi vallemar
Thanks for your prompt reply.  Im afraid i get the message : his.$refs.btnRetrieve.$emit is not a function

**Comment by vallemar** [comment]
hello! I think I expressed myself wrong. I meant that you don't need to call tap, you can directly call the function you want to execute with tap. I mean change this `this.$refs.btnRetrieve.$emit('tap')` to this `handleRetrieve()`

**Comment by pb321** [comment]
Why didnt i think of that !!  Yes, of course, its obvious now !  Sorry to have wasted your time on this, but thank you !
