### ISSUE TITLE
TabView on Vue3

### ISSUE THREAD

**Issue by aalonzi** [nativescript-vue/nativescript-vue#1063]
Hi to all, 
I try to use TabView on Vue3, but I have these error message:
`TypeError: Class constructor TabView cannot be invoked without 'new'`

I use html code from https://v8.docs.nativescript.org/ui-and-styling.html#tabview and vue3 template from @nativescript-vue/template-blank@beta

Can you help me?

**Comment by vallemar** [comment]
@aalonzi try removing the import of your component

```ts
import { TabView, TabViewItem } from "@nativescript/core"; // <----- Remove this
```

**Comment by aalonzi** [comment]
> @aalonzi try removing the import of your component
> 
> ```ts
> import { TabView, TabViewItem } from "@nativescript/core"; // <----- Remove this line 
> ```

I try also it, but I have these error:
`[Vue warn]: Failed to resolve component: TabViewItem
  If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
  at <Tabs>`

Thank you
