### ISSUE TITLE
docs: A re-write of the NativeScript-Vue documentation site.

### ISSUE THREAD

**Issue by selemondev** [nativescript-vue/nativescript-vue#1066]
As a developer using NativeScript-Vue, I strongly believe that a re-write of the documentation site (https://nativescript-vue.org) is crucial for several reasons:

1.  **Clarity and Organization:** The current documentation can be challenging to navigate, especially for newcomers. A well-structured and organized documentation site can make it significantly easier for developers to find the information they need, reducing frustration and saving them valuable time.

2. **Richer Content:** I believe that the re-write can include more comprehensive and up-to-date content. It can cover advanced use cases, best practices, and real-world examples, helping developers fully leverage NativeScript-Vue's capabilities.

3. **Interactive Elements:** Implementing interactive elements, such as live code samples and inline demos, can help developers better understand how to use NativeScript-Vue features in practice, leading to quicker learning and more effective development.

4. **Community Engagement:** A revamped documentation site can facilitate community contributions, allowing external developers like me to add examples, tutorials, and documentation improvements. This will benefit the entire developer community and foster a sense of collaboration and shared ownership.

If accepted, I would be happy to take on this task 😄

**Comment by PixsaOJ** [comment]
![image](https://github.com/nativescript-vue/nativescript-vue/assets/12684017/f253e557-1ef8-4dc4-8b75-9e3d9730c1c8)

This is in Nativescript Discord in vue channel

**Comment by selemondev** [comment]
Thanks @PixsaOJ 😁.
