### ISSUE TITLE
navigation in Vue beta 9 or 10 is broken in production mode

### ISSUE THREAD

**Issue by vallemar** [nativescript-vue/nativescript-vue#1067]
When you generate the apk or I also think that when you run the application in production mode the navigation does not work.

I think the change that could have caused this happened in this PR (it's just a hunch, I haven't checked it): https://github.com/nativescript-vue/nativescript-vue/pull/1060

**Comment by MrSnoozles** [comment]
Here are all the changes from Beta 8, when navigation was working, to the current main:
[https://github.com/nativescript-vue/nativescript-vue/compare/3.0.0-beta.8...main](https://github.com/nativescript-vue/nativescript-vue/compare/3.0.0-beta.8...main)

**Comment by vallemar** [comment]
@heywhy Do you know if this could have broken production mode?

**Comment by heywhy** [comment]
Hey @vallemar. I'm curious to know what the problem is in the production build.

1. Does your app not navigate to a new screen?
2. Do you have logs? Crashlytics or something similar to aid debugging?

**Comment by vallemar** [comment]
@heywhy The main page loads, but when we try to navigate it gets stuck and does nothing. More people have noticed it (spoken on discord). I couldn't see any log, @MrSnoozles , did you have any log of this?
