### ISSUE TITLE
Vue 3 errors only shown when debugging with Vue Devtools

### ISSUE THREAD

**Issue by dangrima90** [nativescript-vue/nativescript-vue#1087]
I'm having an issue related to error logs. I've noticed that whenever errors happen I'm only able to see them logged when switching on Vue Devtools.

Example:

In App.vue I'm throwing an error to showcase the behaviour:

```js
created() {
  throw new Error('TEST ERROR!');
}
```

Without running Vue Devtools in the browser console I don't see the error or even warning. In the terminal I see the following:

```bash
[Vue warn]: Unhandled error during execution of created hook
  at <App key=0 >
  at <Root>
```

The above makes sense, however the error is still not shown. Once I switch on Vue Devtools by using `--env.vueDevtools` I then see the error in the terminal:

```bash
[Vue warn]: Unhandled error during execution of created hook
  at <App key=0 >
  at <Root>
Unhandled promise rejection Error: TEST ERRROR!
```

And in the browser I also see the error plus the stacktrace as expected:

![image](https://github.com/user-attachments/assets/7355ee17-7129-49b2-aed4-ccdae37c50f8)

**Comment by MrSnoozles** [comment]
Hi @dangrima90 ,

can you check if this PR improves error messages for you? https://github.com/nativescript-vue/nativescript-vue/pull/1089

Just configure this error handler for your app instance.

**Comment by dangrima90** [comment]
@MrSnoozles that does indeed fix the issue 🙌
