### ISSUE TITLE
update on single file components and alternate templates...

### ISSUE THREAD

**Issue by aaronksaunders** [nativescript-vue/nativescript-vue#113]
in the past there was work going on with a webpack and rollup templates, it looks like there hasn't been much progress there since the effort was on getting the release out, congrats!!.. but i am still looking to see how if it is feasible to build a complex  app without single file component support.

the doc still says use rollup... rollup says it is being depricated, and the link it sends you to is difference from this one.

https://github.com/nativescript-vue/nativescript-vue-webpack-template

if i am missing something in the documentation, my apologies and please point me in the right direction

**Comment by rigor789** [comment]
The templates documentation is in need of updating, the webpack template you linked (in the nativescript-vue org) is a WIP template that will include code-sharing and sfc support, it is mostly working as is, except the style tags are not being processed correctly. This is a configuration issue, but I didn't have time to look into it further and fix it.

Rollup will be deprecated soon just because we don't have the resources to maintain two templates that accomplish the same.

Right now your best bet is to use the webpack template by @tralves https://github.com/tralves/nativescript-vue-webpack-template/

**Comment by tralves** [comment]
I understand your frustration,@aaronksaunders. I had to stop working on those templates for work and personal reasons, but that situation is changing. Like @rigor789 said, there is a new template WIP that will be much easier to work with and deliver code sharing capabilities, etc.

**Comment by aaronksaunders** [comment]
Thank you both for responding.
so which of the two webpack templates would you suggest I use? Also in the past,
the symlinks were not working properly so the webpack template wasnt really
viable for a real project with multiple developers.  





On Tue, Feb 13, 2018 1:52 PM, Tiago Alves notifications@github.com  wrote:
I understand your frustration,@aaronksaunders. I had to stop working on those
templates for work and personal reasons, but that situation is changing. Like 
@rigor789  said, there is a new template WIP that will be much easier to work
with and deliver code sharing capabilities, etc.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.




--

Aaron K. SaundersCEO Clearly Innovative Inc - Luma Lab - In3
aaron@clearlyinnovative.com
www.clearlyinnovative.comwww.In3DC.com



This email message and any attachment(s) are for the sole use of the intended
recipient(s) and may contain proprietary and/or confidential information which
may be privileged or otherwise protected from disclosure. Any unauthorized
review, use, disclosure or distribution is prohibited. If you are not the
intended recipient(s), please contact the sender by reply email and destroy the
original message and any copies of the message as well as any attachment(s) to
the original message.

**Comment by qLutCh55** [comment]
@rigor789 @tralves Is there any update to this? As it seems that https://github.com/nativescript-vue/nativescript-vue-webpack-template no longer works out of the box. Getting error on error with regards to webpack. 

P.S Keep up the good work, looking good :)

Thanks

**Comment by rigor789** [comment]
We have updated the docs with the currently supported templates, https://nativescript-vue.org/en/docs/getting-started/templates/

I'm closing this issue, but if you have any further questions let us know!
