### ISSUE TITLE
seeing different behavior between playgrounds and building app on ios & android devices

### ISSUE THREAD

**Issue by aaronksaunders** [nativescript-vue/nativescript-vue#114]
**In the Emulator...**
<img width="1003" alt="screen shot 2018-02-16 at 6 02 22 pm" src="https://user-images.githubusercontent.com/524953/36333349-4a66801a-1344-11e8-9e2f-053027fdf159.png">

**Running Using Playgrounds**
![image-1](https://user-images.githubusercontent.com/524953/36333415-cf25748c-1344-11e8-9684-aa22c7b800c3.jpg)

when i run the code from the [router example](https://github.com/nativescript-vue/nativescript-vue-template/blob/master/app-with-router.js) it seems to work fine in the playground but when running the code on device it does not... it does not render the buttons on the router path.

**Comment by nusendra** [comment]
modify nativescript-vue in dependencies section in package.json. change to 1.0
then npm update, or u can delete node_modules then npm install

correct me if im wrong

**Comment by aaronksaunders** [comment]
@nusendra thanks!!
