### ISSUE TITLE
Is it possibly to gradually add nativescript-vue to a native application ?

### ISSUE THREAD

**Issue by asafyish** [nativescript-vue/nativescript-vue#116]
Hi,

Is it possibly to gradually add nativescript-vue to a native application ? or does it requires a fresh project ?

If it is possible, can you point to related documentation ?

**Comment by rigor789** [comment]
Hi, unfortunately I don't see it being possible with nativescript in general. Although I may be wrong here, if it's possible with nativescript, then it should be very similar for nativescript-vue.

**Comment by triniwiz** [comment]
This might be useful https://www.nativescript.org/blog/using-nativescript-in-an-existing-native-ios-android-applications
