### ISSUE TITLE
how to make right to left support

### ISSUE THREAD

**Issue by Haizone** [nativescript-vue/nativescript-vue#118]
hi 
i whant to make an app but i need to know how to make rtl support
have a tutorial or somthing?

**Comment by rigor789** [comment]
I've not created a RTL application in the past, but I think I've seen it done with NativeScript. 

https://github.com/NativeScript/NativeScript/issues/42#issuecomment-367308621

I'm closing this issue because it's not specific to NativeScript-Vue itself.
