### ISSUE TITLE
android.foregroundActivity and android.startActivity is undefined

### ISSUE THREAD

**Issue by iabai** [nativescript-vue/nativescript-vue#121]
Hi! I try to get current android activity but it's undefined.
My code:
```javascript
const Vue = require('nativescript-vue/dist/index')
require("application");

new Vue({
  template: `
    <page ref="page">
      <stack-layout></stack-layout>
    </page>
  `,
  mounted() {
    console.log(android.foregroundActivity);
    console.log(android.startActivity);
    console.log(android.context)
  }
}).$start()
```

What i do wrong?

**Comment by rigor789** [comment]
You are `require`ing the application module but never assigning it to a variable.

I believe what you are looking for is 

```js
const Vue = require('nativescript-vue')
const { android } = require('tns-core-modules/application')

new Vue({
  template: `...`,
  mounted() {
    console.log(android.foregroundActivity)
    console.log(android.startActivity)
    console.log(android.context)
  }
}).$start()
```

Let me know if that works!

**Comment by iabai** [comment]
Yes it's work.
Thanks for your the help!

**Comment by rigor789** [comment]
You are welcome! We also have a slack channel where you can get help a lot faster. It's on the NativeScript Community slack in the #vue channel. https://developer.telerik.com/wp-login.php?action=slack-invitation
