### ISSUE TITLE
how to get context data in the modal component?

### ISSUE THREAD

**Issue by academici** [nativescript-vue/nativescript-vue#123]
how to get context data in the modal component?
`this.$showModal(testModal, {
        fullscreen: true,
        context: {
          test: 1
        },
      })`
`<Page class="vendor-reply-modal" @showingModally="load" >`
`load(args) {
      console.log(args.context)
    },`

args.context is null

**Comment by rigor789** [comment]
The context you pass will be passed to the Vue constructor 
```js
const Constructor = Vue.extend(Component)
const vm = new Constructor(context)
```
(https://vuejs.org/v2/guide/unit-testing.html#Writing-Testable-Components)

You can pass `propsData` for example, and then accept props in your modal component.

Another way to go about it (in simple cases) is to generate the markup for the modal page using javascript, something like 
```js
const test = 1;
this.$showModal({
  template: `
    <Page>
      <StackLayout>
        <Label text="${test}" />
      </StackLayout>
    </Page>
  `
})
```
