### ISSUE TITLE
SegmentedBar using Vue.js not working

### ISSUE THREAD

**Issue by vtvhunter** [nativescript-vue/nativescript-vue#125]
Hi, I am testing the development of an app using Vue.js through Nativescript and have encountered a problem when using SegmentedBar ui component (using [this](https://nativescript-vue.org/en/docs/elements/components/segmented-bar/) as a guide: ) :

**template**

`<SegmentedBar :items="listOfItems" v-model="selectedItem" />`

**object**

`data: {
    	listOfItems: [
			{title: 'Cool'},
			{title: 'Warm'}
    	]`

**error**
```
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:456:27: JS ERROR TypeError: child._setupUI is not a function. (In 'child._setupUI(context)', 'child._setupUI' is undefined)
```
I have also tried using [items]="arrayName" and that prevents the error but the component renders blank. The only way I can make it work is if I use static data with `SegmentedBarItem` component.

Thanks

**Comment by rigor789** [comment]
Hi I don't think the `<SegmentedBar :items="listOfItems" v-model="selectedItem" />` syntax is currenlty supported, and the docs are wrong! 

What you could do right now is use the `SegmentedBarItem` and if you need these to be dynamic, I think a `v-for` should work just fine.

```html
<SegmentedBar/>
  <SegmentedBarItem v-for="item in listOfItems" :title="item.title" />
</SegmentedBar>

**Comment by vtvhunter** [comment]
Hi, 

Thanks for your response! Yeah, that's what I figured, was not too sure if the docs were stating the correct info. Do you need help with the docs?

**Comment by rigor789** [comment]
If you don't mind updating the docs, then sure!
