### ISSUE TITLE
Button isEnabled data bind not working

### ISSUE THREAD

**Issue by vtvhunter** [nativescript-vue/nativescript-vue#126]
Hi I am testing vue.js with nativescript and I am trying to bind a computed to the isEnabled attribute for the `<Button>` element, so i can toggle its enabled/disabled state:

`<Button class="primary" isEnabled="{{isComplete}}" text="Calculate" @tap="calculateRuntime"/>`

js inside computed property: 

`isComplete: function(){
			return this.hour > 0; 
		}`
For some reason I am not able to set either true/false value to it based on an object property value. Nevertheless, it works fine if I put `false` directly: 
`<Button class="primary" isEnabled="false" text="Calculate" @tap="calculateRuntime"/>`

I wanted to dynamically change the value but I don't know if this is a bug or not.

Thanks

**Comment by rigor789** [comment]
Hi, the proper binding syntax is 
```
<Button class="primary" :isEnabled="isComplete" text="Calculate" @tap="calculateRuntime"/>
```
Can you give that a try, and let me now it that solves it?

**Comment by vtvhunter** [comment]
Working! Thanks, should I/we update the documentation? :)

**Comment by vtvhunter** [comment]
It was a little bit difficult to see the proper syntax based on the vue.js/nativescript [docs](https://nativescript-vue.org/en/docs/elements/components/button/) as it didn't show the complete set of attributes inside the **props** section

**Comment by rigor789** [comment]
Well, the binding part doesn't need to go into the button docs itself, because any property can be bound using the `v-bind` or the `:` shorthand method. I'm not sure if we should add this to the docs ourselves, since it's the exact same syntax used in vue (https://vuejs.org/v2/guide/). We could probably refer to the official vue docs though

**Comment by vtvhunter** [comment]
I see, thanks
