### ISSUE TITLE
How to use Applications Settings

### ISSUE THREAD

**Issue by nusendra** [nativescript-vue/nativescript-vue#128]
after i added this into my main.js
```import applicationSettings from 'tns-core-modules/application-settings'```

then how to use it in the component? Im new with this. thanks
I hope sir @rigor789 can help me out

**Comment by rigor789** [comment]
Depends what you want to do, but you can call `applicationSettings.setString(key, value)` to save a string to disk, and then `application.getString(key)` to retrieve it.

**Comment by nusendra** [comment]
I'm import appsetting to my main.js
```import applicationSettings from 'tns-core-modules/application-settings'```

then in my component
```
mounted () {
        applicationSettings.setString(key, 'testing')
    },
    data () {
        return {
            test: 'null'
        }
    },
    methods: {
        tapped () {
           this.test = applicationSettings.getString(key)
        }
    }
```

System.err: ReferenceError: applicationSettings is not defined
----------------
How to solve this? Thanks

**Comment by rigor789** [comment]
Are you importing it in the file where you are trying to access it?

**Comment by nusendra** [comment]
ah so i have to import it locally? How to make it globally?

-------------------
This works  perfect (locally / in my component)
```
import {getString, setString} from 'tns-core-modules/application-settings'
export default {
    mounted () {
        setString("username", "Wolfgang")
    },
    data () {
        return {
            tes: 'null'
        }
    },
    methods: {
        tapped () {
            this.tes = getString("username")
        }
    }
}
```

Thanks sir @rigor789 much appreciated
