### ISSUE TITLE
Installing plugin does not work

### ISSUE THREAD

**Issue by KErez** [nativescript-vue/nativescript-vue#130]
I followed the instructions on the [nativescript-vue website](https://nativescript-vue.org/en/docs/getting-started/quick-start/#next-steps) on how to install nativescript-vue and the app is working however when trying to install plugin as instructed in ["Using NativeScript Plugins"](https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/) I get the following message:

``` 
No project found at or above '/Users/kfir/workspaces/myapp' and neither was a --path specified. 
```
When I run ```tns plugin add nativescript-gradient --path dist``` the plugin is installed successfully under dist (which feel like bad workaround because it does not exist under my codebase but rather on the compiled code which does not suppose to get to the repo) 
When running ```npm run wathc:ios``` I still get this error message (since the gradient module is under dist):
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'nativescript-gradient' in '/Users/kfir/workspaces/myapp/src'
 @ ./src/main.js 7:28-60
```
But the compilation continues.
However the application fails to execute with this stack trace:
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x107551724 -[TNSRuntime executeModule:referredBy:]
2   0x107014681 main
3   0x10d6dfd81 start
4   0x1
JavaScript stack trace:
1   @file:///app/app.js:1:147690
2   @file:///app/app.js:1:147691
3   e@file:///app/app.js:1:175
4   @file:///app/app.js:1:522
5   anonymous@file:///app/app.js:1:531
6   evaluate@[native code]
7   moduleEvaluation@[native code]
8   @[native code]
9   promiseReactionJob@[native code]
JavaScript error:
file:///app/app.js:1:147690: JS ERROR Error: Cannot find module "nativescript-gradient"
```
So in general I cannot add plugins (happened with other plugins as well)

**Comment by asafyish** [comment]
Having the same issue.

**Comment by rigor789** [comment]
If you are using the vue-cli template the you have to use `npm install nativescript-gradient` instead. We should probably change the docs because the `tns add` command only works with a pure nativescript setup (not using the template)

**Comment by asafyish** [comment]
Should it be done in the root level ?

**Comment by rigor789** [comment]
In the vue-cli template yes, and you should also save it, so in the root run `npm install --save nativescript-gradient` and then it should work. If it gives you errors, try running `npm run clean` and then `npm run watch:android` or `npm run watch:ios`.

**Comment by KErez** [comment]
I tried that before and I got the same error. I even tried to install with npm on root and install with tns under dist and I still get the same error

**Comment by rigor789** [comment]
Can you post your package.json file (from the root of the project)?

**Comment by KErez** [comment]
Note that commenting out the ```import Gradient from 'nativescript-gradient';``` works (obviously I cannot use the plugin)

**Comment by rigor789** [comment]
Have you tried using `require`? Like in the docs: 

```js
Vue.registerElement('Gradient', () => require('nativescript-gradient').Gradient)
```

The whole process for adding the plugin to the cli template:

```shell
$ cd project/
$ npm install --save nativescript-gradient
$ npm run clean
```
in you `main.js` file add

```js
Vue.registerElement('Gradient', () => require('nativescript-gradient').Gradient)
```

In your template:

```html
<Gradient direction="to right" colors="#FF0077, red, #FF00FF">
  <Label text="Best gradient." horizontalAlignment="center"
         style="color: white; padding: 20" />
</Gradient>
```

and finally in the terminal

```shell
$ npm run watch:android
$ # or
$ npm run watch:ios
```

**Comment by KErez** [comment]
It is working!
The change to use require instead of import worked for me, thanks!
