### ISSUE TITLE
Icon font in TabView doesn't work (iOS)

### ISSUE THREAD

**Issue by Realistst** [nativescript-vue/nativescript-vue#136]
Is there a way to set icons for tabs (iOS)? FontAwesome doesn't seems to work.

Demo:
https://play.nativescript.org/?template=play-vue&id=qDbPGS&v=6

**Comment by rigor789** [comment]
Try it using a binding like this
https://play.nativescript.org/?template=play-vue&id=qDbPGS&v=9

Char codes are not looked up when not in a binding

**Comment by Realistst** [comment]
It did not help :(

![imageee-1](https://user-images.githubusercontent.com/7064723/37302757-802b7ff0-263d-11e8-8009-e9d7ab2b6e38.jpg)

However it is working properly on Android.

**Comment by rigor789** [comment]
Interesting that If I add the `fa` class to the TabView then the icons work
https://play.nativescript.org/?template=play-vue&id=qDbPGS&v=16

**Comment by Realistst** [comment]
Hmm. That was unexpected! Thanks! I can use it as temporary workaround.

But now they are not vertically aligned. It seems it is related to this issue: https://github.com/NativeScript/NativeScript/issues/4831

**Comment by rigor789** [comment]
Yeah, you can create image assets instead of using an icon font (meh solution tbh). Or you could use a GridView to replicate the tab view, and then use a Pager (nativescript-pager) to display the tabs in

**Comment by Realistst** [comment]
OK. Thanks for the help! I'll try to come up with something.

**Comment by jlooper** [comment]
I believe we always have to use images in the tabs...scaled and everything, it's a hassle

**Comment by packytagliaferro** [comment]
Is there any docs or example on how to add an image for a tab icon? Its pretty common practice to have no text and just an Icon or text with an icon. Seems like this should be outlined somewhere on how to do it. Thanks.

**Comment by zzhoo8** [comment]
@rigor789  It works for me, thx

```
Try it using a binding like this
https://play.nativescript.org/?template=play-vue&id=qDbPGS&v=9

Char codes are not looked up when not in a binding
```
