### ISSUE TITLE
Using <list-view> with VueRouter and 'pageRouting' causes screen freeze

### ISSUE THREAD

**Issue by VladimirAmiorkov** [nativescript-vue/nativescript-vue#138]
Hi,

When I use the template [nativescript-vue-template](https://github.com/nativescript-vue/nativescript-vue-template) and simple add the `pageRouting: true` to the VueRouter the ListView is no longer scrollable or interactable, it aslo looks that the app crashes at some point (I suspect and stackoverflow error, while no such one is logged anywhere tho).

To reproduce this error:

- Change the router declaration to:
```
const router = new VueRouter({
    pageRouting: true,
    routes: [
        {path: '/foo', component: reddit},
        {
            path: '/bar', component: Bar,
            children: [
                {path: 'fizz', component: Fizz},
                {path: 'buzz', component: Buzz}
            ]
        },
        {path: '*', redirect: '/foo'}
    ]
})
```

- Update to the latest version of nativescript-vue:
`"nativescript-vue": "1.3.1"`
-Update the template tags to v-template:
```
<list-view :items="items" class="list-group" :templateSelector="templateSelector" @itemTap="onItemTap">
    <v-template scope="item">
        <stack-layout orientation="horizontal" class="list-group-item">
            <image :src="item.image" class="thumb"></image>
            <stack-layout>
                <label class="list-group-item-heading" :text="item.title"></label>
                <label class="list-group-item-text" text="The rest of the content" textWrap="true"></label>
            </stack-layout>
        </stack-layout>
    </v-template>
    <v-template name="active" scope="item">
        <stack-layout orientation="horizontal" class="list-group-item active">
            <image :src="item.image" class="thumb"></image>
            <stack-layout>
                <label class="list-group-item-heading" :text="item.title"></label>
                <label class="list-group-item-text" text="The rest of the content" textWrap="true"></label>
            </stack-layout>
        </stack-layout>
    </v-template>
</list-view>
```

Attached a sample project that shows the error behavior
[demo-vuep.zip](https://github.com/nativescript-vue/nativescript-vue/files/1805914/demo-vuep.zip)

**Comment by triniwiz** [comment]
Getting the same problem

**Comment by rigor789** [comment]
As commented by @t3hmrman we are currently not supporting VueRouter as it was very difficult to hack it to work in ns, and the Vue team is not currently interested in supporting NS, as it would require a major rewrite of the router. We will likely re-visit the router in the future.
