### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by felipefreitasffs** [nativescript-vue/nativescript-vue#145]
Is it possible use nativescript-sqlite plugin with nativescript-vue?

**Comment by rigor789** [comment]
Did you try it??

--- 
I haven't used it myself, but I'm 99.9% sure that you can use it. 
`npm install --save nativescript-sqlite`

and then 
```js
const Sqlite = require( "nativescript-sqlite" );
```

**Comment by felipefreitasffs** [comment]
Hi @rigor789 , yes I tried, but I receive the following error:

System.err: Error: com.tns.NativeScriptException: Failed to find module: "./application-common", relative to: app/

**Comment by rigor789** [comment]
I assume you are using the vue cli template. Have you read the docs about installing plugins? https://github.com/nativescript-vue/vue-cli-template#using-nativescript-plugins

And also, are you running the latest version of `nativescript-vue-externals` ? Should be `nativescript-vue-externals@0.1.2`
