### ISSUE TITLE
Tint Color for Action Bar items?

### ISSUE THREAD

**Issue by crrobinson14** [nativescript-vue/nativescript-vue#146]
I'm trying to adjust the tint color for the "Back" button in the Action Bar, the equivalent of setting this value in XCode:

![image](https://user-images.githubusercontent.com/1675563/37686904-072fd498-2c5f-11e8-9f5b-952d6460ecf9.png)

I found a vague reference in the main NativeScript project about setting this in code but can't seem to match it up to the Vue equivalent:
https://github.com/NativeScript/NativeScript/issues/4079

Is there a standard way of accessing native views from VueJS like this? I tried setting a `ref` on the ActionBar but if I then to try to access `this.$refs.actionbar.nativeView` that doesn't seem to be defined. I poked around and found ``this.$refs.actionbar.nativeView.$el.nativeView` WAS defined but didn't seem to provide access to what I was trying to get to.

**Comment by crrobinson14** [comment]
Note for other developers: I ended up just implementing a custom action bar of my own, which worked fine. But it would still be nice to know the "right way"!

**Comment by rigor789** [comment]
In NativeScript-Vue the `ActionBar` element is actually a Vue component, to access the underlying native view you have to use `this.$refs.actionBar.$el.nativeView`, and that will return the NativeScript view from `tns-core-modules`.
