### ISSUE TITLE
Cannot set minute 0 to TimePicker in Android

### ISSUE THREAD

**Issue by javiercbk** [nativescript-vue/nativescript-vue#148]
When trying to set a date with minute 0, the TimePicker will always choose the current minute. You can see how I'm using the TimePicker in this [file](https://github.com/javiercbk/timefiller-app/blob/nativescript/src/components/configuration/reminder-config.vue)

Also the `@timeChanged` event will not fire.

You can use my app to replicate this bug, in order to do so you must

1. Launch the app by executing `npm run debug:android`
2. Click the `Configuration` button
3. Click the `Reminder` button
4. Change the time picker to a time with a non zero minute
5. Go back
4. Click the `Reminder` button again
6. Assert that the time previously entered time is shown
7. Change the minute to zero
8. Go Back
9. Click the `Reminder` button again
10. Assert that the hour entered is correct but the minute is the current device minute

**Comment by rigor789** [comment]
Hey, I think this was an issue in nativescript-core and I believe it has been fixed. If you still experience the issue let me know and we can re-open it.
