### ISSUE TITLE
Android Tabview

### ISSUE THREAD

**Issue by chris-snader** [nativescript-vue/nativescript-vue#150]
I am starting to develop an app with nativescript with vue. So far very impressed, but I have come across an issue with the Tabview in Android. The attribute androidTabsPosition="bottom" doesn't seem to work as my Tab remains at the top of the page.

Here is my code:

```
const Vue = require("nativescript-vue");

Vue.component("Profile", require("./profile.js"));
Vue.component("Contact", require("./contact.js"));

module.exports = {
    data() {
        return {
            selectedIndex: 0,
            customer: {
                first_name: "First",
                last_name: "Name",
                customer: 1,
                other_id: "5783"
            },
            contact: {
                'phone': "+1 (555) 555-5555",
                'address': "address",
                'city': "city",
                'state': "AL",
                'zip': "55555"
            }
        }
    },
    methods: {

    },
    template: `
    <Page class="page">
      <ActionBar title="Welcome">
        <NavigationButton text="Logout" android.systemIcon="ic_menu_back" @tap="$router.back()" />
      </ActionBar>
      <TabView :selectedIndex="selectedIndex" androidTabsPosition="bottom">
        <TabViewItem title="Dashboard">
          <Label text="Content for Tab 1" />
        </TabViewItem>
        <TabViewItem title="Profile">
          <Profile :customer="customer" v-model="customer" />
        </TabViewItem>
        <TabViewItem title="Request">
          <Label text="Content for Tab 3" />
        </TabViewItem>
        <TabViewItem title="Contact">
          <Contact :contact="contact" v-model="contact" />
        </TabViewItem>
      </TabView>
    </Page>
  `,

};
```

**Comment by chris-snader** [comment]
I found it when I went to the link for the full Tabview documentation. I
said attribute, but it is actually labeled as a property. It is in the link
that you referenced as androidTabPosition. It says that it can be either
set to the string of top or bottom.

**Comment by bengallienne** [comment]
I'd also be interested in using this if possible too. Is this a thread that can be re-opened or do we need to create a new one?

**Comment by klever34** [comment]
@rigor789 androidTabsPosition="bottom"  does exist in the documentation.

**Comment by rigor789** [comment]
@klever34 indeed, that's why the issue has been re-opened. I did not see it at a glance when I checked the first time 👍

**Comment by elalienx** [comment]
Hi @chris-snader have you tried to update the tns-core-modules to the 4.1.0 version? That worked for me. More details on this thread: https://discourse.nativescript.org/t/how-to-permanently-put-the-tabview-at-the-bottom-in-android-and-style-the-tab-items-in-ns-vue/5643/8

**Comment by rigor789** [comment]
Alright, so I wasn't completely wrong - when I checked the ns docs I landed on the older version which did not have the property yet! This should be working with nativescript 4.x, check https://github.com/nativescript-vue/nativescript-vue/issues/239#issuecomment-394780299 for upgrade instructions.
