### ISSUE TITLE
Importing Modules problem

### ISSUE THREAD

**Issue by MisterBrownRSA** [nativescript-vue/nativescript-vue#151]
Hey,

I have come to a conclusion following the conversation we had on Slack.

Problem:
`TypeError: Could not load view for: radradialgauge. Error: com.tns.NativeScriptException: Failed to find module: "nativescript-ui-gauge\ui-gauge.common", relative to: app/tns_modules/`

I found that the `path.sep` gives "\\", which isn't working on Windows, but does work on iOS.

I tried overriding the path variable, but that doesn't seem to cut it.
So currently I need to update nativescript-vue-externals/index.js.

```
const path = require('path');

module.exports = (context, request, callback) => {

  if (context.indexOf('tns-core-modules') !== -1
    || context.indexOf('nativescript-') !== -1
    || /^(tns-core-modules)/i.test(request)
    || /^(ui|application)/i.test(request)) {

    // Support plugins requiring sibling files by rewriting './' into 'context/'
    if (request.indexOf('./') === 0) {
      request = path.join(path.basename(context), request.substring(2));
    }

    if (request.indexOf('nativescript-ui-sidedrawer') > -1) {
        request = "nativescript-ui-sidedrawer/ui-sidedrawer.common";
    }

    if (request.indexOf('nativescript-ui-gauge') > -1) {
        request = "nativescript-ui-gauge/ui-gauge.common";
    }

    return callback(null, 'commonjs ' + request);
  }

  callback();
};
```

I think the best would be to update the path separator for windows in the config somewhere, but I don't know where to look.

**Comment by rigor789** [comment]
This issue was moved to nativescript-vue/nativescript-vue-externals#1
