### ISSUE TITLE
TextView Multiline not working on android

### ISSUE THREAD

**Issue by darkylmnx** [nativescript-vue/nativescript-vue#153]
## Env
tns : 3.4.3
vue-cli : 3.0.0-beta.6
template : nativescript-vue/vue-cli-template
```
"dependencies": {
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^1.3.1",
    "tns-core-modules": "~3.4.1"
  }
```

## Issue
I just freshly started an app with ns-vue but as soon as i tried to show my first component (TextView), the multiline didn't work. I copied/pasted the code from the doc but apparently it's not working.

## Screens
![image](https://user-images.githubusercontent.com/1426357/37855815-8f7b6634-2ef1-11e8-82e5-cd475fdb7d1e.png)
![image](https://user-images.githubusercontent.com/1426357/37855867-d4323384-2ef1-11e8-9700-4c57722970a2.png)

copied from the doc here => https://nativescript-vue.org/en/docs/elements/components/text-view/

EDIT : I figured out that when i use
`<TextView :text="'Multi\nLine\nText'" editable="false" />`
instead of
`<TextView text="Multi\nLine\nText" editable="false" />`
it works, i think it should be said in the docs.

The example with **FormattedString** though still doesn't work.

**Comment by darkylmnx** [comment]
@rigor789 the issue is till valid when using formatting with span, the multiline doesn't work

**Comment by rigor789** [comment]
You need to insert the `\n` in order to create a new line, the example above shows the intended result.

If you add `\n` (using `:text=` as you mentioned above) it will display multiple lines.

**Comment by darkylmnx** [comment]
@rigor789 this is a copy paste from the doc + result in the android emulator. The multi-line doesn't work with spans.

![image](https://user-images.githubusercontent.com/1426357/40274939-f788c748-5be3-11e8-8d52-52557509d2ef.png)

**Comment by rigor789** [comment]
@darkylmnx fixed the ordering in docs, the screenshot was below the `multi-style` snippet instead of the first snippet.

The one you are pasting does not have line breaks `\n` anywhere, and the output is correct - the title of the section was `multi-line` by mistake.

**Comment by darkylmnx** [comment]
@rigor789 okay I added the "\n" and it still didn't work till I binded the value, that's quite weird like behaviour

**Comment by darkylmnx** [comment]
![image](https://user-images.githubusercontent.com/1426357/40280353-031c5656-5c52-11e8-8d80-cad3f1c6790c.png)

**Comment by rigor789** [comment]
I've tried `<TextView text="Multi\nLine\nText" />` and it displayed multiple lines, but there is nothing in ns-vue that alters the values (no html-entities decoding etc.)

**Comment by darkylmnx** [comment]
@rigor789 I'm talking about formattedString as my screenshhot shows, with the vue-cli template
![image](https://user-images.githubusercontent.com/1426357/40280473-6165cdbc-5c54-11e8-82bd-8b957ad2d782.png)

**Comment by rigor789** [comment]
Yes I know, just pointing out that weirdly the `<TextView text="Multi\nLine\nText" />` version works without binding the text.

**Comment by darkylmnx** [comment]
@rigor789 not on my version lol

![image](https://user-images.githubusercontent.com/1426357/40280626-02478d36-5c57-11e8-8b82-bc232823c070.png)

**Comment by rigor789** [comment]
I've tried in the playground, guess it's different with the vue-cli-template.

At one point we had html entities decoding, but the lib size grew significantly, and caused unintended behavior, so it was ditched soon after. I think using a binding is an ok solution for now
