### ISSUE TITLE
Update docs for TimePicker and DatePicker

### ISSUE THREAD

**Issue by yassipad** [nativescript-vue/nativescript-vue#154]
Just because I ran into an issue where my date/time pickers would not trigger value change... simply because the events are respectively "dateChange" and "timeChange" instead of "dateChanged" and "timeChanged" as defined in the docs:

https://nativescript-vue.org/en/docs/elements/components/time-picker/#events
https://nativescript-vue.org/en/docs/elements/components/date-picker/#events

**Comment by rigor789** [comment]
This issue was moved to nativescript-vue/nativescript-vue.org#70
