### ISSUE TITLE
Are there other Android $navigateTo transition options?

### ISSUE THREAD

**Issue by 7immer** [nativescript-vue/nativescript-vue#155]
When using $navigateTo is it possible to change the android transition from fade to something else?

Also is it possible to have no transition at all?

Cheers

**Comment by 7immer** [comment]
Awesome just found: https://github.com/nativescript-vue/nativescript-vue/blob/master/platform/nativescript/plugins/navigator-plugin.js

It appears you can do this:

```
this.$navigateTo(MyPage, {
  animated: true,
  transition: {
    name: 'flip',
    duration: 2000,
    curve: 'linear'
  }
} )
```

**Comment by 7immer** [comment]
Might be useful to document that one :)

**Comment by rigor789** [comment]
Has been documented recently: https://nativescript-vue.org/en/docs/routing/manual-routing/#navigateto
