### ISSUE TITLE
Howto: ReferenceError: page is not defined

### ISSUE THREAD

**Issue by doctormellow** [nativescript-vue/nativescript-vue#156]
So I'm attempting to modify a TextView based off of previous inputs... I initialize my page variable as the following

```
  export default {
    data() {        
      return {
        page: arguments.object,
        intCount: 0,
        strCount: "Your count is 0",
        userName: "",
        adjustedUsername: "",
      };
    },
// etc here
```

I've tried referencing page as this.$route but honestly I don't know how to grab the psuedo DOM as listed in this NativeScript tutorial 

https://docs.nativescript.org/tutorial/chapter-4#chapter-4nativescript-modules
which uses this code:

```
exports.loaded = function(args) {
    page = args.object;
    var listView = page.getViewById("groceryList");
    page.bindingContext = pageData;

    groceryList.empty();
    pageData.set("isLoading", true);
    groceryList.load().then(function() {
        pageData.set("isLoading", false);
        listView.animate({
            opacity: 1,
            duration: 1000
        });
    });
};
```

**Comment by rigor789** [comment]
You can grab the element by assigning a reference to it https://vuejs.org/v2/api/#ref

In most cases you probably don't need to, and can do most of the things just by using data binding.
