### ISSUE TITLE
Navigation back button is not working

### ISSUE THREAD

**Issue by Dineshkumarraman** [nativescript-vue/nativescript-vue#158]
I used the default navigation back button  <NavigationButton text="Go back" android.systemIcon="ic_menu_back" @tap="goBack" /> but it is not working

**Comment by rigor789** [comment]
What does the `goBack` method look like in your `methods` object?

**Comment by Dineshkumarraman** [comment]
Instead of "goBack" I tried "$navigateBack" -  <NavigationButton text="Go Back" android.systemIcon="ic_menu_back" @tap="$navigateBack"/> .. It navigated back to previous screen but it crashed with an error - "**An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed
TypeError: Cannot read property '__ob__' of undefined**"

**Comment by 7immer** [comment]
Sounds like this may not be related to `$navigateBack`.

$navigateBack appears to be working fine here:
https://play.nativescript.org/?template=play-vue&id=jk2XIt

Check if any of the other objects in your code are returning `undefined`. Perhaps start with searching for the word `ob`.

**Comment by rigor789** [comment]
If you are using the router, then you need to use `$router.back()`.

@7immer `ob` is the Vue observer implementation on observed objects (or something along the lines, been a while since i had to touch that)

**Comment by Dineshkumarraman** [comment]
Thanks @7immer and @rigor789 error is solved when I delete everything and after new installation.

**Comment by Dineshkumarraman** [comment]
Thanks @7immer and @rigor789 issue is solved when I delete and installed the app again
