### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by Dineshkumarraman** [nativescript-vue/nativescript-vue#161]
I got this error while importing a component in main.js file. (e.g) - import Login from './components/Login/Login.vue' and we get another error - SyntaxError: Unexpected token import ... when we try to use import keyword.. we already installed babel transpiler...

**Comment by 7immer** [comment]
What template are you using? It's pretty hard to diagnose something without an error stack or seeing any code

**Comment by Dineshkumarraman** [comment]
I have uploaded the file in my github --[](https://github.com/Dineshkumarraman/LoginModule-vue) ...Still I got the error--  **SyntaxError: Unexpected token import** ..Can you find out the solution

**Comment by rigor789** [comment]
`import/export` are not supported without babel. Playground / your github link both use vanilla js, so to solve the issue, use `require` instead. 

So Instead of 
```js
import Vue from 'nativescript-vue';
```
use 
```js
const Vue = require('nativescript-vue');
```
