### ISSUE TITLE
background image css with local url does not work as expected

### ISSUE THREAD

**Issue by tuqire** [nativescript-vue/nativescript-vue#163]
Hi,

When giving an element a background image stored locally, valid CSS syntax seems to not work. 

What works:

`background-image: ~/images/search.png`

What doesn't work, but imo should:

`background-image: url('~/images/search.png')`

**Comment by rigor789** [comment]
Are you using the `vue-cli-template`? I believe this has to be set up in the webpack config, so it ignores paths, and doesn't try to replace them.

**Comment by tuqire** [comment]
@rigor789 yep that's right. I have tried a few things, including setting `options.css` to `false` inside the `css-loader`, but it does not seem to work. Am I missing something?

**Comment by rigor789** [comment]
I'm not sure, I couldn't find anything for disabling that behavior (https://vue-loader.vuejs.org/en/configurations/asset-url.html)

**Comment by tuqire** [comment]
yeh same. I will ask inside the vlue-cli template repo. Thank you.
