### ISSUE TITLE
WebViews not loading websites within simulator

### ISSUE THREAD

**Issue by 7immer** [nativescript-vue/nativescript-vue#164]
Hello,
I'm trying to load web addresses in a webview on the iPhone simulator but can't get it to work.

**Whats not working**

- Webview does not load any web addresses in the iphone simulator ie http://google.com
- I've tried this within both available templates (nativescript-vue/vue-cli-template, nativescript-vue/nativescript-vue-template)
- The loadFinished event does not work where `src="http://google.com"`

**What is working**

- https://play.nativescript.org/?template=play-vue&id=V7LAow
- loadStarted event where `src="http://google.com"`
- `src="<html><body><div>hello world</div></body></html>"`

**Thoughts**

- Are there any permissions that need to be set on IOS to get the internet to work from within an app?
- Within the iphone simulator Safari is able to load websites.

Any advise would be awesome!

Cheers

**Comment by 7ammer** [comment]
Just adding that this does work fine in Android simulators

**Comment by 7ammer** [comment]
Soo, weirdly if I change the url to **https://** google.com it works! What's more odd is I still can't get `https://www.nativescript.org` to work.

**Comment by sudhanshu-15** [comment]
Facing the same issue with WebView on iOS simulator.
adding `src="http://www.google.com"` doesn't work.
Tried setting src using code and it doesn't work either: 
`this.$refs.webViewLogin.nativeView.src = 'http://www.google.com'`
When I added `https` it works for google.

**Comment by rigor789** [comment]
I'm closing this because it is an issue with nativescrpt core, because there is nothing in nativescript-vue that would affect it.
