### ISSUE TITLE
How implement decidePolicyForNavigationAction and didReceiveAuthenticationChallenge  in WebView?

### ISSUE THREAD

**Issue by facuesr** [nativescript-vue/nativescript-vue#170]
I'm trying to migrate an old objective C app, but I cannot figure out how to implement decidePolicyForNavigationAction and didReceiveAuthenticationChallenge in the nativescript-vue.
Is it possible to implement these methods?

**Comment by rigor789** [comment]
To implement native code, you have to convert it to JS.

There is a guide on the nativescript website here: https://docs.nativescript.org/runtimes/ios/Overview

(check the sidebar for more)
