### ISSUE TITLE
Multi level navigation error

### ISSUE THREAD

**Issue by jgirgis85** [nativescript-vue/nativescript-vue#172]
I am trying to navigate from a list of items to an indiviual view for one of the list items but I keep getting this error no matter how I structure the routes.

```
[Vue warn]: Error in directive view inserted hook: "Error: View already has a parent. View: ActionBar(28) Parent: Page(27)"
JS:
JS: found in
JS:
JS: ---> <ActionBar>
JS:        <Root>
```

My routes file looks like below:

````
import Vue from 'nativescript-vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter);

import Home from '../components/Home';
import Runs from '../components/Runs';
import Run from '../components/Run';
import RunList from '../components/RunList';
import Counter from '../components/Counter';

const router = new VueRouter({
  pageRouting: true,
  routes: [
    {
      name:'home',
      path: '/home',
      component: Home,
      meta: {
        title: 'Home',
      },
    },
    {
      path: '/runs',
      component: Runs,
      meta: {
        title: 'Runs',
      },
    },
    {
      path: '/run',
      component: Run,
      meta: {
        title: 'Run',
      },
      children: [
                  {
                      path: "",
                      name: "runList",
                      component: RunList
                  }
              ]
    },
    {path: '*', redirect: '/home'},
  ],
});

router.replace('/home');

module.exports = router;```

**Comment by jgirgis85** [comment]
I tried both component and page routing but they were giving the same error. 

But no prob I will give manual routing a go if that's more stable currently.

Thanks for the reply and the fantastic work Igor.

**Comment by jgirgis85** [comment]
Sorry just one more question.

In the example of manual routing in the docs you are defining components as variables and then calling them in the Navigateto function but how can I do the same with single file components like the structure in the vue-cli-template? 

Thanks in advance.

**Comment by rigor789** [comment]
You can just import the like normal and call a navigateTo with the imported single file component.

**Comment by jgirgis85** [comment]
Perfect that works. Thanks Igor.
