### ISSUE TITLE
How to integrate nativescript-vue to an existing App?

### ISSUE THREAD

**Issue by lusnaow** [nativescript-vue/nativescript-vue#173]
Hi, how to integrate nativescript-vue to an existing App? Just rewrite some views in nativescript-vue, not all. Can not find any information about this in docs.

**Comment by rigor789** [comment]
Hi, this is more of a nativescript feature than a nativescript-vue one. You can read more about it in the official nativescript docs here: https://docs.nativescript.org/integration-with-existing-ios-and-android-apps/extend-existing-android-app
