### ISSUE TITLE
How to enable LiveSync? 

### ISSUE THREAD

**Issue by moneymc** [nativescript-vue/nativescript-vue#174]
Hi. 

How can i enable LiveSync in my app? I start development with https://github.com/nativescript-vue/vue-cli-template template. After saving code app is restarting. 

Thx.

**Comment by rigor789** [comment]
If you are looking for instant changes on the device, unfortunately that is not supported yet. The NativeScript CLI (which is responsible for copying the app files to the device) currently only supports instant changes for CSS changes only, if javascript changes the app will be reloaded no matter what. This current behavior is called LiveSync, what you might be after is HMR (Hot Module Replacement) where changes in the javascript/templates can be reflected on the device instantly, and this feature is on the official NativeScript roadmap. Once it is supported in NativeScript, we will add support for it in NativeScript-Vue.

**Comment by moneymc** [comment]
Sorry, maybe I misunderstood.

When i start development with this https://docs.nativescript.org/tutorial/chapter-1 article and do exercise LiveSync, that works like HMR, UI is updating without app reloading. How can do this with vue template? 

Thx.

**Comment by moneymc** [comment]
Thank you for your answer and your work.

**Comment by moneymc** [comment]
Sorry, one more question. 

In release notes (https://www.nativescript.org/roadmap-and-releases#releases) HMR will be release in version 4.2, but in 4.0 (this april, now devepng) i found «Enable LiveSync with Webpack». Maybe this is what I was asking about? 

Thx.
