### ISSUE TITLE
Data Form Component (RadDataForm) : using metadata results an error on Android

### ISSUE THREAD

**Issue by budi7** [nativescript-vue/nativescript-vue#176]
Hi, i'am totally new here. I'm not sure whether this is bug or not.

So, the problems began when i added some metadata property on the component. Maybe you guys would glad to help?

NOTES:
1. i'am using nativescript playground to play arround (please kindly go here : https://play.nativescript.org/?template=play-vue&id=urFJQf)
2. i'am using android 4.2 
3. on IOS it's all good (IOS 11.2.6)

**Here is my code :** 
require("nativescript-vue").registerElement("RadDataForm", () => require("nativescript-ui-dataform").RadDataForm);
const Vue = require("nativescript-vue");

new Vue({
  data() {
    return {
      profile: {
        name: "Ed Sheeran",
        age: "9",
        email: ""
      },
      profileMetadata: {
        "isReadOnly": false,
        "commitMode": "Immediate",
        "validationMode": "Immediate",
        "propertyAnnotations":
        [
          {
            "name": "name",
            "displayName": "Name",
            "index": 0
          },
          {
            "name": "age",
            "displayName": "Age",
            "index": 1,
            "editor": "Number"
          },
          {
            "name": "email",
            "displayName": "E-Mail",
            "index": 2,
            "editor": "Email"
          },
        ]
      }
    }
  },

  template: `
    <Page class="page">
      <ActionBar title="Home" class="action-bar" />
      <ScrollView>
        <RadDataForm :source="profile" :metadata="profileMetadata" />
      </ScrollView>
    </Page>
  `,

}).$start();

**And this was the error :** 
`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.Error: The data form editor for property age must have a constructor that accepts a RadDataForm and an EntityProperty.
    com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:56)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.createEditor(DataFormEntityAdapter.java:146)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.getEditorsForEntity(DataFormEntityAdapter.java:65)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:793)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
    android.app.Fragment.performCreateView(Fragment.java:1695)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
    android.app.BackStackRecord.run(BackStackRecord.java:682)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
    android.app.Activity.performResume(Activity.java:5265)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2805)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2844)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2291)
    android.app.ActivityThread.access$600(ActivityThread.java:144)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:137)
    android.app.ActivityThread.main(ActivityThread.java:5166)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:525)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
    dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
    java.lang.reflect.Constructor.constructNative(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:417)
    com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:54)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.createEditor(DataFormEntityAdapter.java:146)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.getEditorsForEntity(DataFormEntityAdapter.java:65)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:793)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
    android.app.Fragment.performCreateView(Fragment.java:1695)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
    android.app.BackStackRecord.run(BackStackRecord.java:682)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
    android.app.Activity.performResume(Activity.java:5265)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2805)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2844)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2291)
    android.app.ActivityThread.access$600(ActivityThread.java:144)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:137)
    android.app.ActivityThread.main(ActivityThread.java:5166)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:525)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
    dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
    com.telerik.widget.dataform.visualization.editors.DataFormIntegerEditor.<init>(DataFormIntegerEditor.java:38)
    com.telerik.widget.dataform.visualization.editors.DataFormIntegerEditor.<init>(DataFormIntegerEditor.java:22)
    java.lang.reflect.Constructor.constructNative(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:417)
    com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:54)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.createEditor(DataFormEntityAdapter.java:146)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.getEditorsForEntity(DataFormEntityAdapter.java:65)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:793)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
    android.app.Fragment.performCreateView(Fragment.java:1695)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
    android.app.BackStackRecord.run(BackStackRecord.java:682)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
    android.app.Activity.performResume(Activity.java:5265)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2805)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2844)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2291)
    android.app.ActivityThread.access$600(ActivityThread.java:144)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:137)
    android.app.ActivityThread.main(ActivityThread.java:5166)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:525)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
    dalvik.system.NativeStart.main(Native Method)
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js, line: 527, column: 26

StackTrace: 
	Frame: function:'RadDataForm.reload', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 527, column: 27
	Frame: function:'RadDataForm._updateMetadata', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 200, column: 14
	Frame: function:'RadDataForm.createNativeView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 100, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 412, column: 35
	Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38

	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2815)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2844)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2291)
	at android.app.ActivityThread.access$600(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5166)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.Error: The data form editor for property age must have a constructor that accepts a RadDataForm and an EntityProperty.
    com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:56)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.createEditor(DataFormEntityAdapter.java:146)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.getEditorsForEntity(DataFormEntityAdapter.java:65)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:793)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
    android.app.Fragment.performCreateView(Fragment.java:1695)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
    android.app.BackStackRecord.run(BackStackRecord.java:682)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
    android.app.Activity.performResume(Activity.java:5265)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2805)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2844)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2291)
    android.app.ActivityThread.access$600(ActivityThread.java:144)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:137)
    android.app.ActivityThread.main(ActivityThread.java:5166)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:525)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
    dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
    java.lang.reflect.Constructor.constructNative(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:417)
    com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:54)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.createEditor(DataFormEntityAdapter.java:146)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.getEditorsForEntity(DataFormEntityAdapter.java:65)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:793)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
    android.app.Fragment.performCreateView(Fragment.java:1695)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
    android.app.BackStackRecord.run(BackStackRecord.java:682)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
    android.app.Activity.performResume(Activity.java:5265)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2805)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2844)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2291)
    android.app.ActivityThread.access$600(ActivityThread.java:144)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:137)
    android.app.ActivityThread.main(ActivityThread.java:5166)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:525)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
    dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
    com.telerik.widget.dataform.visualization.editors.DataFormIntegerEditor.<init>(DataFormIntegerEditor.java:38)
    com.telerik.widget.dataform.visualization.editors.DataFormIntegerEditor.<init>(DataFormIntegerEditor.java:22)
    java.lang.reflect.Constructor.constructNative(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:417)
    com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:54)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.createEditor(DataFormEntityAdapter.java:146)
    com.telerik.widget.dataform.visualization.DataFormEntityAdapter.getEditorsForEntity(DataFormEntityAdapter.java:65)
    com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:793)
    com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
    android.app.Fragment.performCreateView(Fragment.java:1695)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
    android.app.BackStackRecord.run(BackStackRecord.java:682)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
    android.app.Activity.performResume(Activity.java:5265)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2805)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2844)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2291)
    android.app.ActivityThread.access$600(ActivityThread.java:144)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:137)
    android.app.ActivityThread.main(ActivityThread.java:5166)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:525)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
    dalvik.system.NativeStart.main(Native Method)
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js, line: 527, column: 26

StackTrace: 
	Frame: function:'RadDataForm.reload', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 527, column: 27
	Frame: function:'RadDataForm._updateMetadata', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 200, column: 14
	Frame: function:'RadDataForm.createNativeView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 100, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 412, column: 35
	Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
	at android.app.Fragment.performCreateView(Fragment.java:1695)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.Activity.performResume(Activity.java:5265)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2805)
	... 12 more
Caused by: java.lang.Error: The data form editor for property age must have a constructor that accepts a RadDataForm and an EntityProperty.
	at com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:56)
	at com.telerik.widget.dataform.visualization.DataFormEntityAdapter.createEditor(DataFormEntityAdapter.java:146)
	at com.telerik.widget.dataform.visualization.DataFormEntityAdapter.getEditorsForEntity(DataFormEntityAdapter.java:65)
	at com.telerik.widget.dataform.visualization.RadDataForm.load(RadDataForm.java:793)
	at com.telerik.widget.dataform.visualization.RadDataForm.reload(RadDataForm.java:485)
	... 26 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at com.telerik.widget.dataform.visualization.registries.EditorRegistry.createEditorFromMetadata(EditorRegistry.java:54)
	... 30 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at com.telerik.widget.dataform.visualization.editors.DataFormIntegerEditor.<init>(DataFormIntegerEditor.java:38)
	at com.telerik.widget.dataform.visualization.editors.DataFormIntegerEditor.<init>(DataFormIntegerEditor.java:22)
	... 33 more`

Regards

**Comment by 7ammer** [comment]
Hello, I'm not sure how 'RadDataForm' works but it looks like you've not installed the `nativescript-ui-dataform` package in the `play.nativescript.org` link. It needs adding to the project.

**Comment by 7ammer** [comment]
Oh, scratch that. 
`age: "9",` needs to be `age: 9,`

**Comment by 7ammer** [comment]
Oh, scratch that.
age: "9", needs to be age: 9,

**Comment by rigor789** [comment]
As @7ammer said, change `age: "9"` to `age: 9` and it should work:

https://play.nativescript.org/?template=play-vue&id=urFJQf&v=2

**Comment by budi7** [comment]
thank you @7ammer  & @rigor789 for your help.
By changing  age: "9" to age: 9 the error is gone
