### ISSUE TITLE
Can't access page vue instance in itemTap event of ListView

### ISSUE THREAD

**Issue by omerilhans** [nativescript-vue/nativescript-vue#177]
<template>
  <Page>
    <ActionBar class="action-bar" title="List Page">
        <NavigationButton text="Go Back" 
                          android.systemIcon="ic_menu_back" 
                          @tap="$navigateBack()" />
    </ActionBar>

    <ListView for="item in listOfItems" @itemTap="onItemTap">
      <v-template>
        <Label :text="item.text"/>
      </v-template>

      <v-template if="$odd">
        <Label :text="item.text" color="red" />
      </v-template>
    </ListView>

  </Page>
</template>

<script>
export default {  
  methods: {
    onItemTap() {
        const vm = this;
        // vm is not the page vue instance
    }
  },
data() {
      return {
        listOfItems: [
            { text: 'First' }, 
            { text: 'Second' },
            { text: 'Third' },
            { text: 'Fourth' }
        ]
      }
  }
}
</script>
```

In the example on itemTap event handle of ListView the method is not bind to page's vue instance.

**Comment by 7ammer** [comment]
Are you trying to get access to the 'page' view?

```
<page ref="myPage">
</page>
```

```
onItemTap() {
   let myPage = this.$refs.myPage; // the app's page view
}
```

**Comment by omerilhans** [comment]
No i dont. I'm trying to get access to page's vue instance

**Comment by rigor789** [comment]
`this` in the handler is the vue vm instance, can you [create a playground](https://play.nativescript.org/) of the issue? I think something else might be your issue, because I'm using `@itemTap` and have no problems accessing the vm.

**Comment by omerilhans** [comment]
The issue was resolved by removing the dist folder and rerunning it. 👍
