### ISSUE TITLE
How to pass data between pages using navigateTo

### ISSUE THREAD

**Issue by drehimself** [nativescript-vue/nativescript-vue#178]
Hello!

I'm not sure how to pass data between pages when using `$navigateTo`.

Here's one of the example apps with a slight modification: [app-with-pages.js](https://github.com/nativescript-vue/nativescript-vue/blob/master/samples/app/app-with-pages.js)

```js
methods: {
  openPage() {
    const foo = 'bar'
    this.$navigateTo(DetailsPage)
  }
}
```
I just want to pass `foo` into the `DetailsPage`.

I found this issue: #123 where you proposed this solution, which does work for me.

```javascript
const test = 1;
this.$showModal({
  template: `
    <Page>
      <StackLayout>
        <Label text="${test}" />
      </StackLayout>
    </Page>
  `
})
```
However, if I want to keep the other component on its own, I can't get it to work.

I tried this as proposed in the other issue. It doesn't work for me. I know I'm probably doing it wrong or missing something.

``` javascript
const Constructor = Vue.extend(DetailsPage)
const vm = new Constructor(foo)
this.$navigateTo(vm)
```
Ideally, passing in params like this would be awesome. 
```javascript
this.$navigateTo(DetailsPage, { foo: 'bar' })
```
Then accept `foo` as a prop on the `DetailsPage`.

Thanks so much! Loving Vue NativeScript.

**Comment by rigor789** [comment]
Hi, you can pass props using

```js
this.$navigateTo(DetailsPage, { context: { propsData: { foo: 'bar' }}}
```

This is not currently documented, but will be as soon as we merge this pr: https://github.com/nativescript-vue/nativescript-vue.org/pull/88
