### ISSUE TITLE
"created" lifecycle event not called for the first Component

### ISSUE THREAD

**Issue by olachris** [nativescript-vue/nativescript-vue#183]
The "created" lifecycle event doesnt seem to work for the first component that the app loads, e.g. the App component passed here:
```
new Vue({
  render: h => h(App),
}).$start()
```

To replicate this i updated the app-with-pages.js sample to add a "created" function for both components, here is this code:
```
const Vue = require('./nativescript-vue')

const App = {
  template: `
    <StackLayout>
      <Button text="Open page" @tap="openPage" />
    </StackLayout>
  `,

  methods: {
    openPage() {
      this.$navigateTo(DetailsPage)
    }
  },

  created: function() {
    alert('1');
  }
}

const DetailsPage = {
  template: `
    <StackLayout>
      <Label :text="'Details ' + Math.random()" />
      <Button text="another" @tap="openDetails" />
      <Button text="back" @tap="goBack" />
    </StackLayout>
  `,

  methods: {
    openDetails() {
      this.$navigateTo(DetailsPage)
    },
    goBack() {
      this.$navigateBack()
    }
  },

  created: function() {
    alert('2');
  }
}

new Vue({
  render: h => h(App),
}).$start()
```

When this sample runs, the first alert('1') is not fired, but if you click to navigate to the DetailsPage component then the alert('2') is fired successfully. So it seems like the "created" event is not fired for that first component.

Is this expected behaviour? or is it a bug?

Thanks for your great work

**Comment by rigor789** [comment]
Have you tried logging to the console instead of an `alert()`? The alerts probably don't work before the `mounted` hook fires (when all the elements are created and the app is started). The `created` callback is fired before NativeScript boots, the second alerts fires because at that point the application is started, and only a navigation occurs.

**Comment by olachris** [comment]
Ignore that...i just wrapped the `this.$navigateTo(DetailsPage);` line in a setTimeout and it worked!

So the sample code is the same as above but the `mounted` hook is now:
```
mounted: function() {
    setTimeout(() => {
      this.$navigateTo(DetailsPage);
    }, 300);
  }
```

That does indeed load up the app and immediately navigate as expected! 

I will close the issue, thanks for the help and again for the great work with this, im excited to be using vuejs with nativescript!

**Comment by rigor789** [comment]
Another idea worth trying is to do the logic like this:

```js
new Vue({
  render: h => h(isLoggedIn ? App : LoginPage),
}).$start()
```
