### ISSUE TITLE
Bug related to the life cycle of an Android application

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue#185]
_From @Fabiyo-90 on April 17, 2018 18:48_

I am on android, once I press the button "back" and that the application is found in pause "onPause ()", and then I click on the icon of the application to engage "surResume ()" then the application bug. Once stop "onStop ()", click on the icon while it normally starts. Bug related to the life cycle of an Android application.

_Copied from original issue: nativescript-vue/nativescript-vue.org#95_

**Comment by rigor789** [comment]
@Fabiyo-90 I'm not sure if I understand you correctly, but if you are talking about the issue where if the activity gets suspended and then recreated the app is unresponsive (no events or bindings work) then yes, that's an issue that I'm currently investigating. It is an issue in NativeScript core too, so I'm not sure how to fix it yet.

**Comment by Fabiyo-90** [comment]
You'll need to make sure you have a good time and you're just a bug car. You're welcome to go to the community of the carriers. You suis étudiant and RD Congo, pays francophone.
Sinon Nativescript-vue est un superbe project d'autant plus que lé framework vuejs est très simple et facile à prendre en main.
Grand merci pour ce gift

**Comment by Fabiyo-90** [comment]
it's exactly that, I'm preparing a presentation to my friends and I would not like a bug because I'm trying to create a mobile developer community around nativescript-view. I am a student in DR Congo, French speaking country.
Else Nativescript-view is a great project especially since the framework vujs is very simple and easy to handle.
Thank you for this gift

**Comment by Fabiyo-90** [comment]
I pray that this bug is quickly solved

**Comment by rigor789** [comment]
I've released an rc build which should fix the issue, can you try it and let me know if it works for you? 

`nativescript-vue@1.3.2-rc.2`

**Comment by Fabiyo-90** [comment]
I love nativescript-vue

**Comment by Fabiyo-90** [comment]
I love NativeScript-Vuem I will test it right now !

**Comment by Fabiyo-90** [comment]
I'ts not working ! here is my bug
https://user-images.githubusercontent.com/26508533/38934781-7c6e024a-4314-11e8-88f9-e809d1845bbd.PNG

**Comment by Fabiyo-90** [comment]
With the version "nativescript-vue@1.3.2-rc.2" the application bug when launching "onCreate ()", but with this version "nativescript-vue@1.3.2-rc.1", the application does not bug anymore. I think that I will work with this version "nativescript-vue@1.3.2-rc.1"

**Comment by Tronix117** [comment]
As a work-around, you can use
```
if (isAndroid) {
  application.android.on(application.AndroidApplication.activityBackPressedEvent, backEvent)
  function backEvent(args) {
    const tm = topmost()
    if (tm.backStack.length) return
    args.cancel = true

    const startMain = new android.content.Intent(android.content.Intent.ACTION_MAIN)
    startMain.addCategory(android.content.Intent.CATEGORY_HOME)
    startMain.setFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK)

    const activity = application.android.startActivity ||
                     application.android.foregroundActivity ||
                     tm.android.currentActivity ||
                     tm.android.activity

    activity.startActivity(startMain)
  }
}
```

it prevents the app to suspend, and goes directly to dashboard.

**Comment by Fabiyo-90** [comment]
La version nativescript-vue@1.3.2-rc.2 bug lors du démarage de l'application même pour un "Hello world !" mais en essayant la version nativescript-vue@1.3.2-rc.1, il n'y a aucun bug et fonctionne très bien.
J'utilise la version nativescript@4.0.0, tns-android@4.0.1, tns-core-module@4.0.0
![tns_bug_2](https://user-images.githubusercontent.com/26508533/39094582-82a99a62-4629-11e8-9826-a7c0e848964e.PNG)

**Comment by Fabiyo-90** [comment]
The version nativescript-vue@1.3.2-rc.2 bug when starting the application even for a "Hello world!" but trying the nativescript-vue@1.3.2-rc.1 version, there is no bug and works very well.
I am using the version nativescript@4.0.0, tns-android@4.0.1, tns-core-module@4.0.0.
![tns_bug_2](https://user-images.githubusercontent.com/26508533/39094601-c889677e-4629-11e8-970a-b3ca12cb1cba.PNG)

**Comment by hoatructhanhlam** [comment]
> I also have same problem with nativescript-vue 1.3.2-rc.* (both tns-core-modules 3.4.1 or 4.0.0)

**Comment by Fabiyo-90** [comment]
Hello hoatructhanhlam ! try nativescript-vue.1.3.2-rc.1

**Comment by championswimmer** [comment]
I have a hacky workaround this problem

First make sure on exit event you **really really** exit the app

```typescript
import * as application from 'tns-core-modules/application'
import {exit} from 'nativescript-exit'

/*
 * Force an exit, instead of trying to remount
 * FIXME: On upgrade to nativescript-vue 2.x this wont be necessary
 */
application.on(application.exitEvent, (args: ApplicationEventData) => {
  exit()
})
```

Next, to make back button work as page routing 

```typescript
/*
 * Go back if in a nested route. If top level route, just do what android does
 */
if (application.android) {
  application.android.on(
    AndroidApplication.activityBackPressedEvent,
    (data: AndroidActivityBackPressedEventData) => {
      if (router.currentRoute.path.split('/').length > 2) {
        router.back()
        data.cancel = true
      }
    }
  )
}
```

**Comment by msaelices** [comment]
@Fabiyo-90 I've added this sample app which tests all the Android events: https://github.com/nativescript-vue/nativescript-vue/commit/014e8129ca394093e58a6c13f514fa37ae37a39c

I've tested pausing and resuming the app and is still responsive, as you can see here:

![screenshot_1533203254](https://user-images.githubusercontent.com/136875/43576814-858a881a-964a-11e8-861f-7620f8d04428.png)

So closing this issue. Please re-open if I missed something.
