### ISSUE TITLE
Feature: expose a refresh method from the list-view component

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue#193]
- [ ]  update docs https://github.com/nativescript-vue/nativescript-vue.org/pull/97

**Comment by MisterBrownRSA** [comment]
Close this perhaps ?

**Comment by rigor789** [comment]
Not yet, still plan to add a shortcut method for refreshing the listview.

**Comment by rigor789** [comment]
Note: update docs when change is released.
