### ISSUE TITLE
do not do pageRouting for nested pages

### ISSUE THREAD

**Issue by championswimmer** [nativescript-vue/nativescript-vue#195]
if my routes are like this 
```
- route1
  - route1-1
  - route1-2
- route2
- route3
```

I want pageRouting when going to `/route1` or `/route2`
But when going from `/route1` to `/route1/route1-1` I want component routing.

**Comment by rigor789** [comment]
This will be possible with the upcoming changes to the way page routing is handled. Tracked in #214
