### ISSUE TITLE
invalid prop assignment

### ISSUE THREAD

**Issue by richardo2016** [nativescript-vue/nativescript-vue#198]
https://github.com/nativescript-vue/nativescript-vue/blob/af1dbc324662414fba766bb4233b8959ef002f2b/samples/app/app-with-tab-view.js#L35

this line should be `<Label :text="tab.text" /> `

**Comment by rigor789** [comment]
Feel free to open a PR with this change - since these samples are mostly used during the development of the library it's not a high priority to change this
