### ISSUE TITLE
iOS ScrollView when trying to scroll crashes on Physical and Emulator

### ISSUE THREAD

**Issue by andreMariano90** [nativescript-vue/nativescript-vue#201]
Probably is a similar issue to his one: [https://github.com/nativescript-vue/nativescript-vue/issues/24](url)
My code works fine on android but it crashes on iOS
```javascript
(Foundation) *** Assertion failure in -[UIGestureGraphEdge initWithLabel:sourceNode:targetNode:directed:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.33.6/Source/GestureGraph/UIGestureGraphEdge.m:25
```

Android Sample Running:
![android_gif](https://user-images.githubusercontent.com/1918494/39262806-d83390c2-4896-11e8-979e-4275a7cab0c5.gif)

IOS Sample Crashing
![ios_gif](https://user-images.githubusercontent.com/1918494/39262881-1176d1fa-4897-11e8-8c39-c88f65c6b490.gif)

The code is:
```
    <TabViewItem title="Documentos">
        <ScrollView>
            <tarefas :lista-tarefas="tarefas.DOCUMENTOS"/>
        </ScrollView>
    </TabViewItem>
```
Inside the 'tarefas' component:
```javascript
<template>
    <FlexboxLayout flexDirection="column">
        <StackLayout v-for="item in ListaTarefas" :key="item.ID_TAREFA" class="item">

            <CardView class="card wd-100" radius="0" shadowOffsetWidth="0"
                      shadowOffsetHeight="0" shadowOpacity="0" shadowRadius="0" >
                <FlexboxLayout flexDirection="row">
                    <StackLayout class="barra-situacao" :class="cardStatus(item, true)"></StackLayout>

                    <FlexboxLayout flexDirection="column">
                        <StackLayout class="icone-tarefa wd-30" verticalAlignment="center">

                            <StackLayout v-if="item.TIPO === DOCUMENTO">
                                <image src="~/images/ic_documento.png" class="wd-40"/>
                                <label text="Documento" class="text-center" textWrap="true"/>
                            </StackLayout>

                            <StackLayout v-if="item.TIPO === ORDEM_SERVICO">
                                <image src="~/images/ic_ordem_servico.png" class="wd-40"/>
                                <label text="Ordem de Serviço" class="text-center" textWrap="true"/>
                            </StackLayout>

                            <StackLayout v-if="item.TIPO === PROCESSO">
                                <image src="~/images/ic_processo.png" class="wd-40"/>
                                <label text="Processo" class="text-center" textWrap="true"/>
                            </StackLayout>

                        </StackLayout>
                    </FlexboxLayout>

                    <FlexboxLayout alignItems="column" flexWrap="wrap"
                                   class="wd-70 o-7">
                        <FlexboxLayout alignItems="flex-start" class="card-header">
                            <FlexboxLayout class="wd-50">
                                <image src="~/images/ic_calendario.png"/>
                                <label :text="item.PRAZO" class="data"
                                       :class="cardStatus(item, false)"/>
                            </FlexboxLayout>
                            <FlexboxLayout class="wd-50 label-situacao">
                                <image src="~/images/ic_relogio.png"/>
                                <label :text="labelStatus(item.STATUS)"/>
                            </FlexboxLayout>
                        </FlexboxLayout>
                        <FlexboxLayout alignItems="row" flexWrap="wrap" class="card-body">
                            <label class="nome-tarefa wd-100" :text="item.DESCRICAO"/>
                            <label class="detalhes-tarefa wd-100" :text="item.DETALHES"/>
                        </FlexboxLayout>
                    </FlexboxLayout>
                </FlexboxLayout>
            </CardView>
        </StackLayout>
    </FlexboxLayout>
</template>
```

Inside the tarefas component I don't have any tap event

**Comment by rigoparis** [comment]
Hey guys!

I'm having the same issue. Any ideas what may be happening?

**Comment by andreMariano90** [comment]
Well, I found a workaround and discovered why it isn't easy to catch.
If the Vue class with ScrollView is my first screen. It crashes. I Also had the same problem using the RadCalendar component. 

The workaround is to call another class before this one. You must set a timeout before calling the $navigateTo method otherwise it will crash (using the @loaded or the mounted() method). Well, I created a second splash screen that waits 1 sec before calling the Home class and then everything works fine with any component. I hope it gives any light to the main developers and helps anyone who is having a hard time with it

```
mounted(){
        var vm = this;
        setTimeout(function () {
            //calls the class that was crashing when calling the first time
            //the 'clearHistory' class ignore this class and set the Home class as the first one
            vm.$navigateTo(Home,{clearHistory:true});
        },1000);
    }
```

**Comment by Reached** [comment]
Also have this issue, has a solution been found, or has this even been acknowledged as being an issue? :)

**Comment by sagunkho** [comment]
+1 to have this issue solved ASAP. This library is the future.

**Comment by Reached** [comment]
I can confirm that the workaround @andreMariano90 posted indeed works. If anyone is struggling with implementing this, let me know, maybe I can help :)

**Comment by mrzorn** [comment]
Was banging my head against the wall on this one also - workaround does do the job.

**Comment by yauri-io** [comment]
Why there is no fix yet? :(

**Comment by rigor789** [comment]
@yauri-io we don't know the cause, it is most likely an issue with NativeScript-Core rather than NativeScript-Vue. If you find a fix, feel free to submit a pull request, it's open source.

**Comment by yauri-io** [comment]
@rigor789 I wish I could help but I'm not familiar with NativeScript :( 
If the creator doesn't know what the cause, I think I'll get the same result if I try to figure out the problem. 
Yesterday was my first-day trying nativescript-vue and hit the issue right away.
Then I decided to use the workaround for now.

**Comment by uniquejava** [comment]
Hello, I met this issue today. 

Error message:

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: targetNode'

Here is my code, when I click any of the list item. the app stuck with the above error message.
![issue](https://user-images.githubusercontent.com/1049271/43364027-535cb5a6-9344-11e8-8bf1-ac978f587ac0.jpg)

Home.vue

```html
<ListView for="item in listOfItems" @itemTap="onItemTap">
    <v-template>
      <StackLayout class="list-item">
        <FlexboxLayout>
          <Label class="icon" :text="String.fromCharCode(item.icon)" />
          <Label style="margin-left: 15" flexGrow="1" :text="item.text" />
          <Label v-if="$index === 0" class="broker-type">{{this.useWatson ? 'watson' : 'local'}}</Label>
          <Label class="icon" :text="String.fromCharCode(0xe930)" />
        </FlexboxLayout>
      </StackLayout>

    </v-template>
  </ListView>
```
I worked around this problem by removing `vue-router` completely. 
Before the home page is loaded by `router/index.js` => `router.replace('/home');`

Now, I am rendering home page directly 
```js
new Vue({
  store,
  render: h => h(Home)
}).$start();
```

And the app works again.

BTW , I am trying nativescript-vue from last week.
From my experience, the `vue-cli-template` is very buggy whereas `nativescript-vue-template` works in every case.

**Comment by RinatDav** [comment]
I have the same problem. And partly I decided it as follows:

`<template>
	<Page class="page">
		<FlexboxLayout flexDirection="column" v-if="ready">
			<ScrollView orientation="vertical">
				<StackLayout orientation="vertical">
					...
				</StackLayout>
			</ScrollView>
		</FlexboxLayout>
	</Page>
</template>

<script>
export default {
	data() {
		return { ready: false };
	},
	mounted() {
		this.ready = true;
	},
};
</script>`

But when I add the ActionBar to the Page then the application crashes when I go through this routing and an error occurs in the console:

`CONSOLE ERROR file:///app/app.js:1:73458: [Vue warn]: Error in directive view inserted hook: "Error: View already has a parent. View: ActionBar(12) Parent: Page(11)"

found in

---> <ActionBar>
<Root>`

**Comment by rickdps** [comment]
@Reached If you could help me out it would be great. I have tried @andreMariano90 solution but it didn`t work. Maybe I'm putting the code in the wrong place. Here is my code. 
` new Vue({
         router,
         methods: {
         mounted(){
              var vm = this;
              setTimeout(function () {
               //calls the class that was crashing when calling the first time
              //the 'clearHistory' class ignore this class and set the Home class       
        vm.$navigateTo(Home,{clearHistory:true});
      },1000);
    }
  }
 }).$start();`

Thanks for any help.

**Comment by Tarens2** [comment]
Having the same issue, the issue in vue-router but I also don't know how to solve it

**Comment by Reached** [comment]
@rickdps sorry, somehow your message got lost in my notifications feed.

Don't know if you managed to fix it, otherwise here is what I did:

1. Create a new Vue component called Splash.vue and add the following code:

```vue
<template>
    <Page class="page">
        <Label>Splash Page</Label>
    </Page>
</template>

<script>
    import Newsfeed from './Newsfeed';

    export default {
        mounted() {
            setTimeout(() => {
                //calls the class that was crashing when calling the first time
                //the 'clearHistory' class ignore this class and set the Newsfeed class as the first one
                this.$navigateTo(Newsfeed, {clearHistory: true});
            }, 1);
        }
    }
</script>
```

2. Then in your router file (index.js) add a redirect to the Splash component instead of your main component:

`router.replace('/splash');`

3. As a sidenote I don't think this is an issue in the 2.0 alpha branch (next), however I will would have to test this.
