### ISSUE TITLE
ListView: Property or method "$index" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by altunyurt** [nativescript-vue/nativescript-vue#202]
This following component randomly puts out warnings about $index, $odd and $even not having been defined and being created on the run in template. Warnings are not issued on each navigation to page so it seems that some kind of latency in rendering ie may be the cause.    

    <template>
        <ListView for="pg in product_groups">
            <v-template>
                <StackLayout> 
                  <Label padding="10"  :text="pg.product_name"/> 
                </StackLayout> 
            </v-template>
        </ListView>  
    </template>

    <script type="text/javascript">
    import { mapGetters } from "vuex";

    export default {
      data() {
        return {};
      },

      computed: {
        ...mapGetters(["product_groups"])
      }
    };
    </script>

Warnings i'm getting: 

    JS: [Vue warn]: Property or method "$index" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based c
    omponents, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
    JS: 
    JS: found in
    JS: 
    JS: ---> <ProductsListing> at src/components/game/ProductsListing.vue
    JS:        <AppMain> at src/components/Main.vue
    JS:          <Root>
    JS: [Vue warn]: Property or method "$even" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based co
    mponents, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
    JS: 
    JS: found in
    JS: 
    JS: ---> <ProductsListing> at src/components/game/ProductsListing.vue
    JS:        <AppMain> at src/components/Main.vue
    JS:          <Root>
    JS: [Vue warn]: Property or method "$odd" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based com
    ponents, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
    JS: 
    JS: found in
    JS: 
    JS: ---> <ProductsListing> at src/components/game/ProductsListing.vue
    JS:        <AppMain> at src/components/Main.vue
    JS:          <Root>

Version 1.3.2-rc.4 on android 7.1.1

**Comment by rigor789** [comment]
Can you provide a repo that I can test this with? I've never seen it happen in my projects with ListViews, so I'm curious to find out where this would be coming from.

**Comment by altunyurt** [comment]
Having changed the setup a few times and got back to 1.3.1, I'm not getting those warnings anymore;  i'm not sure if relevant though, since it's my first time working with nativescript on mobile. I'll update if that happens again.  

Thanks
