### ISSUE TITLE
How to create and test local plugins

### ISSUE THREAD

**Issue by andreMariano90** [nativescript-vue/nativescript-vue#206]
Hi Guys! I'm having a really hard time trying to test out my own plugins on other project.

My project is using the vue-cli-template.

I already tried `npm link`, I tried installing a local folder from source and even tried changing the prepare.js file to copy a symbolic link to every node-module folder without any success

How is it done on nativescript-vue without using npm?  Every time I run with
`npm run watch:ios` or `npm run watch:android` It gives me the "Module not found: Error: Can't resolve" error

**Comment by rigor789** [comment]
What I did was to install the plugin using a relative path. I had to change the path in the `template` directory too to make sure it points to the right folder.
