### ISSUE TITLE
set font not work on actionItem

### ISSUE THREAD

**Issue by vitouchhay1** [nativescript-vue/nativescript-vue#208]
<ActionBar color="#fff" backgroundColor="#0056A0" :title="title" v-if="title=='មាត្រា'">
      <NavigationButton color="#fff" text="Go Back" android.systemIcon="ic_menu_back" @tap="$navigateBack"/>
      <ActionItem backgroundColor="#0056A0" color="#fff"  class="fa" :text="'fa-home' | fonticon"/>
    </ActionBar>
i want to  use fontawsome instead of default icon and image on ActionItem

**Comment by rigor789** [comment]
I'm assuming you already have font-icons set up (https://nativescript-vue.org/blog/using-fonticons/)

To show a custom icon in an `ActionItem`, you have to add a `Label` as the child of the `ActionItem` where you can set the icon.

Something like
```html
<ActionBar>
  <ActionItem>
    <Label class="fa" :text="'fa-star' | fonticon" /> 
  </ActionItem>
</ActionBar>
```
