### ISSUE TITLE
Question  !  How can I integrate materialdesignicons.com as font ? 

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-vue/nativescript-vue#210]
I did as in this article but it is not working, https://docs.nativescript.org/ui/icon-fonts 
. I need help !

**Comment by rigor789** [comment]
Here is an article more specific to nativescript-vue https://nativescript-vue.org/blog/using-fonticons/
which covers how you can get icon fonts to work

**Comment by Fabiyo-90** [comment]
http://fluentreports.com/blog/?p=176

Now it 's OK !
