### ISSUE TITLE
when using Vue.extend() the template block doesn't work

### ISSUE THREAD

**Issue by championswimmer** [nativescript-vue/nativescript-vue#211]
So instead of
```js
export default {
   data
   methods
   ...
}
```

If I instead do 

```ts
export default Vue.extend({
   data
   methods
   ...
})
```

Then the template is not loaded and I get `You are running a runtime-only build of Vue` warning. (Which is supposed to happen if template is string, or el is id, *and* no render function exists)

**Comment by championswimmer** [comment]
Using 

```ts
export default Vue.extend({})
```

or using 

```ts
@Component
export default class MyComponent extends Vue {}
```

this is more of a Typescript thing. People who use TS with Vue use this syntax

**Comment by rigor789** [comment]
Thanks for the info, do you think this would be worthy of a blog post? You are welcome to submit a PR to the https://github.com/nativescript-vue/nativescript-vue.org/ repo with a blog post about this if interested!

**Comment by championswimmer** [comment]
Yes sure, I'll totally do that. I am making a production-ready app with NSVue. Have figured out a lot of things on my own how to do, would contribute a few articles to the documentation for sure!

**Comment by rigor789** [comment]
I'm in the finish line with a production app as well, although I didn't use typescript, just es6 + webpack (vue-cli-template).

**Comment by championswimmer** [comment]
The double build step is kinda pain in the neck :P 
(pure ns template is blazing hot reload) 

But .vue files and scoped styles FTW, so I am on cli template too.

**Comment by championswimmer** [comment]
I would like to contribute here. Is there a roadmap, and an idea of what things need immediate attention? I will try to chip in wherever I can

I have a moderately good understanding of how `vue-loader` works. Working on my project has made me understand a lot about the `nativescript-vue` render function.

**Comment by rigor789** [comment]
I have a new nativescript-loader that I need to finish up / clean up. It utilizes the new (v15) vue-loader, and basically serves are a pre-loader. The reason for this loader is to allow future code-sharing, by assembling a .vue file by picking the correct blocks (web/native etc). I have it working in a local project, so all it really needs is some cleaning up.

The other thing that really needs some attention is vue-router

**Comment by championswimmer** [comment]
I will take up vue-router.

Essentially, a feature I personally, really really need is non-page routing nested within top level page routing. 
I'll try implementing it.

**Comment by rigor789** [comment]
I have experimented with the router with ns 4.0, which allows multiple frames and such. I had success with nesting my layout like so:

```html
<Frame>
  <router-view />
</Frame>
```

where if the route changed, the frame would navigate to the new route. This isn't perfect because we can't easily navigate back - at least not with the initial implementation, where the `addChild` of the `Frame` is overwritten to `navigate`  instead. But I think this approach is worth exploring further, because then we don't have to differentiate page routing from regular routing, and they can be mixed together.

I'm happy to figure things out with you, but we should move the conversation to a new issue / thread.

**Comment by rigor789** [comment]
Moved discussion to https://github.com/nativescript-vue/nativescript-vue/issues/214

**Comment by kilroy05** [comment]
@championswimmer do you happen to have a complete example of how you did this? I tried following your guide but hitting some snags.

**Comment by championswimmer** [comment]
A fully working app, here it goes https://github.com/championswimmer/hasgeek_mobile_nsvue

**Comment by kilroy05** [comment]
Thanks for that.
I cloned your repo and it doesn't actually work.
` Error: com.tns.NativeScriptException: Failed to find module: "nativescript-ui-sidedrawer\ui-sidedrawer.common", relative to: app/tns_modules/`

Is this related to my setup or what am I missing. 
I ran  npm install --save nativescript-ui-sidedrawer/
What am I missing?

**Comment by kilroy05** [comment]
Alright, sorted it. It's because... windows :)
Related to this : https://github.com/nativescript-vue/nativescript-vue-externals/issues/1

Upgrading "nativescript-vue-externals" to "^0.2.0" fixed it.
