### ISSUE TITLE
 Vue.navigateTo with clearHistory: true destroyed isn't caused

### ISSUE THREAD

**Issue by newapx** [nativescript-vue/nativescript-vue#216]
I use 
```
 Vue.navigateTo(Component, {
       clearHistory: true
});
```
for switching between components and the event `destroyed` isn't caused 

node_modules:
```
   "nativescript-vue": "^1.3.2-rc.4",
   "tns-core-modules": "~4.0.0",
```

**Comment by rigor789** [comment]
Hey, would you mind re-submitting this issue with more info using the new issue helper? https://new-issue.nativescript-vue.org/?repo=nativescript-vue/nativescript-vue 

Thanks!
