### ISSUE TITLE
Example for detecting gestures on layout

### ISSUE THREAD

**Issue by koder12** [nativescript-vue/nativescript-vue#218]
Can anyone give an example for detecting gestures on layout, like a swipe on AbsoluteLayout?

**Comment by 7ammer** [comment]
https://docs.nativescript.org/ui/gestures#swipe

**Comment by rigor789** [comment]
You can just add a normal event listener using `@swipe="onSwipe"`.

**Comment by koder12** [comment]
How to get arguments of the onSwipe function like swipe direction ?

**Comment by rigor789** [comment]
In your event handler `onSwipe` you have access to the event:

```js
methods: {
  onSwipe(args) {
    console.log(args.direction)
  }
}
```
