### ISSUE TITLE
when i use "@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex (...",it go error

### ISSUE THREAD

**Issue by saviourdog** [nativescript-vue/nativescript-vue#219]
PS C:\Users\cxm> @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).D
ownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
所在位置 行:1 字符: 13
+ @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex (( ...
+             ~~~~~~~~~~
表达式或语句中包含意外的标记“-NoProfile”。
所在位置 行:1 字符: 24
+ @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex (( ...
+                        ~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“-ExecutionPolicy”。
所在位置 行:1 字符: 151
+ ... nt).DownloadString('https://chocolatey.org/install.ps1'))" && SET PAT ...
+                                                                ~~
标记“&&”不是此版本中的有效语句分隔符。
所在位置 行:1 字符: 1
+ @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex (( ...
+ ~~~~~~~~~~~
无法使用展开运算符“@”以在表达式中引用变量。只能将“@powershell”作为命令的参数。要在表达式中引用变量，请使用“
$powershell”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by rigor789** [comment]
This issue is not related to nativescript-vue. Open the issue in the choco repository: https://github.com/chocolatey/choco/issues
