### ISSUE TITLE
<keep-alive> with v-if makes component disappear

### ISSUE THREAD

**Issue by SilentDepth** [nativescript-vue/nativescript-vue#220]
Demo: https://play.nativescript.org/?template=play-vue&id=liGhQ2

```xml
<Page>
  <StackLayout>
    <Button @tap="counter++">{{counter}}</Button>    
    
    <keep-alive>
      <CompButton v-if="isOdd" key="odd" label="Odd"></CompButton> 
      <CompButton v-else key="even" label="Even"></CompButton>
    </keep-alive>
  </StackLayout>
</Page>
```

`<CompButton>` is just a simple wrapper of `<Button>`. This template is almost everything of the app (except a definition of data `counter`).

The `counter` starts from `0`. When `counter <= 2` everything goes fine. But after that, no `<CompButton>` will be rendered in the view. Everything else functions well, and no `<CompButton>` is destroyed (means the `keep-alive` is working).

If replace the custom component with a bare `<Button>`, no more issues.

**Comment by msaelices** [comment]
@rigor789  PR ready for review: https://github.com/nativescript-vue/nativescript-vue/pull/291

I don't know if this PR would cause other issues, but this issue is solved with that.
