### ISSUE TITLE
Long ListView - app is not responding - Android

### ISSUE THREAD

**Issue by alexpalchikovskiy** [nativescript-vue/nativescript-vue#226]
When I scroll ListView and loading data dynamically at some moment (when list has more than 200 items) I get message "app is not responding" and app eating more than 150 Mb of RAM.

**Comment by rigor789** [comment]
> IMPORTANT! Please use the following link to create a new issue:
>
>    https://new-issue.nativescript-vue.org/?repo=nativescript-vue/nativescript-vue

---

Enable `markingMode: none` to see if it improves. I've faced a similar issue, and it was fixed when I enabled `markingMode: none`.

**Comment by alexpalchikovskiy** [comment]
@rigor789 thanks! it's work good!
