### ISSUE TITLE
Android application events are not fired

### ISSUE THREAD

**Issue by msaelices** [nativescript-vue/nativescript-vue#227]
### Version
1.3.2-rc.3

### Reproduction link
[https://github.com/msaelices/nativescript-vue-android-event-issue](https://github.com/msaelices/nativescript-vue-android-event-issue)
### Platform and OS info
Android 7.0 / NativeScript 3.4.1 / Ubuntu Xenial 

### Steps to reproduce
1. `vue init nativescript-vue/vue-cli-template myproject`

2. Select default options: no vue-router, no vuex

3. Add this code to the `src/main.js` file:

```
# after import HelloWorld from './components/HelloWorld';
const application = require('tns-core-modules/application')

application.android.on(application.AndroidApplication.activityStartedEvent, args => {
  console.log('activityStarted event called')
})
```

### What is expected?
See the `activityStarted event called` message.

### What is actually happening?
The `console.log` sentence is not reached. Even if you change the `console.log` to a `throw Error('Foo')` the error is not raised so that function is never reached. 

---
The issue is only happening with the `vue-cli-template`, which uses webpack for building the bundle. There are no issues with the `nativescript-vue-template`.

**Comment by msaelices** [comment]
More info about the issue. I can confirm that no Android event is fired, by adding the following line to the `node_modules/tns-core-modules/data/observable/observable.js`:

```
Observable.prototype.notify = function (data) {
   // add this line
   console.log('Event fired: ' + data.eventName);
   ...
```

Trying this in both the `vue-cli-template` and the `nativescript-vue-template` the following happens:

* `vue-cli-template` output:
```
...
JS: '{NSVue (Vue: 2.5.13 | NSVue: 1.3.1)} -> AppendChild(ElementNode(stacklayout), TextNode(comment))'
JS: '{NSVue (Vue: 2.5.13 | NSVue: 1.3.1)} -> AppendChild(ElementNode(page), ElementNode(stacklayout))'
JS: 'Event fired: activityStarted'
JS: 'activityStarted event called!'
JS: 'Event fired: loaded'
JS: 'Event fired: navigatingTo'
JS: 'Event fired: creatingView'
JS: 'Event fired: loaded'
JS: 'Event fired: loaded'
JS: 'Event fired: resume'
...
```
* `nativescript-vue-template` output:
```
...
JS: '{NSVue (Vue: 2.5.13 | NSVue: 1.3.1)} -> AppendChild(ElementNode(stacklayout), TextNode(comment))'
JS: '{NSVue (Vue: 2.5.13 | NSVue: 1.3.1)} -> AppendChild(ElementNode(page), ElementNode(stacklayout))'
```
No events are fired

**Comment by rigor789** [comment]
I hunted down the issue, seems like `NativeScriptVueExternals` doesn't account for nested dependencies, and doesn't mark them as external.

A workaround (which I'll include in the next version of `nativescript-vue-externals`) is to use `webpack-node-externals` like this:

```js
externals: (context, request, callback) => {
      NativeScriptVueExternals(context, request, (err, importType) => {
        if(importType && importType.startsWith('commonjs')) {
          return callback(err, importType)
        }

        require('webpack-node-externals')()(context, request, callback)
      })
},
```

This change needs a bit more thoughts, because this way all dependencies will be external, and we might not want that (in most cases no).

**Comment by msaelices** [comment]
Wow! Thanks for finding the issue. I found out the exactly same conclusion. 

I've just fixed it here: https://github.com/msaelices/nativescript-vue-android-event-issue/commit/add2f520f1be132e871c4d8a3e523fd91f39e00a

I don't know why we cannot bundle the tns-core-modules code in the app JS but it works.

**Comment by championswimmer** [comment]
@rigor789 @msaelices 
Here is a better solution that works with imports like vue-router

```typescript
    externals: [
      WebpackNodeExternals({
        // whitelist everything that does not have tns-core-modules in its name
        whitelist: [((moduleName) => (moduleName.indexOf('tns-core-modules') === -1))]
      }),
      NativeScriptVueExternals
    ],
```

**Explanation**: This uses the whitelist function to whitelist everything that 
does not have 'tns-core-modules' in its name. Because we only want to externalise tns-core-modules. Everything else can be bundled

**Comment by championswimmer** [comment]
cc @alexpalchikovskiy

**Comment by bundyo** [comment]
A better approach IMHO will be to remove the externals plugin and just set modules to resolve at specific location, thus the other folder will search for them in the same place and load only one instance of tns-core-modules. 

Something like this:
```javascript
resolve: {
    modules: [
        path.resolve(__dirname, "node_modules/tns-core-modules"),
        path.resolve(__dirname, "node_modules")
    ]
}
```

Or using alias in similar fashion.

**Comment by bundyo** [comment]
No, this would mean only where to find specific modules - the paths to them, IMHO this shouldn't affect tree shaking and bundling.

**Comment by msaelices** [comment]
Hi all! I've tried the solutions you mentioned in this repo: https://github.com/msaelices/nativescript-vue-without-vueexternals

The timeline was:

1. Created a vanilla JS app with Vuex, RadSideDrawer and RadListView, using NativeScriptVueExternals. Working well.
2. Added Android events logging. Not working. Needed to do the hack @rigor789 mentioned: https://github.com/msaelices/nativescript-vue-without-vueexternals/commit/c295b8f00d64f881b9ec0d2d59bbb7a46648076f and working now well. Attached screencast:

![screencast](https://user-images.githubusercontent.com/136875/43642878-7851c994-9729-11e8-8dd6-535bee3f22bd.gif)

3. Removed NativeScriptVueExternals and changed the modules config to have absolute routes **NOT WORKING**. See [commit](https://github.com/msaelices/nativescript-vue-without-vueexternals/commit/90c17a22559cf57fefacd782993d90a576e77419). Attached error:

![captura de pantalla de 2018-08-03 14-17-04](https://user-images.githubusercontent.com/136875/43642727-079c3edc-9729-11e8-9bad-b012f52bdec9.png)

@bundyo could you review this commit? https://github.com/msaelices/nativescript-vue-without-vueexternals/commit/90c17a22559cf57fefacd782993d90a576e77419

is there something more to do on it?

**Comment by bundyo** [comment]
I'll check it out tomorrow.

**Comment by bundyo** [comment]
Unrelated question - why do you need a template folder and all these prepare scripts? {N} app can be built directly in its folder if App_Resources are present. The setup is much simpler and you can also use tns commands directly, which you currently can't with launch.js - things like --clean for instance.

**Comment by championswimmer** [comment]
@bundyo use the `next` branch https://github.com/nativescript-vue/vue-cli-template/tree/next and those issues won't be there :)

**Comment by RosilBelli** [comment]
Sorry to ask this, but what solution should I use on my project to fix this issue meanwhile?

**Comment by rigor789** [comment]
Use the new template, upgrade guide: https://nativescript-vue.org/en/docs/getting-started/upgrade-guide/
