### ISSUE TITLE
Clicking on notifications causes app to crash - Err: 'View already has a parent'

### ISSUE THREAD

**Issue by 7ammer** [nativescript-vue/nativescript-vue#239]
### Version
1.3.1

### Reproduction link
[https://github.com/7ammer/nativescript-vue-notifications-error](https://github.com/7ammer/nativescript-vue-notifications-error)
### Platform and OS info
Android 8.1.0, Nexus 5x, macOS 10.13.4, tns-core-modules ~3.4.1, tns-android 4.0.1

### Steps to reproduce
npm install
npm run watch:android 
click on schedule button
wait 5 seconds for notification to appear
click on notification
app crashes %$£%$£@! :P

### What is expected?
On notification click, the app should resume as normal.

### What is actually happening?
On notification click, the app crashes with error:
`System.err: Error: View already has a parent. View: Page(4) Parent: Frame(3)`

---
These issues look familiar and what what led me to posting this issue here:
https://github.com/nativescript-vue/nativescript-vue/issues/59 https://github.com/nativescript-vue/nativescript-vue/issues/78

**Comment by 7ammer** [comment]
Tried on both emulator and physical device

**Comment by 7ammer** [comment]
Full error stack: https://pastebin.com/raw/eMvmi4qH

**Comment by hoatructhanhlam** [comment]
I must enable **Developer options -> Don't keep activities option** in setting of your device

**Comment by worthers** [comment]
We're experiencing this problem too on a business-level app we need to launch.

We're using in conjunction with the nativescript push plugin, and it's producing the same error message.

Tapping into the first notification received works fine. If I then receive a second notification and tap that whilst the app is still open, I get the same crash.

**Comment by rigor789** [comment]
I suggest updating to `nativescript-vue@1.4.0-alpha.0`, which has changes in the way app is resumed, this is not a stable release - so the api might change in the actual release - but it is working and stable, I have an app running in production with it.

When you update make sure you add these lines and wrap the root view in a `Frame` element

https://github.com/nativescript-vue/nativescript-vue/blob/c91fd9fb0beec94ab5fe055f0b9a3edcd2eaf9e5/samples/app/app-with-router-v2.js#L81-L85

(this is the part that will most likely change)

**Comment by gle6as** [comment]
Now router works much better, but on iOS when you use `router.back()` it navigates to view (correctly btw) but not back.

**Comment by rigor789** [comment]
This should be fixed in `2.0.0-alpha.1` closing the issue, but if it occurs again, feel free to open a new issue with more details.
