### ISSUE TITLE
[RFC] Wrap every NativeScript element in a Vue component

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue#241]
### What problem does this feature solve?
Currently, there are only a few elements that have vue components wrapping them, like ListView, TabView, TabView item etc.

The reason is that these elements needed additional code to make them work properly. 

This leads to confusion when to use `this.$refs.element.nativeView` and when to use `this.$refs.element.$el.nativeView` while trying to access the underlying NativeScript view. (first one is for non-wrapped elements, second for wrapped elements).

If we opt for wrapping every element with a minimal (functional) component, the above confusion will no longer exist.

Another benefit of doing this is that once we manage to get VueDevtools working with NativeScript-Vue, the component tree will contain everything instead of just the Vue components.

### What does the proposed API look like?
Inside element registry, we have to create a Vue component factory function that creates the wrapper, we also need to make it configurable, and move current element wrappers (required from their current location) so it all lives in a central place.

**Comment by msaelices** [comment]
- [x] ActivityIndicator
- 
- [x] Border
- [x] Button
- [x] Image

WIP

**Comment by msaelices** [comment]
@rigor789 I'm not sure I'm and approaching well but I'm working in that PR that I consider would solve this problem (Work In progress): https://github.com/nativescript-vue/nativescript-vue/pull/264

**Comment by rigor789** [comment]
@msaelices I initially thought about keeping them in the element-registry, but had no real plan since I haven't actually tried to implement it. I'll take a closer look at your PR in a bit and leave some feedback!

**Comment by msaelices** [comment]
@rigor789 Ok, I'm trying to refactor it now.

**Comment by msaelices** [comment]
@rigor789 I tried to take your approach here: https://github.com/msaelices/nativescript-vue/commit/c4b26731d048b50060766a9c4e3630925f93009d

But the news is not good, at least related to my try:

* There are warning about circular imports, which I prevented using the my first approach.
* I cannot do a progressive migration of components.
* There are a lot of errors testing the samples app.

With my first approach I tried to maintain the backward compatibility and having two ways of registering elements:

* `registerElement` which means registering an element in NS.
* `registerComponent` which register the NS but also the Vue component.

So the code of the already existing apps will behave the same, and the solution is more explicit, so we can document this two alternatives, but recommending use the `registerComponent` one.

**Comment by msaelices** [comment]
@rigor789 the thing which is hard to do is having some templates with `<native-frame></native-frame>`, but also having vue and ns-vue code as `this.documentElement = new ElementNode('document')` which both uses the same API (`registerElement`, `getViewClass`, `isKnownView`), so having the `Native${elementName}` and `${elementName}` in the same register is trickier than using separated registry for components are NS elements.

**Comment by rigor789** [comment]
The idea was to use `registerElement('ElementName', () => require('path-to-element').ElementName`, options)`

where `options` would stay the same as it is now, except allow passing a `component`. 

If no `options.component` is set, then we would create a simple component with a factory function like this

```
createComponentForElement(name, options) {
  return {
    name,
    functional: true,
    render: (h, { props, slots, listeners })  => h(`Native${name}`, { on: listeners, props }, slots.default)
  }
}
```

This is pseudo code, but I believe something like this should work. I'm not able to test this now, but will do later

**Comment by msaelices** [comment]
@rigor789 thanks, I've done the https://github.com/msaelices/nativescript-vue/commit/cdf5199ac0703754f55681d6d69e5c463b00e832 commit and everything's better now. BTW I will keep the old `registerElement` as `registerElementLegacy` and be able to migrate components one by one.

**Comment by msaelices** [comment]
@rigor789 It's not working well (see https://github.com/nativescript-vue/nativescript-vue/compare/master...msaelices:wrap-ns-elements-another-way)

If I inspect the `<Label>` tag is an NS element but not a Vue component. The Label component should be registered with the new system but it's not the case.
 
Could you check out my branch and test it? I'm testing with the `app-with-all-components.js` for debugging the label component, and others like `app-with-v-template.js` are crashing.

**Comment by msaelices** [comment]
@rigor789 There is a new PR which your approach working and some new components wrapped as `Label`, `Button` and `DatePicker`: https://github.com/nativescript-vue/nativescript-vue/pull/266

**Comment by msaelices** [comment]
@rigor789 new update. As you can see I've created the #268 PR and you can see there this code:
```
this.$refs.search.nativeView.dismissSoftInput()
```
So, as I meant before, the right syntax is still `this.$refs.refname.nativeView`, at least inside the Vue instance code.
