### ISSUE TITLE
ListView items lose height style when navigating back

### ISSUE THREAD

**Issue by microwavesafe** [nativescript-vue/nativescript-vue#244]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=2UaLdl&v=2](https://play.nativescript.org/?template=play-vue&id=2UaLdl&v=2)
### Platform and OS info
Android 8.1.0 / Nativescript 4.0 / Ubuntu 16.04

### Steps to reproduce
When you first open the app, all the Labels have a height of 60. Click on any Label to navigate to the next page, use the back button to navigate back. Now all the Labels have no height style.

### What is expected?
Label keeps the height it was assigned

### What is actually happening?
Label reduces height to minimum

**Comment by rigor789** [comment]
If you set the height of the items using `rowHeight="60"` on the `ListView` tag, then it works when navigating back. 

My guess is that when navigating back the layout recalculation doesn't account for the height you set in css - but this is not a NativeScript-Vue specific issue, so if ` rowHeight="60" ` doesn't work for you please open an issue in the https://github.com/NativeScript/NativeScript repository.

**Comment by microwavesafe** [comment]
I can confirm ```rowHeight="60"``` fixes the problem. Thanks.
