### ISSUE TITLE
error following tutorial

### ISSUE THREAD

**Issue by chovy** [nativescript-vue/nativescript-vue#246]
I installed nativescript-vue and I get an error running both `npm run watch:ios` and `npm run watch:android`

```
fullstack-mobile
> npm run watch -- --env.android


> fullstack-mobile@1.0.0 watch /Users/username/projects/chovy/fullstack/fullstack-mobile
> webpack --watch --env.tnsAction run "--env.android"

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN fullstack-mobile@ No repository field.

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
error: uncaughtException: 127 date=Sun Jun 10 2018 16:27:16 GMT-0700 (PDT), pid=71776, uid=501, gid=20, cwd=/Users/username/projects/chovy/fullstack/fullstack-mobile, execPath=/Users/username/.nvm/versions/node/v10.3.0/bin/node, version=v10.3.0, argv=[/Users/username/.nvm/versions/node/v10.3.0/bin/node, /Users/username/projects/chovy/fullstack/fullstack-mobile/node_modules/.bin/webpack, --watch, --env.tnsAction, run, --env.android], rss=200503296, heapTotal=170078208, heapUsed=116691416, external=1601018, loadavg=[2.681640625, 2.453125, 2.33056640625], uptime=621168, trace=[], stack=undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fullstack-mobile@1.0.0 watch: `webpack --watch --env.tnsAction run "--env.android"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fullstack-mobile@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2018-06-10T23_27_16_698Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fullstack-mobile@1.0.0 watch:android: `npm run watch -- --env.android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fullstack-mobile@1.0.0 watch:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2018-06-10T23_27_16_741Z-debug.log

```

I'm using node v10

**Comment by elalienx** [comment]
Have you tried to run a pure NativeScript (without Vue) project? It looks like NativeScript is not installed correctly.

**Comment by absolutehype** [comment]
I'm actually getting exactly the same exception 127 trying to run `npm run watch:android`. I went through all of the steps to setup my local environment. Running tns doctor i get

```
No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.1 version and is up to date.
```

And get this when trying to run on Android

```
error: uncaughtException: 127 date=Fri Jun 22 2018 11:41:33 GMT+0100 (BST), pid=18092, uid=501, gid=20, cwd=/Users/paul/Projects/location-tracking, execPath=/usr/local/bin/node, version=v9.3.0, argv=[/usr/local/bin/node, /Users/paul/Projects/location-tracking/node_modules/.bin/webpack, --env.tnsAction, build, --env.android], rss=121286656, heapTotal=85106688, heapUsed=74134472, external=2496163, loadavg=[5.08642578125, 4.59228515625, 4.22265625], uptime=686984, trace=[], stack=undefined
```

Any ideas?

**Comment by SGissubel** [comment]
I am also having this same issue on my Mac.  I even went in to change all permission in terminal to make sure that was not interfering. I went through ALL of the steps of setting up everything locally.  Installed every package and everything required. 
But even at the end of all of that (multiple times) --> I can't even run "tns" -- I get "command not found".
So I am now getting BOTH of these errors.

**Comment by rigor789** [comment]
@SGissubel If you get `command not found` when running `tns` that means that either you haven't installed `nativescript` or your don't have your global `node_moudles` in your path

**Comment by SGissubel** [comment]
Well I installed nativescript probably 100 times to figure it out.  So maybe the path.  What might be a solution?

**Comment by rigor789** [comment]
@SGissubel Edit your `PATH` variable to include the path to your global `node_modules/.bin`, this depends on your platform, and how nodejs has been installed, so I can't really give detailed instructions..

**Comment by SGissubel** [comment]
Well when I install... It says installed at /.npm-global/lib. 

When I run npm ls -g nativescript; 
It shows that path as /myusername/.npm-global/lib

**Comment by rigor789** [comment]
Is `/myusername/.npm-global/lib` in your `PATH` variable? In terminal try `echo $PATH`

**Comment by SGissubel** [comment]
Yeah.. it took a lot a lot a lot of refactoring and messing with my bash profile and installing and uninstalling node and everything else... But got it working. 

HOWEVER.  I still get that same error `uncaughtException: 127 ` when I try to run `npm run watch:android`. 

But it is working for `npm run watch:ios`

**Comment by rigor789** [comment]
Have you created an android emulator? The easiest would be to start Android Studio, and create it there

**Comment by SGissubel** [comment]
I will check that out. Thanks!

**Comment by hyounoo** [comment]
@rigor789 I have the same issue as @SGissubel has.
Is there any other way to create an android emulator other than installing whole android studio?

**Comment by hyounoo** [comment]
Able to create avd but got below error again.
$ avdmanager create avd -n android25 -k "system-images;android-25;google_apis;x86"
Auto-selecting single ABI x86===========] 100% Fetch remote repository...       
Do you wish to create a custom hardware profile? [no]

$ npm run watch:android

...

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN test_app@ No repository field.

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
Searching for devices...
Starting Android emulator with image android25
error: uncaughtException: 127 date=Fri Jul 13 2018 10:44:31 GMT+0900 (Korean Standard Time), pid=2620, uid=501, gid=20, cwd=/Users/drakefang/github/testApp, execPath=/usr/local/bin/node, version=v10.6.0, argv=[/usr/local/bin/node, /Users/drakefang/github/testApp/node_modules/.bin/webpack, --watch, --env.tnsAction, run, --env.android], rss=107675648, heapTotal=70815744, heapUsed=58963296, external=469801, loadavg=[1.84619140625, 1.7333984375, 1.5986328125], uptime=6768, trace=[], stack=undefined

**Comment by absolutehype** [comment]
If it helps, I managed to fix the issue after messing around with my template directory. Renaming my android image assets so they were all lowercase seemed to do the trick :scream:

**Comment by irthos** [comment]
I've got a fresh install of NS-VUE and getting the same error. Followed the rules, fixed some PATH issues for Java and Android SDK, getting this output:
```
io:isitcool2 i$ npm run watch:android

> isitcool2@2.2.1 watch:android /Users/i/Apps/isitcool/isitcool2
> npm run watch -- --env.android


> isitcool2@2.2.1 watch /Users/i/Apps/isitcool/isitcool2
> webpack --watch --env.tnsAction run "--env.android"

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN isitcool2@ No repository field.
npm WARN isitcool2@ license should be a valid SPDX license expression

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
Searching for devices...
error: uncaughtException: 127 date=Mon Jul 16 2018 21:35:36 GMT+0100 (BST), pid=2366, uid=503, gid=20, cwd=/Users/i/Apps/isitcool/isitcool2, execPath=/usr/local/bin/node, version=v9.2.0, argv=[/usr/local/bin/node, /Users/i/Apps/isitcool/isitcool2/node_modules/.bin/webpack, --watch, --env.tnsAction, run, --env.android], rss=22679552, heapTotal=156471296, heapUsed=104637792, external=593057, loadavg=[4.3388671875, 4.4833984375, 4.27685546875], uptime=2761, trace=[], stack=undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isitcool2@2.2.1 watch: `webpack --watch --env.tnsAction run "--env.android"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isitcool2@2.2.1 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i/.npm/_logs/2018-07-16T20_35_36_517Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isitcool2@2.2.1 watch:android: `npm run watch -- --env.android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isitcool2@2.2.1 watch:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i/.npm/_logs/2018-07-16T20_35_36_641Z-debug.log
io:isitcool2 i$ echo $PATH
/Users/i/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/Users/i/.rbenv/shims:/Users/i/.rbenv/shims:/Users/i/bin/IAMCli-1.2.0/bin:/opt/local/bin:/opt/local/sbin:/Applications/MAMP/bin/php/php5.3.6/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/clojure:/opt/X11/bin:/usr/local/git/bin:/Users/i/Desktop/android:Documents/sdk/platform-tools:/Development/adt-bundle/sdk/tools:/usr/local/git/bin:/usr/local/bin
```
And the following is in the generated log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch',
1 verbose cli   '--',
1 verbose cli   '--env.android' ]
2 info using npm@6.2.0
3 info using node@v9.2.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle isitcool2@2.2.1~prewatch: isitcool2@2.2.1
6 info lifecycle isitcool2@2.2.1~watch: isitcool2@2.2.1
7 verbose lifecycle isitcool2@2.2.1~watch: unsafe-perm in lifecycle true
8 verbose lifecycle isitcool2@2.2.1~watch: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/i/Apps/isitcool/isitcool2/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/i/Apps/isitcool/isitcool2/node_modules/.bin:/Users/i/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/Users/i/.rbenv/shims:/Users/i/.rbenv/shims:/Users/i/bin/IAMCli-1.2.0/bin:/opt/local/bin:/opt/local/sbin:/Applications/MAMP/bin/php/php5.3.6/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/clojure:/opt/X11/bin:/usr/local/git/bin:/Users/i/Desktop/android:Documents/sdk/platform-tools:/Development/adt-bundle/sdk/tools:/usr/local/git/bin:/usr/local/bin
9 verbose lifecycle isitcool2@2.2.1~watch: CWD: /Users/i/Apps/isitcool/isitcool2
10 silly lifecycle isitcool2@2.2.1~watch: Args: [ '-c', 'webpack --watch --env.tnsAction run "--env.android"' ]
11 silly lifecycle isitcool2@2.2.1~watch: Returned: code: 1  signal: null
12 info lifecycle isitcool2@2.2.1~watch: Failed to exec watch script
13 verbose stack Error: isitcool2@2.2.1 watch: `webpack --watch --env.tnsAction run "--env.android"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid isitcool2@2.2.1
15 verbose cwd /Users/i/Apps/isitcool/isitcool2
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch" "--" "--env.android"
18 verbose node v9.2.0
1:2018-07-16T20_35_36_517Z-debug.log
```

**Comment by irthos** [comment]
If multiple users are experiencing the same ish, should this still be a low priority?

**Comment by rigor789** [comment]
That's just a GitHub tag, it doesn't mean much in this case because the issue already got a lot of attention. What it means in most cases is that when going through the issues, the ones that are submitted with enough information using the issue helper are more likely to be replied to sooner.

**Comment by irthos** [comment]
Thanks for the clarification, Igor.. Your work porting VUE is awesome. I've
spent more time battling unknown config issues than expressing JS
application code over the last 6 months. Such is life on the edge.

**Comment by irthos** [comment]
Got it working on *macOS*. 

The first thing was deleting .android and .gradle from my Users/[yourname] folder. Then I opened Android Studio, removed all SDK api's, and reinstalled only api 26 (Android 8, Oreo). That did the trick. 

Fwiw, I pointed Genymotion to use the Studio-installed path to SDK and reinstalled Node/NPM but I doubt that had any effect since the 127 error persisted after. Hope it helps some of y'all!

**Comment by the94air** [comment]
I had the same error because I didn't have the AVD installed. After installing Android studio And creating and starting a new AVD, the NPM command worked.

**Comment by rigor789** [comment]
I'm not sure @mrnagydavid there are many possibilities... The fact that you needed `sudo` to start the emulator seems odd in the first place, since that should not be required. You may have installed the android sdk to a directory that your current user has no exec access to. 

Is this installed through Android Studio? I recommend you use it because it takes care of installing the sdks and creating the emulators.

If the command works when you have your phone connected, then it's definitely an emulator issue. Can you run the project on the emulator if the emulator is already running when you try to start it?

**Comment by mrnagydavid** [comment]
I fixed the sudo-emulator issue, by fixing the permissions for /dev/kvm. That `sudo` was a bad idea as it messed up a lot of permissions, which I fixed by hand.

I didn't install the emulator through android studio as the nativescript tutorial instructs us to install only the sdk, separately. (And I'm happy to leave out bulky things.) But I also set up Flutter, which actually asks us to install the whole android studio - and I did just that. The Android Studio noticed the already installed SDK and also noticed that I have an emulator device already. It was displayed in the AVD Manager panel.

I'm already fearful of setting this whole thing up on mac... I'm looking forward to using sidekick and vue.

When I start fiddling with nativescript next time, I'll try what you asked. Thanks!

**Comment by rigor789** [comment]
@mrnagydavid Sidekick is just a GUI for the tns cli, so you have to install everything before you can use it.

I am using a mac, and I had no trouble setting it up (had some experience setting it up on linux beforehand). What I did was install Android studio, and then installed the sdk's, created an emulator. Then I installed the tns cli and it worked right away.
