### ISSUE TITLE
$modal.close() does not cleanup view

### ISSUE THREAD

**Issue by absolutehype** [nativescript-vue/nativescript-vue#248]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=XdkvxZ](https://play.nativescript.org/?template=play-vue&id=XdkvxZ)
### Platform and OS info
iOS 11

### Steps to reproduce
Tap open modal, look in the device logs, you should see an incrementing counter every second. When you click close modal the counter should stop. Instead it continues, and opening the modal again creates another counter creating a memory leak.

### What is expected?
The modal close method should dispose of the view and fire the relevant destroy hooks. This in turn should destroy the counter.

### What is actually happening?
Closing a modal using $modal.close() does not cleanup the view and the counter continues.

---
I'm having this issue with the nativescript-barcodescanner. It continues to scan for barcodes using my scanner despite the fact that the element is destroyed.

**Comment by EddyVerbruggen** [comment]
Does that `console.log` work? If so, call `close` on the barcodescanner there.

```typescript
    this.$showModal(Modal).then(() => console.log("modal closed"));
```

**Comment by rigor789** [comment]
You need to explicitly clear intervals, there is no way for us to detect stale intervals (this is also a requirement when using web vue - and other frameworks in general)

Updated the playground to add a `beforeDestroy` hook, where you need to `clearInterval` to stop it.

https://play.nativescript.org/?template=play-vue&id=XdkvxZ&v=3

For reference here is the application / component lifecycle
![component lifecycle](https://vuejs.org/images/lifecycle.png)

**Comment by EddyVerbruggen** [comment]
I tried my suggestion on your playground and it works: "closed modal" is logged when the modal is closes if you open it like this: `this.$showModal(Modal).then(() => console.log("closed modal"));`
