### ISSUE TITLE
Failed to find module "nativescript-ui-sidedrawer"

### ISSUE THREAD

**Issue by bluelemonade** [nativescript-vue/nativescript-vue#249]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=AWZeYG&v=5](https://play.nativescript.org/?template=play-vue&id=AWZeYG&v=5)
### Platform and OS info
Windows to Android 

### Steps to reproduce
I tried to use the https://play.nativescript.org/?template=play-vue&id=AWZeYG&v=5 example in the vue-cli-template

I installed the plugin
tns plugin add nativescript-ui-sidedrawer

in the main.js I have

```
Vue.registerElement("RadSideDrawer", () => require("nativescript-ui-sidedrawer/vue") ); // .RadSideDrawer
import Vue from 'nativescript-vue';
import Home from './components/Home';
import SettingsPage from './components/SettingsPage';
import store from './store';
import './styles.scss';

```
and changed later to 
`require("nativescript-vue").registerElement("RadSideDrawer", () => require("nativescript-ui-sidedrawer").RadSideDrawer);`

### What is expected?
should show the sidedrawer menu.

### What is actually happening?
```
System.err:
System.err: Error calling module function
System.err:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-ui-sidedrawer", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:542)
System.err:     com.tns.Runtime.run(Runtime.java:534)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6517)
System.err:     android.app.ActivityThread.-wrap2(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
System.err:     android.os.Handler.dispatchMessage(Handler.java:108)
System.err:     android.os.Looper.loop(Looper.java:166)
System.err:     android.app.ActivityThread.main(ActivityThread.java:7425)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
System.err: File: "<unknown>, line: 1, column: 265
```

---
the menu works on the playground, when I use the cli-template I couldn't request the plugin.

**Comment by bluelemonade** [comment]
why I can't see this issue in the normal opend issue thread?

**Comment by rigor789** [comment]
@bluelemonade not sure what you mean?

> I installed the plugin
> tns plugin add nativescript-ui-sidedrawer

Did this command work? Because in the vue-cli template you should use `npm install --save nativescript-ui-sidedrawer`, the `tns` command will tell you that there is no project in the current directory (this is normal) 

This is documented here: https://github.com/nativescript-vue/vue-cli-template#using-nativescript-plugins

**Comment by bluelemonade** [comment]
oh sorry, I didn'r read, I will test it tomorrow morning.

**Comment by bluelemonade** [comment]
thanks, I didn't have the difference to the tns install in sight. works great.
