### ISSUE TITLE
Add platform specific CSS

### ISSUE THREAD

**Issue by elalienx** [nativescript-vue/nativescript-vue#250]
### What problem does this feature solve?
This solve the customization limitation per platform currently available.

The end user experience that I try to build is a to apply styles like fonts and colors to the components targeted to Android and iOS.

The end user experience that I try to build is to create a distinct look for Android and iOS instead of the same visual style on both platforms.

### What does the proposed API look like?
It should work similar to how pure NativeScript handle platform specific CSS code: https://docs.nativescript.org/ui/styling#platform-specific-css

So you can create custom styles like this:
style.css (common styles)
style.android.css (Android only styles, like background-color: green)
style.ios.css (Apple iPhone only styles, like background-color: cyan)

**Comment by rigor789** [comment]
> There are 4 primary ways to target styles at iOS or Android:
>
> 1.  Platform-specific stylesheets (styles.ios.css, styles.android.css)
> 2.  Platform-specific markup blocks (<ios> ... </ios>, <android> ... </android>)
> 3.  Platform-specific attributes (<Label ios:style="..." android:style="...")
> 4.  Platform-specific CSS rules (.ios .mystyle { ... }, .android .mystyle { ... }) *requires plugin

From the linked article,

1. would work as long as webpack produces these stylesheets (not out of the box)
2. This works in nativescript-vue
3. this also works in nativescript-vue
4. this also works with the plugin (or you can add `ios:class="ios" android:class="android"` to the root element)
