### ISSUE TITLE
compatibility nativescript with tns-core-modules  with tns-android-version

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-vue/nativescript-vue#251]
I would like to know which version of nativescript-view should I have as well as the tns-core-modules to be compatible with tns-android 4.1.2
I am using nativescript-view 1.3.1 with the tns-core-modules 3.4.1 and i have to say that the bug router as not possible.
Sometimes I feel that this project is really lagging behind and is not considered by the nativescript team because Angular looks more stable but I prefer and like to work with views because it is much more simple with view files.
I would like you to note the compatible versions to work well with tns-android 4.1.2 because I use nativescript-view / view-cli-template to start my project

**Comment by Fabiyo-90** [comment]
All I wish is to work with compatible version, too much bug with tns-android 4.1.3. I work with nativescript-vue 1.3.1 and tns-core-modules 3.4.1
I want to know if I work with tns-android 3.4.1

**Comment by jlooper** [comment]
closed as dupe of #269
