### ISSUE TITLE
NS components with vue

### ISSUE THREAD

**Issue by xeroxstar** [nativescript-vue/nativescript-vue#253]
Hello, i have a small problem to install a component from nativescript with vue, i have a library fresco ([https://github.com/NativeScript/nativescript-fresco](https://github.com/NativeScript/nativescript-fresco)) that i want to test but i have no success to install it, here is what i tried:

`<fresco xmlns:fresco="nativescript-fresco/nativescript-fresco-common" />`
`<fresco xmlns:fresco="nativescript-fresco" />`
`<page xmlns:fresco="nativescript-fresco/nativescript-fresco-common" ><fresco /></page>`
`<page xmlns:fresco="nativescript-fresco/nativescript-fresco-common" ><fresco:FrescoDrawee /></page>`

i also tried:

```
<fresco />
<script>
var fresco = require("nativescript-fresco/nativescript-fresco-common");
export default {
        components: {fresco}
}
</script>
```

what ever i do i get an error:
TypeError: No known component for element fresco.

What i am missing here?
Thx

**Comment by rigor789** [comment]
Please read the docs about using NativeScript plugins: https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/

You need to register the element in main.js (`Vue.registerElement('FrescoDrawee', () => require("nativescript-fresco").FrescoDrawee`)

**Comment by xeroxstar** [comment]
thx @rigor789 for a quick response, somehow i missed that...

**Comment by rigor789** [comment]
@xeroxstar no problem! It happens :)
