### ISSUE TITLE
confirm not fired in mounted or created method

### ISSUE THREAD

**Issue by bluelemonade** [nativescript-vue/nativescript-vue#254]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=izHUgC&v=3](https://play.nativescript.org/?template=play-vue&id=izHUgC&v=3)
### Platform and OS info
playground and android version

### Steps to reproduce
please comment the timeout in and the confirm dialog appears after one second

```
created() {
    console.log('created');
     // setTimeout(() => {
      confirm({
        title: "Your title",
        message: "Your message",
        okButtonText: "Your OK button text",
        cancelButtonText: "Your Cancel text"
      }).then(result => {
        console.log(result);
      });
   // }, 1000);
  },

```

### What is expected?
confirm dialog should appear on created method

### What is actually happening?
nothing!

---
why is it working only with the timeout delay.

**Comment by rigor789** [comment]
The `created` hook is called as soon as the Vue instance is created, at this point the application has not been started yet (`.$start()` is called after the `created` hook fires). You may try it in the `mounted` hook, which may still not work - I can't remember when exactly are the dialogs initialized in NativeScript.

**Comment by bluelemonade** [comment]
mounted does not work either. I can use the timeout...

**Comment by rigor789** [comment]
Alright, so the app is still not fully started / dialogs initialized when the `mount` is fired, if you don't want to use a `setTimeout` you can attach a `loaded` event listener to the page / root element of your app, and call the dialog from the handler - that should ensure that it loads.

**Comment by msaelices** [comment]
I've tested the `launchEvent` and only works if there is a `setTimeout` (even with 0 milliseconds delay).

So, the following code shows the `LAUNCHED EVENT` log but not shows the alert dialog until the `setTimeout` lines are uncommented:
 
```
import * as app from 'tns-core-modules/application'

app.on(app.launchEvent, (args) => {
  console.log('LAUNCHED EVENT')

  // setTimeout(() => {
    alert('Launched')
  // }, 0)
})
```

**Comment by msaelices** [comment]
More tests done. It seems it does not depends on the time we launch the dialog but the fact of the dialog is launched on a task which does not block the main thread. So, the following code makes the app finish launching a few seconds later, but it does not show the dialog: 
```
app.on(app.launchEvent, (args) => {
  console.log('LAUNCHED EVENT')

  console.log('START EXPENSIVE TASK')
  let isEven;
  for (let i = 0; i < 10000000000; i++) {
    isEven = i % 2;
  }
  console.log('END EXPENSIVE TASK')

  alert('Launched')
})
```

**Comment by rigor789** [comment]
`app.launchEvent` is used to start the application, so I don't think it is reliable to use that for firing an `alert`

https://github.com/nativescript-vue/nativescript-vue/blob/49d8373d1496d1f6e86bad1867d87ffabb6d8394/platform/nativescript/runtime/index.js#L62-L70

**Comment by msaelices** [comment]
@rigor789 Ahh! got it, so you mean something like that:
```
const Vue = require('./nativescript-vue')
const app = require('tns-core-modules/application')

Vue.config.silent = false

new Vue({
  template: `
    <Frame>
      <Page @loaded="onLoaded">
        ...
      </Page>
    </Frame>
  `,
  methods: {
    onLoaded () {
      alert('Launched')
    },
  }
}).$start()
```

**Comment by rigor789** [comment]
@msaelices yes that's that I meant, hopefully that works?! 👍

**Comment by msaelices** [comment]
@rigor789 yes it works! I would like to document that on the docs, but I'm having troubles building it.

**Comment by bluelemonade** [comment]
hi, interested thing, is there a documention on these onload methods?

**Comment by bluelemonade** [comment]
ok, but there's nothing about events in the https://nativescript-vue.org/en/docs/introduction/
where can I find infomation about the lifecycle event like onResume?

**Comment by rigor789** [comment]
Check https://docs.nativescript.org/core-concepts/application-lifecycle for the lifecycle events

as well las https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram for the Vue lifecycle.

How they work together is not documented yet - I would like to have a diagram in the docs at some point!
