### ISSUE TITLE
Error: A Frame must be used to navigate to a Page.

### ISSUE THREAD

**Issue by h-p-r** [nativescript-vue/nativescript-vue#255]
src : https://github.com/h-p-r/zList

template : https://github.com/nativescript-vue/vue-cli-template

when using gradient in home.vue i am getting error.

```
System.err: Error: A Frame must be used to navigate to a Page.
System.err: File: "file:///data/data/org.zlist.app/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.zlist.app/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.zlist.app/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
```

**Comment by xyh67** [comment]
I have the same issue

**Comment by championswimmer** [comment]
Are you using tns-core-modules 4.x or 3.x ?

**Comment by xyh67** [comment]
I'm useing tns-core-modules on 4.1.0.

**Comment by uniquejava** [comment]
Hello, I met the same issue.

I created a hello world nativescript-vue project following the official document and it works, i can click the counter button and got the surprise.

and then i want to use the `application` module to implement lifecycle events.
in main.js, I added one line of code (just imported the module), and then after `npm run clean` and `npm run watch:ios`

The console throws the following error.

> file:///app/app.js:1:150143: JS ERROR Error: A Frame must be used to navigate to a Page.

Here is the main.js(one line of code change)

```js
import Vue from "nativescript-vue";
import * as application from "tns-core-modules/application"; // this is newly added line
import router from "./router";

import store from "./store";

import "./styles.scss";

// Uncomment the following to see NativeScript-Vue output logs
//Vue.config.silent = false;

new Vue({
  router,

  store,
  mounted() {
    console.log("root component mounted.");
  }
}).$start();

```

If searched other posts. and found maybe it's the default `tns-core-modules 3.x` not the latest, so I upgraded that single dependency. Still that same error.

Here is how i created this project.
```sh
vue init nativescript-vue/vue-cli-template hello
```

Here is some of my system info.
```
vue-cli 3.0.0-rc.5
node v8.11.3
npm  5.6.0
macOS 10.13.5
xcode 9.1(9B55)
```

**Comment by uniquejava** [comment]
Oh. I am using iphone 7 plus with ios 10. Not upgraded to ios11.

**Comment by spogulis** [comment]
Try to get Gradient or other plugins working, need to register it this way:
`Vue.registerElement('Gradient', () => require('nativescript-gradient').Gradient);`

- where `Gradient` is  the package name. Works for me.

**Comment by hgouveia** [comment]
i have same issue, after upgrade to nativescript-vue to 2.0.0-alpha2, using https://github.com/nativescript-vue/vue-cli-template , not change

Steps:
```
npm install -g @vue/cli @vue/cli-init
vue init nativescript-vue/vue-cli-template tns-vue-alpha
cd tns-vue-alpha
npm install nativescript-vue@2.0.0-alpha.2 --save
npm install
npm run watch:android
```

**Comment by uniquejava** [comment]
@hgouveia Hi. later I found that it's `vue-router`'s problem. You can try remove `vue-router` and see if it works.
