### ISSUE TITLE
Bug very serious with Navigation Screem!

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-vue/nativescript-vue#269]
I use "NativeScript@4.1" with "nativescript-view@1.3.1" using the template designed with view / cli, "view-router@3.0.1", tns-core-modules@3.4.1 ".
When I use my router going from the "root page" to the third page with the method "$ route.push ('/ path')" everything goes well; while I'm on the second page and I press the return button of my android so I go back to the "root page" but when I'm on the third page and I press the back button of my android so to go back to the second page, I have an error

TypeError: cannot read property "__ob__" of undefined

this error comes back to all "tns-android" versions including "tns-android@4.0.0", android@4.0.1 ", android@4.1.1", android@4.1.2 "and android@4.1.3 "

Bug very serious!

**Comment by jlooper** [comment]
For now the best workaround is to not use the vue router. Please try manual routing as described in the docs.

**Comment by rigor789** [comment]
> Currently, integration with Vue Router is **experimental**.

We are working on a better routing setup, but it will take some time before it is complete.

As for your issue, I don't know a solution and I would rather focus on making the new setup work without issues.

**Comment by Fabiyo-90** [comment]
I will try to use the manual routing and I pray that it will work because I develop a project that will soon be in production

Many thanks to you Igor because it's a great project and much easier to handle than NativeScript-Angular (many of my friends dropped to React-Native)

**Comment by Fabiyo-90** [comment]
I will try to use the manual routing and I pray that it will work because I develop a project that will soon be in production

Many thanks to you Igor because it's a great project and much easier to handle than NativeScript-Angular

**Comment by Fabiyo-90** [comment]
import Vue from 'nativescript-vue';

Vue.registerElement('RadSideDrawer', () => require('nativescript-ui-sidedrawer').RadSideDrawer);
Vue.registerElement('CardView', () => require('nativescript-cardview').CardView);

const AuthPage = require('./pages/Auth');

import './styles.scss';

// Uncommment the following to see NativeScript-Vue output logs
//Vue.config.silent = false;

new Vue({
    render: h => h(AuthPage)

}).$start();



it does not work and there are no errors reported and no bug. Show what's wrong in this code

**Comment by jlooper** [comment]
This is a different issue, should be handled in Slack, but uncomment //Vue.config.silent = false; to see more logging

**Comment by Fabiyo-90** [comment]
I tried as you told me using the Manuel Routing but unfortunately I always have the same error, I tried to change versions of NativeScript to earlier versions and "tns-android" unfortunately I still have the same error, I have to present a prototype application this Thursday and I see myself having to change the alternative to "Vue-Native" which seems to be stable, and with this I lost almost two weeks well without understanding the mistake or finding an alternative solution

**Comment by championswimmer** [comment]
I have a hacky workaround this problem

First make sure on exit event you **really really** exit the app

```typescript
import * as application from 'tns-core-modules/application'
import {exit} from 'nativescript-exit'

/*
 * Force an exit, instead of trying to remount
 * FIXME: On upgrade to nativescript-vue 2.x this wont be necessary
 */
application.on(application.exitEvent, (args: ApplicationEventData) => {
  exit()
})
```

Next, to make back button work as page routing 

```typescript
/*
 * Go back if in a nested route. If top level route, just do what android does
 */
if (application.android) {
  application.android.on(
    AndroidApplication.activityBackPressedEvent,
    (data: AndroidActivityBackPressedEventData) => {
      if (router.currentRoute.path.split('/').length > 2) {
        router.back()
        data.cancel = true
      }
    }
  )
}
```
