### ISSUE TITLE
startActivity is undefined

### ISSUE THREAD

**Issue by mbuehrig** [nativescript-vue/nativescript-vue#270]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=m1qdiD](https://play.nativescript.org/?template=play-vue&id=m1qdiD)
### Platform and OS info
Android 7.0 / MacOSX

### Steps to reproduce
Well run it in the Playground and you see how it actually works, the StatusBar and NavigationBar are not visible anymore. But it doesn't work in my own Vue project, when I run it with npm run debug:android on an with USB connected device.

### What is expected?
StatusBar and NavigationBar shouldn't be visible by default

### What is actually happening?
I get an error when I build, that getDecorView() doesn't work because startActivity is undefined

**Comment by msaelices** [comment]
@mbuehrig I confirm it's working on the playground and also if you download the zip and deploy on your local machins. 

It's a weird issue. Have you tested also the `foregroundActivity` attribute?

**Comment by mbuehrig** [comment]
Yeah tried that as well, no solution it is as undefined as startActivity is.

**Comment by msaelices** [comment]
I tried also add your app to the NS-vue samples app but it's working too. I think is a weird issue related to webpack and `nativescript-vue-externals`, which is bundling the AndroidApplication code (which is in `tns-core-modules`) to the `app.android.js` file.

I will try to investigate further.

**Comment by msaelices** [comment]
@mbuehrig I can confirm bundling the `AndroidApplication` code is the reason of the issue. You can fix it by changing the commonjs sentences to tell webpack they are externals by trying with this `main.js` file:

```
import * as app from 'tns-core-modules/application'
import * as platform from 'tns-core-modules/platform'

const Vue = require('nativescript-vue');

new Vue({
  template: `
  <Page
    class="page page__start"
    actionBarHidden="true"
    backgroundSpanUnderStatusBar="true"
    @loaded="pageLoaded"
  >
  <StackLayout>
    <FlexboxLayout flexDirection="column">
      <Label text="hello world" />
    </FlexboxLayout>
  </StackLayout>
  </Page>
  `,
  methods: {
    pageLoaded: (args) => {
      const View = android.view.View;

      if (app.android && platform.device.sdkVersion >= '21') {
        const window = app.android.startActivity.getWindow();
        const decorView = window.getDecorView();
        decorView.setSystemUiVisibility(
          View.SYSTEM_UI_FLAG_LAYOUT_STABLE
          | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
          | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
          | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
          | View.SYSTEM_UI_FLAG_FULLSCREEN
          | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
      }
    }
  },

}).$start({
  getRootView (vm) {
    return vm.$el.nativeView; // frame
  },
})
```

**Comment by mbuehrig** [comment]
I will test it tomorrow, thanks for the help anyway.

**Comment by k-pawan** [comment]
Facing similar issue in an application i am trying to build with nativescript vue, 
tried following as well.
 pageLoaded(args){
                const applicationModule = require('tns-core-modules/application');
                console.log("start activity  ",applicationModule.android.startActivity); //logs undefined
                console.log("forground activity",applicationModule.android.foregroundActivity); //logs undefined
            }

**Comment by underdoeg** [comment]
Same here:
```
<template>
	<Page class="page" @loaded="pageLoaded">
		<StackLayout backgroundColor="#3c495e">
			<Label text="first" height="70" backgroundColor="#43b883"/>
			<Label text="second" height="70" backgroundColor="#289062"/>
			<Label text="third" height="70" backgroundColor="#1c6b48"/>
		</StackLayout>
	</Page>
</template>

<script>

	export default {
		name: "Home",

		mounted(){

		},

		methods: {
			pageLoaded(args){
				const app = require('application');
				const platform = require('platform');
				const View = android.view.View;

				console.log(app.android.startActivity);
			}
		}
	}
</script>

```

startActivity is undefined

**Comment by rigor789** [comment]
This issue should no longer happen in the latest cli template, see the upgrade guide for more details https://nativescript-vue.org/en/docs/getting-started/upgrade-guide/
