### ISSUE TITLE
No loaded / unloaded event when app resumed / suspended in iOS

### ISSUE THREAD

**Issue by microwavesafe** [nativescript-vue/nativescript-vue#271]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=pQ0EeU](https://play.nativescript.org/?template=play-vue&id=pQ0EeU)
### Platform and OS info
iOS 11 / NativeScript 4.0 / Ubuntu 16.04

### Steps to reproduce
The playground I've linked to above works in the preview app, but I do not get any loaded / unloaded events when the app is suspended or resumed when building with Vue cli template.

### What is expected?
loaded method is called when app is resumed, unloaded method is called when the app is suspended.

### What is actually happening?
These methods are not called on suspend or resume. But I do get suspend / resume events if I hook into ```application.on(application.suspend, () => {})```
directly

**Comment by microwavesafe** [comment]
I've done some further tests. I get the same results for NS4.0.0 on the iPhone simulator. I have also tried NS 4.1.2 (tns-ios@4.1.1) and I get the same results. I'm wondering if this is expected behaviour and actually an issue of NS not NS Vue.

**Comment by microwavesafe** [comment]
Thanks for checking this out. This may be a stupid question, but how do I update this package? I've run
```
npm install https://github.com/nativescript-vue
npm run clean
npm run watch:ios
```
which updated the package to 2.0.0-alpha. But now the project doesn't build or run giving me an error
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'nativescript-vue' in '/Users/dev/Documents/Test/unload_test/src'
```
Are there any instructions for performing an upgrade to either of the alpha releases?

**Comment by microwavesafe** [comment]
OK I managed to get it running, installing from Github didn't install the dist folder, so I used
```
npm install nativescript-vue@next
```
Which installed the right files to get it to build, but now it won't run.
```
file:///app/app.js:1:131509: JS ERROR TypeError: Qi.run is not a function. (In 'Qi.run()', 'Qi.run' is undefined)
```

**Comment by rigor789** [comment]
The default install is `1.3.1`, to install the lastest alpha use `npm i --save nativescript-vue@next`

**Comment by rigor789** [comment]
@microwavesafe make sure `tns-core-modules` is updated in both `package.json` and `template/package.json`, and that you clean, and re-build the project. The error you are seeing is due to an outdated version of `tns-core-modules` which doesn't have the `run` method...

**Comment by microwavesafe** [comment]
Ah that was it, I had upgraded tns-core-modules in my project directory, but didn't know about the additional version in the template directory.
```
npm i --save nativescript-vue@next
npm i --save tns-core-modules@latest
cd template
npm i --save tns-core-modules@latest
cd ..
npm run clean
npm run watch:ios
```
It now builds and runs and I can confirm that I get correct loaded / unloaded signals when the app is suspended.
@rigor789 @msaelices thank you both for your help.
