### ISSUE TITLE
Empty label on ios

### ISSUE THREAD

**Issue by mathieutu** [nativescript-vue/nativescript-vue#272]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=3SaUXi&v=3](https://play.nativescript.org/?template=play-vue&id=3SaUXi&v=3)
### Platform and OS info
Nativescript from vue-cli-template, Ios in emulator.

### Steps to reproduce
HI, 
Inside a ListView, I have a another component which contains a Label.
```js
<Label :text="user.name" class="list-group-item-heading" :textWrap="false" style="height: 100%"/>
```

It works perfectly on android but not on ios. 
on Ios the label is empty.

BUT if I _convert_ the name to a string (which is already) directly in the template, it works!

```js
<Label :text="String(user.name)" />
<Label :text="user.name + ''" />
```
If I do the same in a computed property it doesn't work, it has to be in the template.

I precise that in the chrome debugger I can see that the xml is ok, the name appear well in sources, but not in the application.

### What is expected?
Label should not be empty on ios

### What is actually happening?
Label is empty on ios

---
I'm not sure that the reproduction link actually reproduce the problem as I don't have an iPhone to test it, the problem occur in the emulator.

**Comment by mathieutu** [comment]
Ok, I think I've understood where is the problem.
The items passed to the listView are an array of User objects:

```js 
export default class User {
    constructor(user) {
        this.name = user.profile.real_name_normalized.toUpperCase();
    }
};
```

And the item passed throw the template is not of type User anymore. Maybe something happen at this time ?

**Comment by rigor789** [comment]
Please try `2.0.0-alpha.1` as we changed how ListViews are rendered. It should solve the issue, but please let me know, I'll keep the issue open until then.

**Comment by mathieutu** [comment]
ok, I'm not on it right now, but I'll try and let you know.
Thank's for all your amazing work @rigor789! 😉

**Comment by msaelices** [comment]
@mathieutu I've added a test case and confirmed that it's working on the `2.0.0-alpha.1` version

CC/ @rigor789

**Comment by msaelices** [comment]
Closing this issue as it works on the `2.0.0-alpha.1` version. Please re-open it if I missed something.

**Comment by msaelices** [comment]
@mathieutu, please reopen if I missed something.
