### ISSUE TITLE
Template freeze with several v-if.

### ISSUE THREAD

**Issue by mathieutu** [nativescript-vue/nativescript-vue#273]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=tYnwgA&v=16](https://play.nativescript.org/?template=play-vue&id=tYnwgA&v=16)
### Platform and OS info
All

### Steps to reproduce
When several v-if instead of v-if/v-else, the template doesn't update anymore.
See https://play.nativescript.org/?template=play-vue&id=tYnwgA&v=16 for a not working example and https://play.nativescript.org/?template=play-vue&id=tYnwgA&v=17 for a working one.

Thanks.

### What is expected?
No problem with several v-if

### What is actually happening?
Template freeze

**Comment by msaelices** [comment]
This is a duplicated issue, which is solved on the master branch.

**Comment by mathieutu** [comment]
Oh yeah, found it! 🤦‍♀️
https://github.com/nativescript-vue/nativescript-vue/issues/127
