### ISSUE TITLE
Debugging Nativescript-Vue

### ISSUE THREAD

**Issue by birthevdb** [nativescript-vue/nativescript-vue#280]
### What problem does this feature solve?
I'm trying to debug my NativeScript-Vue app in Chrome by running npm run debug, opening the chrome devtools link that was provided, and hitting the 'Sources' Tab. However, all I can see is a bundled and minified app.js file. 
Is there a possibility to view the original Vue component files? It seems that there are no sourcemaps? 
Is there another way to debug my Nativescript-Vue app?

I used this command to set up my project: > vue init nativescript-vue/vue-cli-template <project-name>

### What does the proposed API look like?
An easy to use and straightforward debug feature.

**Comment by msaelices** [comment]
You can easily comment the following lines in the `webpack.config.js` file:

```
      new webpack.optimize.UglifyJsPlugin({
        compress: {warnings: false},
        output: {comments: false},
      }),
```

BTW, I think you are right and the `npm run debug` command should disable code uglifying by default.

**Comment by msaelices** [comment]
PR ready for review: https://github.com/nativescript-vue/vue-cli-template/pull/63
