### ISSUE TITLE
Radlistview scrollOffset is always 0

### ISSUE THREAD

**Issue by asqwrd** [nativescript-vue/nativescript-vue#284]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=i28vZu&v=12](https://play.nativescript.org/?template=play-vue&id=i28vZu&v=12)
### Platform and OS info
Android 8.1

### Steps to reproduce
In the playground https://play.nativescript.org/?template=play-vue&id=i28vZu&v=12 i set a scrolled event on the radlist component and console log the offset.  Looking at the output u will notice that it is always 0

### What is expected?
scrollOffset should increase or decrease depending on direction of scrolling

### What is actually happening?
it is always 0 no matter how much you scroll

**Comment by rigor789** [comment]
Has been solved on Slack:

> @asqwrd [4 days ago]
for those who need the answer it was zero because I scrollDirection has to uppercase ie scrollDirection="Vertical" not scrollDirection="vertical"
