### ISSUE TITLE
RadListView not working with 2.0.0-alpha.1

### ISSUE THREAD

**Issue by odai-alali** [nativescript-vue/nativescript-vue#294]
### Version
2.0.0-alpha.1

### Reproduction link
[https://github.com/odai-alali/radlistview-test](https://github.com/odai-alali/radlistview-test)
### Platform and OS info
Android 7.0 / NativeScript 4.1 / Windows 10

### Steps to reproduce
run the application

### What is expected?
RadListView to be rendered

### What is actually happening?
render is wrong
![screen](https://user-images.githubusercontent.com/5602515/43644335-ad59cede-972e-11e8-9f6d-e0b2c7023088.png)

**Comment by rigor789** [comment]
We have changed the way elements are registerd in 2.0. Every element is now wrapped in a Functional Vue component. The RadListView implementation needs a bit of tweaking, specifically I think changing the registerElement lines to this should make it work as before:

```js
Vue.registerElement('RadListView', () =>require('nativescript-ui-listview').RadListView, {
  component: { /* insert RadListView component code here instead */ }
})

**Comment by asqwrd** [comment]
i am having the same issue was anyone able to figure it out.  I tried wrapping it but i dont think i did it right @rigor789  can you post an example of how it should look

**Comment by asqwrd** [comment]
@odai-alali were you able to get the Radlistview to work

**Comment by msaelices** [comment]
@asqwrd here there is a working code: https://github.com/msaelices/nativescript-vue-without-vueexternals/blob/master/src/views/Home.vue

**Comment by asqwrd** [comment]
@msaelices what u have isnt working for me i get [object object] instead looks like you are just importing like normal which has never worked.  I had to make a component file based off this https://play.nativescript.org/?template=play-vue&id=i28vZu&v=4 but now this no longer works anymore as of 2.0

**Comment by odai-alali** [comment]
@asqwrd I tried to change the implementation as @rigor789 suggested but I am still getting the same result and I wasn't able to build the example that @msaelices provided.

**Comment by odai-alali** [comment]
the following three lines always return `null`.
```js
this.$templates.getKeyedTemplate('header').createView()
this.$templates.getKeyedTemplate('footer').createView()
this.$templates.getKeyedTemplate('default').createView()
```

**Comment by odai-alali** [comment]
@rigor789 How can I create a view instance for header and footer from a KeyedTemplate
https://github.com/odai-alali/radlistview-test/blob/master/src/RadListView.js#L77

createView is always returning **null**

**Comment by odai-alali** [comment]
The example that @msaelices provided seems to work only when items attribute is an array of literal strings. The same with the example in my repo. However, the condition (if="$odd") is ignored to. Could it be that there is something wrong in **patchElement** function?

**Comment by asqwrd** [comment]
is this in the repo u linked?

**Comment by odai-alali** [comment]
yes, this is working now https://github.com/odai-alali/radlistview-test
but like I think there should be a better solution

![screen](https://user-images.githubusercontent.com/5602515/43717100-c1c167a6-9986-11e8-80ea-8e7338eb2b5a.png)

**Comment by asqwrd** [comment]
@odai-alali doesnt work for me i get this when trying to load
> System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err:
System.err: TypeError: Cannot read property 'name' of null
System.err: File: "<unknown>, line: 18, column: 935
System.err:
System.err: StackTrace:
System.err:     Frame: function:'fn', file:'', line: 18, column: 936

**Comment by odai-alali** [comment]
did you tried the same code in the repo or used the RadListView in your own component?

**Comment by asqwrd** [comment]
I used your code in the RadListView.js it seems to throw the error at
patchElement

**Comment by odai-alali** [comment]
I did a workaround which was creating a view without an empty context through patchElement. That means, when your component is mounted the **item** will be empty. and the header and footer will not be able to be able to use somthing like `v-if="isVisible"` because they do not have access to the component data.

In case you are displaying `item.name` in your code. you have to check on every use if item is defined `v-if="item"` like [here](https://github.com/odai-alali/radlistview-test/blob/master/src/components/HelloWorld.vue#L20)

I am not sure how to get the context of the item inside `itemViewLoader`. the items at this place are not yet known. the same thing for header and footer.

**Comment by asqwrd** [comment]
@odai-alali ok that got rid of the error but it looks like the listview doesnt render anything I guess Ill have to wait until this is ironed out

**Comment by rigor789** [comment]
@odai-alali @msaelices is working on official implementation for vue which will land in the RadListView...

As for now, the way you did it with `patchTemplate` is correct, just a few suggestions:

 - for static templates such as header/footer try passing `this.$parent` as the second argument - this will set the render context to the parent (this is where you defined the `<v-template>`'s) and allow you to use data like normal. **note:** haven't tested this, but I think that should work just fine
 - remove the `case 'itemview':`  branch, since item loading is done here: https://github.com/odai-alali/radlistview-test/blob/master/src/RadListView.js#L104 - this should avoid the `v-if="item"` checks. The reason why createView returns null is to avoid some other issues we had in prior releases, where there would be cryptic errors all over the place in some cases (before 2.0 we passed in a DeepProxy as the context, so any data in your template like `a.b.foo.bar` would "work" and not error out while creating the initial view, but in some cases passing a Proxy caused issues)

**Comment by odai-alali** [comment]
@rigor789 thank you for your time and suggestions but unfortunately: 
- the data still not reactive in header and footer template
- removing `itemView` case broke the rendering and items are rendered like before `[object Object]`

I hope to see RadListView in the core soon. I wanna see the solution 😭

**Comment by odai-alali** [comment]
works in v2.0
https://github.com/msaelices/ns-ui-vue-demo/blob/master/app/components/ItemList.vue
