### ISSUE TITLE
Is there a way to animate splash screen on nativescript-vue?

### ISSUE THREAD

**Issue by fixer112** [nativescript-vue/nativescript-vue#296]
The title explains all, is there a way to achieve this?

**Comment by t3hmrman** [comment]
Hi @fixer112 could you be more clear about what you mean by animating the splash screen?

After generating splash screens with [`tns resources generate splashes`](https://docs.nativescript.org/tooling/docs-cli/project/configuration/resources/resources-generate-splashes), you have at least a few options as I can see:

- Create your own screen that *is* the splash screen -- use it to show whatever image/video/animation you want

- Use a GIF that only plays once as your splash screen image, but this ONLY works on android ([SO post about android](https://stackoverflow.com/questions/39871405/can-i-add-gif-format-image-as-a-splash-screen), [SO post about iOS](https://stackoverflow.com/questions/19122074/can-ios-launch-images-be-animated-gifs))

**Comment by rigor789** [comment]
See https://market.nativescript.org/plugins/nativescript-splashscreen for a possible solution.
