### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue#297]
In order to release 2.0 there are few things that we need to do:

* [x] Create a migration guide in the docs
* [x] Create a snapshot of the current docs in the v1.3.1 branch
* [x] Document new elements such as `<Frame>`
* [x] Update documentation about manual routing to include information about using multiple frames
* [x] Clean up `nativescript-vue-devtools` and bump version to `1.0`
* [x] Document standalone VueDevtools usage with NativeScript-Vue
* [ ] @rigor789 - PR pro-ui plugins with a Vue implementation
  * [x] - RadSideDrawer
  * [x] - RadListView
  * [ ] - RadDataForm
  * [ ] - RadGauges
  * [ ] - RadAutocomplete
  * [ ] - RadCharts
  * [ ] - RadCalendar

### can wait:
* [ ] @rigor789 Clean up `nativescript-vue-loader` (configuration for multiple targets in the future)
* [ ] Finish Vue CLI 3.x plugin and deprecate the vue-cli-template
* [ ] Finish VueRouter integration (WIP)

**Comment by Fabiyo-90** [comment]
I need a tutorial or a more explicit document about using nativescript-ui-pro elements,
I tried everything and I'm stuck serious

http://docs.telerik.com/devtools/nativescript-ui/Controls/Vue/Calendar/getting-started


nothing is clear in this document

**Comment by jlooper** [comment]
Are the VueDevTools going to be released with this 2.0 release? I think we have to wait on the core team.

**Comment by rigor789** [comment]
@jlooper as long as the support lands in VueDevtools 5.0 (which will have a new beta soon afaik, so it may land there) https://github.com/vuejs/vue-devtools/pull/732#issuecomment-417894368

**Comment by Akryum** [comment]
I'm not sure about the change from `src` to `app`, it's not in line with the vue-cli 3 defaults and might cause issues for vue-cli-plugin-nativescript.

**Comment by rigor789** [comment]
@Akryum I believe we can change it back to `src` (will need to be checked), but the `vue-cli-plugin-nativescript` will most likely have to wait, because the webpack setup for nativescript is a lot different than the one provided by vue-cli, and the plugin would have to undo most rules and then add the ones we need.

The nativescript cli needs a `webpack.config.js` in the root of the project to function, and I think we could technically make it just `module.exports = require('@vue/cli-service/webpack.config.js')` if the generated config is compatible.

One of the ideas right now is to create a nativescript-cli template, and then build the vue-cli-plugin on top of it to make maintenance easier.
