### ISSUE TITLE
I have a very specific imagepicker question/bug, showing the image works in the IOS emulator, but not on the actual phone, even though it has a path, see screenshots below

### ISSUE THREAD

**Issue by gjonakin** [nativescript-vue/nativescript-vue#299]
here's the action:

getPicture (contexted) {
        console.log('entering getpic');
        const fs = require("tns-core-modules/file-system");
        const imageSourceModule = require("tns-core-modules/image-source");
    //import * as imageSourceModule from "image-source";
        var imagepicker = require("nativescript-imagepicker");
        
        var context = imagepicker.create({ mode: "multiple" });
                
        context.authorize().then(() => {
            return context.present();
        }).then((selection) => {
            selection.forEach(function(selected) {
            const ios = selected.ios;
            if (ios && ios.mediaType === PHAssetMediaType.Image) {
                const opt = PHImageRequestOptions.new();
                opt.version = PHImageRequestOptionsVersion.Current;
                PHImageManager.defaultManager().requestImageDataForAssetOptionsResultHandler(
                    ios, opt, (imageData, dataUTI, orientation, info) => {
                        console.log(info.objectForKey("PHImageFileURLKey").toString());
                        var fileUri = info.objectForKey("PHImageFileURLKey").toString();
                        contexted.commit("uploadPic",  fileUri );
                    });
                    
            } 
            });
        });
        
    },

Here's the mutation to add pics to the vuex array:
uploadPic (state, payload) {
        console.log('adding pic = ', payload);
        console.log('pre-value of image',state.imagePicked);
        //state.imagePicked = payload;
        state.imagePicked.push(payload);
        console.log('value of image',state.imagePicked);
    },

Here's a pic of it working correctly in the IOS emulator:
<img width="486" alt="screen shot 2018-08-06 at 5 12 20 pm" src="https://user-images.githubusercontent.com/29108907/43744775-4bc5ad58-99a1-11e8-8d21-39751574f501.png">

Here's what it looks like on the phone itself, doesn't display even though the file path is available:

<img width="369" alt="screen shot 2018-08-06 at 5 16 37 pm" src="https://user-images.githubusercontent.com/29108907/43744793-5dd00f84-99a1-11e8-84ad-9ea2c44adf49.png">

Here's the code for calling the image:
<Image class="imageCss" :src="item" stretch="aspectFill"></Image>

Here's the CSS for displaying that element:
.imageCss {
        border-radius: 70;
        width: 75;
        height: 75;
    }

**Comment by rigor789** [comment]
If you are still having issues, please ask on the NativeScript Community Slack (specificially the #vue channel) with more details.
