### ISSUE TITLE
Linear-gradient TypeError: imageUri.match is not a function

### ISSUE THREAD

**Issue by mennolp098** [nativescript-vue/nativescript-vue#304]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-ng&id=uMfuhG](https://play.nativescript.org/?template=play-ng&id=uMfuhG)
[https://github.com/mennolp098/NS-Vue-GradientTest](https://github.com/mennolp098/NS-Vue-GradientTest)
### Platform and OS info
Android API 24 V7.0 / Nativescript 4.1.2 / Windows 10

### Steps to reproduce
1. Create a layout: <StackLayout class="gradient"></StackLayout>
2. Add css styling for gradient: .gradient { background: linear-gradient(to right, red, blue, yellow);  }
3. Run app
4. Get runtime error: TypeError: imageUri.match is not a function

### What is expected?
A layout with a gradient from left to right with the colors red, blue and yellow.

### What is actually happening?
A runtime error: TypeError: imageUri.match is not a function

---
Tried it on a new Nativescript JS and it worked.

**Comment by hoatructhanhlam** [comment]
Are you sure tns-code-modules >= 4.0.0 in package.json & template/package.json?

**Comment by mennolp098** [comment]
@hoatructhanhlam Hi you are right, bundyo on the slack community helped me out yesterday. The issue was that template/package.json didn't get updated automatically because of the CLI template I used
