### ISSUE TITLE
Nested ListView with v-for component gives errors. 

### ISSUE THREAD

**Issue by joannesalfa** [nativescript-vue/nativescript-vue#309]
### Version
2.0.0-alpha.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=67zSTS](https://play.nativescript.org/?template=play-vue&id=67zSTS)
### Platform and OS info
Android 5.0 and iOS 10

### Steps to reproduce
1- Open Playground link
2- Test it with your device.

### What is expected?
It should render list like any layout element like this. https://play.nativescript.org/?template=play-vue&id=lRSu2s&v=2

### What is actually happening?
Returned an error.

**Comment by rigor789** [comment]
`<ListView>` does not support `v-for` instead use `for`, see the docs: https://nativescript-vue.org/en/docs/elements/components/list-view/#props and https://nativescript-vue.org/en/docs/elements/components/list-view/#an-important-note-about-v-for

The playground has nativescript-vue `1.3.1`

**Comment by joannesalfa** [comment]
@rigor789 Would you mind to correct my code? I tried it with `for` instead of `v-for` and it returned the same error.

**Comment by rigor789** [comment]
Try with `2.0.0-alpha.2` (try with the `next` vue-cli-template: https://github.com/nativescript-vue/vue-cli-template/tree/next)  

I just tried with a simple example:

```xml
<ListView for="item in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]" separatorColor="transparent">
  <v-template>
    <StackLayout :backgroundColor="$even ? 'red' : 'blue'" >
      <Label v-for="i in item" :key="i" :text="i"/>
    </StackLayout>
  </v-template>
</ListView>
```
and it works fine on 2.0.0-alpha.2

**Comment by joannesalfa** [comment]
Thanks for clearing that, I'mclosing this issue.
