### ISSUE TITLE
How to make string interpolation

### ISSUE THREAD

**Issue by farhanrahmadi** [nativescript-vue/nativescript-vue#310]
i have raw curency on my data its still in integer but i want to do string interpolation with label
<Label :text="\\"Rp.\\"+ price"/> 

but it thrown error how could i work with that

**Comment by msaelices** [comment]
@farhanrahmadi could you try the following:
```
<Label :text="`Rp. ${price}`" />
```

**Comment by farhanrahmadi** [comment]
its work thank a lot @msaelices
