### ISSUE TITLE
Modal does not render ActionBar

### ISSUE THREAD

**Issue by lundtropic** [nativescript-vue/nativescript-vue#311]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=OJz25y](https://play.nativescript.org/?template=play-vue&id=OJz25y)
### Platform and OS info
iPhone 7; iOS 11.4.1

### Steps to reproduce
Preview Playground app. Click "To details directly".

### What is expected?
When modal opens, an ActionBar should exist at the top saying "Detail".

### What is actually happening?
No ActionBar exists.

---
Using exactly the code sample located in the official docs [here](https://nativescript-vue.org/en/docs/routing/manual-routing/#showmodal).

**Comment by rigor789** [comment]
Just tested this, indeed there is no action bar, as it is not actually supported this way.
I just updated the `$showModal` implementation in b2be4bdd34292b21463c598327a1495735ed99f9 which should allow you to wrap your modal in a Frame and then the ActionBar shows up. See sample below
https://github.com/nativescript-vue/nativescript-vue/blob/b2be4bdd34292b21463c598327a1495735ed99f9/samples/app/modals.js#L15-L31

**Comment by lundtropic** [comment]
@rigor789 Thanks. I got it working by using ```<Frame>```

However, I was having trouble passing props with the newly defined syntax. Once I converted it back to the old syntax it worked as such:

```javascript
openModal() {
  this.$showModal(ModalComponent, {
    context: {
      propsData: {
        foo: 'bar'
      }
    },
    fullscreen: true
  }).then(res => {
    this.modalResult = res
  })
},
```

**Comment by rigor789** [comment]
Just released the modal changes with the new syntax in `2.0.0-rc.0`!

**Comment by lundtropic** [comment]
Upgraded to rc.0 and, after I realized I needed to update props for all routing, the documented syntax works.

Thanks!
