### ISSUE TITLE
nativescript-plugin-firebase: Command gradlew.bat failed with exit code 1

### ISSUE THREAD

**Issue by telcy** [nativescript-vue/nativescript-vue#313]
### Version
1.3.1

### Reproduction link
[https://bitbucket.org/Telcy/vue-ns-firebase-test/src/master/](https://bitbucket.org/Telcy/vue-ns-firebase-test/src/master/)
### Platform and OS info
MacOS latest version

### Steps to reproduce
We need help with installing the nativescript-plugin-firebase

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/792

running `tns plugin add ...` does not work in the root folder, so we used `npm install --save ...` which seems to break the plugin behavior. The author seems to have no Vue experience. We would really appreciate if one of you guys could have a look. 

this is a test repo: https://bitbucket.org/Telcy/vue-ns-firebase-test/src/master/

### What is expected?
working `tns plugin add ... ` command in root folder and working firebase plugin

### What is actually happening?
ERROR: Unable to apply changes on device: xxx. Error is: Command gradlew.bat failed with exit code 1.

**Comment by rigor789** [comment]
Make sure you have `firebase.nativescript.json` in `template/` folder, and make sure you have `google-services.json` in `template/app/App_Resources/Android`, and then make sure you run `npm run clean` before trying to build again. If the issue still occurs, try `cd dist && tns run android --log trace` to see the full log which should include the gradle error that causes the build to fail.

**Comment by telcy** [comment]
Thanks! `tns run android --log` in dist folder helped me finding a solution.

```
13:47:38.254 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/Users/jascha/.gradle/caches/modules-2).
13:47:38.254 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
13:47:38.556 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@
708caba
13:47:38.556 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 14: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
13:47:38.557 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.] from daemon DaemonInfo{pid=1964, address=[c93643dc-73b7-4523-96fa-60795f07de33 port:52289, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1535179520716, context=DefaultDaemonContext[uid=2db4575d-b192-4774-a004-c3db512fc316,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home,daemonRegistryDir=/Users/jascha/.gradle/daemon,pid=1964,idleTimeout=10800000,daemonOpts=-Xmx16384M,-Dfile.encoding=UTF-8,-Duser.country=DE,-Duser.language=en,-Duser.variant]} (build should be done).
13:47:38.557 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
13:47:38.558 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
Command ./gradlew failed with exit code 1
```

Enabling multiDex as descriped [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#dexindexoverflowexception) fixed the problem.
