### ISSUE TITLE
State return incorrect value 

### ISSUE THREAD

**Issue by farhanrahmadi** [nativescript-vue/nativescript-vue#314]
Welll guys im in proccess developing an waitress app on mobile using nativescript-vue

the flow of app is : curstommer choose what menu they want and choosen menu send to order state,
in order page client can adjust how many they want for the menu and add some message, after it the order will go to bill state before order item push itu bill state it will check if the item already on bill only qty get update,

but here the problem when i adding same item it return not what i expected
in my bill i already have 1 item with qty 1 but just check this log
JS: { order: 2, billing: 1, item: ‘ke duar’ }
JS: { order: 2, billing: 1, item: ‘ke duar’ }
JS: { order: 4, billing: 2, item: ‘ke duar’ }
JS: { order: 8, billing: 4, item: ‘ke duar’ }

check my code 

view:
https://gist.github.com/farhanrahmadi/0b99887dc7894a59d9a0a24f619c4a87

bill module vuex: 
https://gist.github.com/farhanrahmadi/fa5b7b562d3bdabd2e8340d0a0db88c9

**Comment by budi7** [comment]
hello @farhanrahmadi, i believe this isn't bug with the nativescript vue nor the vuex. have you try to trace your data inside your iteration?

So. if i'm not get you wrong, you try to add item to previous billing/order or just create new order if no previous order selected. If so, i've successfully implement this with no errors. 

Maybe this can save your day

```
cartItemAdd: (state, payload) => {
         // 1. update carts
         var idx = state.cart_items.findIndex(x => x.product_code=== payload.product_code)

         if(idx < 0){ 
            // 1.a new data
            state.cart_items.push(payload) 
        }else{
            // 1.b update qty
            state.cart_items[idx].qty++
        }
 
         // 2. your additional things
}
```

Regards
