### ISSUE TITLE
the parents components dont render childrens

### ISSUE THREAD

**Issue by omarpe19** [nativescript-vue/nativescript-vue#317]
information:
im using template: nativescript-vue/vue-cli-template

-----------------------main.js------------------
import Vue from 'nativescript-vue';

import router from './router';

import store from './store';

import './styles.scss';

// Uncomment the following to see NativeScript-Vue output logs
Vue.config.silent = false;
Vue.registerElement('Gradient', () => require('nativescript-gradient').Gradient)
Vue.registerElement('CardView', () => require('nativescript-cardview').CardView)
Vue.registerElement('RadSideDrawer', () => require('nativescript-ui-sidedrawer').RadSideDrawer);

new Vue({

  router,

  store,

}).$start();

-----------------------index.js------------------
import Vue from 'nativescript-vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter);
import Asociados from '../components/content/Asociados';
import Cotizador from '../components/content/Cotizador';
import Creditos from '../components/content/Creditos';
import Perfil from '../components/content/Perfil';
import Ventas from '../components/content/Ventas';
import Panel from '../components/content/Panel';
import Padre from '../components/test/Padre';
import Hijo from '../components/test/Hijo';
import DashBoard from '../components/DashBoard';
import Login from '../components/Login';

const router = new VueRouter({
  pageRouting: true,
  routes: [
    {
      path: '/login',
      component: Login,
    },
    {
      path: '/padre',
      component: Padre,
      children:[
        {path: 'hijo',component: Hijo}, 
      ]
    },
    {
      path: '/dashboard',
      component: DashBoard,
      children:[
        {path: 'panel',component: Panel},
        {path: 'cotizador',component: Cotizador},
        {path: 'perfil',component: Perfil },
        {path: 'asociados',component: Asociados},
        {path: 'ventas',component: Ventas},
        {path: 'creditos',component: Creditos}
      ]
    },
    { path: '*', redirect: '/dashboard' }
  ]
});

router.replace('/login');

module.exports = router;

------------Parent.vue----------

   <Page class="page">
  <ScrollView>
            <StackLayout class="home-panel">
                
                <button textWrap="true" text="Padre" class="h2 description-label" @tap="$router.replace('/padre/hijo')"  />
            
            </StackLayout>
            
        </ScrollView>
        <router-view></router-view>
   </Page>

--------------Children-------------

   <Page class="page">
  <ScrollView>
            <StackLayout class="home-panel">
                
                <button textWrap="true" text="HOL SOY HIJO" class="h2 description-label" />
    
            </StackLayout>
        </ScrollView>
   </Page>

    https://new-issue.nativescript-vue.org/?repo=nativescript-vue/nativescript-vue

**Comment by rigor789** [comment]
Please use the issue helper and provide the required information. The code you provided is hard to read and understand without formatting (use 3 `'s to create a code block, check https://guides.github.com/features/mastering-markdown/)
