### ISSUE TITLE
Vue invocation fails under Jest test.

### ISSUE THREAD

**Issue by jofftiquez** [nativescript-vue/nativescript-vue#324]
### Version
1.3.1

### Reproduction link
[https://bitbucket.org/jofftiquez/mycure-doctor-mobile/src/nativescript-vue-issue/](https://bitbucket.org/jofftiquez/mycure-doctor-mobile/src/nativescript-vue-issue/)
### Platform and OS info
OSX Sierra

### Steps to reproduce
I think `src/vuex/store.js` line 1: `import Vue from 'nativescript-vue';` causes this error: 

> Cannot find module 'tns-core-modules/ui/layouts/layout-base' from 'index.js'

Every time I am creating a Jest test that involves files invoking `nativescript-vue`, this error occurs.

---------------- 

Kindly see files: 
1. `src/vuex/store.js`
2. `src/vuex/store.test.js`
3. `src/vuex/auth/auth.js`
4. `src/vuex/auth/auth.test.js`

### What is expected?
Test should run.

### What is actually happening?
Test scripts fails.

---
.env is not required to this repo, run `yarn install` and `yarn test`. Thank you.

**Comment by t3hmrman** [comment]
Hey just wanted to note that the bitbucket link you posted is login-protected/private -- maybe you could make a public repo for the reproduction test case? 

Also, could you post more of the stack trace from the error? It might be easier for others to help debug if you started from a working test case (even if it tests `1 + 1 = 2`) with jest and then add in the code you're suspecting is breaking it to go from working -> not working, and post those results here.

**Comment by jofftiquez** [comment]
Hi @t3hmrman, thanks for taking time to look at my issue. The repo I posted is already viewable and available for private forks if you have bitbucket account. I don't they have a public repo feature 😕 I'll update my issue tho along with the stack trace, however the only error I was getting was: 

> Cannot find module 'tns-core-modules/ui/layouts/layout-base' from 'index.js'

For the file `foo.test.js`

```
import Vue from 'nativescript-vue';

describe('foo', () => {
    test('bar', (done) => {
        // some test cases
        done();
    })
})
```

**Comment by t3hmrman** [comment]
Hey @jofftiquez it's a bit of a PITA but would you mind putting it on Gitlab/Github instead then? I'm not a maintainer/contributor to this project but I imagine it'd be hard for them to see the code too.

Also, have you seen [`navtivescript-vue-ui-tests`](https://github.com/nativescript-vue/nativescript-vue-ui-tests)? I think there's a thing or two in there that would help you. There's also [a big PR with upgraded appium and other stuff](https://github.com/nativescript-vue/nativescript-vue-ui-tests/pull/6) which might help if you're dealing with upgraded versions of things in your setup.

**Comment by msaelices** [comment]
@t3hmrman FYI, I've just upgraded `nativescript-vue-ui-tests` to the latest versions of NS, NS-vue and appium.

**Comment by msaelices** [comment]
I've found that the #357 issue is the same as this one but with a public repo for reproducing the error. So I will close this issue. Please follow the #357 one

**Comment by jofftiquez** [comment]
Thanks @msaelices that will do.
