### ISSUE TITLE
Fetch and Http post not working

### ISSUE THREAD

**Issue by monkeymonk** [nativescript-vue/nativescript-vue#326]
### Version
1.3.1

### Platform and OS info
iOS 10.1 / iPhone 6 (Simulator) / NativeScript 4.2.2 / macOS 10.13.6

### Steps to reproduce

Try one of those script inside a Vue component and mount.

```javascript
import * as http from 'tns-core-modules/http';

http.request({
    content: JSON.stringify({foo: 'bar'}),
    headers: {
        'Cache-Control': 'no-cache',
        'Content-Type': 'application/json',
    },
    method: 'POST',
    url: 'https://httpbin.org/post',
})
    .then((response) => {
        // ...the request work but "foo" is not sent! (response.form is empty)
        console.log('(ಠಿ_ಠ)', response);
    });
```

```javascript
import fetch from 'tns-core-modules/fetch';

fetch({
    body: JSON.stringify({foo: 'bar'}),
    headers: {
        'Cache-Control': 'no-cache',
        'Content-Type': 'application/json',
    },
    method: 'POST',
    url: 'https://httpbin.org/post',
})
    .then((response) => {
        // ...never reached
        console.log('(눈‸눈)', response);
    });
```

### What is expected?

"tns-core-modules/http" should send parameters and with POST method.

"tns-core-modules/fetch" should send a request properly...

### What is actually happening?

With "tns-core-modules/http", the request is sent without parameter (no content).
The Chrome devtools show the request as GET instead of POST.
The result of "https://httpbin.org/post" show an empty "form".

Ex.

```json
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-us", 
    "Cache-Control": "no-cache", 
    "Connection": "close", 
    "Content-Length": "0", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "Mozilla/5.0 (iPhone; CPU OS 10_1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/10.1 Mobile/10A5355d Safari/8536.25"
  }, 
  "json": null, 
  "origin": "15.173.122.100", 
  "url": "https://httpbin.org/post"
}
```

With "tns-core-modules/fetch", nothing seems to happen... Chrome devtools show no request activity.

---
The result of "https://httpbin.org/post" should show every parameters sent in "form" key.
Ex. (tested with Postman) 

```json
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
        "foo": "bar"
    },
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-us", 
    "Cache-Control": "no-cache", 
    "Connection": "close", 
    "Content-Length": "0", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "Mozilla/5.0 (iPhone; CPU OS 10_1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/10.1 Mobile/10A5355d Safari/8536.25"
  }, 
  "json": null, 
  "origin": "15.173.122.100", 
  "url": "https://httpbin.org/post"
}
```

**Comment by mila76** [comment]
Using var http = require("http"); and not tns-core-modules/http seem work here..
From the error i can only suppose is a webpack related issue

**Comment by Reached** [comment]
You probably solved this already or moved on to something else, but just for reference; you don't have to import fetch to use it :)

**Comment by monkeymonk** [comment]
Hello there, sorry for the late reply I was on some other projects and so wasn't able to test further...

But I'm back on this project and... nothing seems to work. I have tried `const http = require('http');` and using `fetch` without importing... but the result is absolutely the same.

I have now succeeded using [axios](https://github.com/axios/axios).
(For those who have the same problem and decide to use axios, "post" will work with "params" despite the documentation that says "data"...)

So, I guess we can close this for now. But this is still weird that "http" and "fetch" fails...

**Comment by DepickereSven** [comment]
Why not use the native fetch from javascript like this? :
```
let fetchRequestForGettingData = function (url) {
        return fetch(url)
            .then((resp) => {
                console.log(resp.status);
                return resp.json();
            })
    };
```

**Comment by uniqueginun** [comment]
**_i'm having this issue_**

**Comment by jpldev** [comment]
> Hello there, sorry for the late reply I was on some other projects and so wasn't able to test further...
> 
> But I'm back on this project and... nothing seems to work. I have tried `const http = require('http');` and using `fetch` without importing... but the result is absolutely the same.
> 
> I have now succeeded using [axios](https://github.com/axios/axios).
> (For those who have the same problem and decide to use axios, "post" will work with "params" despite the documentation that says "data"...)
> 
> So, I guess we can close this for now. But this is still weird that "http" and "fetch" fails...

How do you resolve it with axios?
I have the same problem with fetch, and with axios.get(uri) i get undefinied response.data, with postman works.

**Comment by msaelices** [comment]
@jpldev could you share a minimal sample app which is failing? I am using the NS `fetch` API with total success in a production app and I've never found your problem.

**Comment by fmaylinch** [comment]
I experience the same problem. POST calls fail in iOS, using `fetch`, `axios` or `http`.

These POST don't show anything.
If they're GET calls they all work.

I have verified the POST calls via Postman or node simple program.

```
import * as http from "http";
import axios from 'axios';

...

fetch(url, {method: "POST"})
  .then(r => r.json())
  .then(r => console.log(r.json))
  .catch(e => console.error(e));

axios.post(url)
  .then(r => console.log(r.data))
  .catch(e => console.error(e));

http.request({url: url, method: "POST"})
  .then(
    r => console.log(r.content.toJSON()),
    e => console.error(e));
```
