### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by nuochong** [nativescript-vue/nativescript-vue#327]
`$ tns run android --bundle`
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watchPatterns hook from D:\kyj\nativescript\admin\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from D:\kyj\nativescript\admin\hooks\before-watch\nativescript-dev-webpack.js
Running webpack for Android...
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Executing webpack failed with exit code 3.`

**Comment by mila76** [comment]
Same error on webpack: "a memory leak caused by the sass-loader"
Try look on that direction... some css problem?

**Comment by nuochong** [comment]
> webpack上的相同错误：“由sass-loader引起的内存泄漏” 
> 试试看那个方向......一些css问题？

Thank you. It seems that the other NPM sources are used.
