### ISSUE TITLE
CSS takes too long to be compiled by IOS when being referenced in many Vue components then crashes

### ISSUE THREAD

**Issue by andreMariano90** [nativescript-vue/nativescript-vue#328]
### Version
1.3.1

### Platform and OS info
IOS Physical Device

### Steps to reproduce
Create as many as 20 Vue components. In Every component reference the styles.scss file
example: In every vue component only type this:
```javascript
<style scoped lang="scss">
  @import "../styles.scss";
</style>
```

Then compile it. Your output css (in dist/app/app.ios.css or dist/app/app.android.css) will be huge. Like 300kb huge. therefore iOS won't leave the splash screen and will crash. Simulate directly in a physical device compiling a real code, otherwise you won't find the bug.

### What is expected?

The compiled css file to be as little as the original scss file

### What is actually happening?
The output css file is reaching more than 300kb unabling ios to run.

### Workaround
Set almost every style in the app.scss style sheet. This way the scss will be small. In my app, for example, I removed every stylesheet from my vue components.

---
I ran into this bug when sending my app to the apple store.
I only found out using the timeline-view that the css compilation was taking too long because the css was huge
https://www.nativescript.org/blog/deep-dive-into-nativescript-3.1-performance-improvements

This should be a heads up for any developer. But I didn't test it in the nativescript-vue 2.0

**Comment by andreMariano90** [comment]
I showed that example that only by importing the scss, not using any variable, the output css increases.

I will give a more practical example.

```javascript
<style scoped lang="scss">
  @import "../styles.scss";

  .action-item{
    color: $white;
  }

  .sidedrawer-left {

    .sidedrawer-header {
      background-color: $primary-color;
      height: 120;
    }

    .sidedrawer-header-image {
      width: 80;
      height: 80;
      background-color: #fff;
      border-width: 1;
      border-color: #fff;
      border-radius: 100% !important;
      margin-top: 10;
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
    }

    .sidedrawer-header-username {
      font-weight: bold;
      color: $white;
    }

    .separador {
      margin-top: 20;
    }

    .sidedrawer-list-item {
      width: 100%;
      height: 40;
      margin-top: 15;
      font-size: 16;

      image {
        width: 12%;
        margin-left: 15%;
        margin-right: 5%;
      }

      label {
        width: 78%;
      }
    }
  }
  
  .list-header {
    height: 30;
    color: #fdfdfd;
    font-size: 16;
    font-weight: 900;
    padding: 5%;
    margin-bottom: 5;
    background-color: $secondary-color;
  }

</style>
```

For example, in this style. I just wanna get the default variables. ($primary-color or $secondary-color), but my output css becomes huge because it aparently copies everything from the 'styles.scss' file.

**Comment by rigor789** [comment]
Closing this - as it is a webpack/vue-loader related issue. Generally you should only import variables/utilities - they will be compiled to css. Otherwise, it will add all css to every component, resulting in duplicated styles and a massive amounts of css. (This is especially true if you are scoping the styles).
