### ISSUE TITLE
Imports do not work

### ISSUE THREAD

**Issue by mrcatman** [nativescript-vue/nativescript-vue#329]
### Version
2.0.0

### Reproduction link
[https://github.com/mrcatman/karapuztv-app](https://github.com/mrcatman/karapuztv-app)
### Platform and OS info
Android 7.0 / NativeScript 4.0 / Windows 10

### Steps to reproduce
tns run android

### What is expected?
Working import functionality (like "import Vue from 'nativescript-vue'")

### What is actually happening?
Unexpected identifier on imports (http://prntscr.com/kxpswx). Requires do work, but then I can't import Vue components.

---
An error log:

Successfully synced application org.nativescript.application on device emulator-
5554.
System.err: java.lang.RuntimeException: Unable to create application com.tns.Nat
iveScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Cannot compile /data/data/org.nativescript.application/files/app/mai
n.js
System.err:
System.err: SyntaxError: Unexpected identifier
System.err: File: "file:///data/data/org.nativescript.application/files/app/main
.js, line: 1, column: 67
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: SyntaxError: Unexpected identifier
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThre
ad.java:5406)
System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.jav
a:1545)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(Zy
goteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: com.tns.NativeScriptException:
System.err:
System.err: Cannot compile /data/data/org.nativescript.application/files/app/mai
n.js
System.err:
System.err: SyntaxError: Unexpected identifier
System.err: File: "file:///data/data/org.nativescript.application/files/app/main
.js, line: 1, column: 67
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: SyntaxError: Unexpected identifier
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:553)
System.err:     at com.tns.Runtime.run(Runtime.java:545)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplicat
ion.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumen
tation.java:1024)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThre
ad.java:5403)
System.err:     ... 8 more

**Comment by mila76** [comment]
i run your code and the app run... no error

sure you used tns run android --bundle ?

**Comment by mrcatman** [comment]
I forgot to add "--bundle", thanks, the problem is solved
