### ISSUE TITLE
How to be more efficient?

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-vue/nativescript-vue#330]
I would just like some advice on how to work the most effectively with sight.
Should work with simple javascrip and .js files or .vue files especially that I would like to take advantage of the module "HMR"?

I ask because i wanted to test nativescript-ui-calendar and it did not work with the .vue file but oddly enough worked with a .js file

I really like nativescript-view

And how to start a project with typescript if I have to use simple .ts files without using .vue files?

**Comment by rigor789** [comment]
We don't currently offer a typescript template, but it's something that is on the roadmap.

For HMR, what I found a good workflow is only using HMR when changing templates/laying things out.

When I need to change any logic or code, I stop HMR and use regular `--bundle`.
