### ISSUE TITLE
Manual Routing: Documentation Example not working

### ISSUE THREAD

**Issue by tweichart** [nativescript-vue/nativescript-vue#340]
### Version
2.0.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=8DlYMb&v=2](https://play.nativescript.org/?template=play-vue&id=8DlYMb&v=2)
### Platform and OS info
iPhone 6 Emulator / iOs 12 / NativeScript 4.0 / MacOS Mojave

### Steps to reproduce
Use the routing example from https://nativescript-vue.org/en/docs/routing/manual-routing/#in-the-view

### What is expected?
Navigation to the details page.

### What is actually happening?
Nothing, no routing. The page stays on the default page.

**Comment by rigor789** [comment]
@tweichart you are (and the docs too) missing a `Frame`. I just updated the docs https://github.com/nativescript-vue/nativescript-vue.org/commit/3c5ce2caef4fdab27e10c4e91651f213db638961

**Comment by tweichart** [comment]
looks good, thanks ;-)
