### ISSUE TITLE
There is no way to access the real .nativeView

### ISSUE THREAD

**Issue by OsamaAbbas** [nativescript-vue/nativescript-vue#354]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=3qA6Ka&v=2](https://play.nativescript.org/?template=play-vue&id=3qA6Ka&v=2)
### Platform and OS info
Android 5.1.1

### Steps to reproduce
Open the play ground, run the app on an android device (or ios, too).

Click the button.

See the log message.

### What is expected?
It should log something like this:

`android.widget.Button{371341c1 VFED..C. ...P.... 0,112-720,1232}`

### What is actually happening?
It logs some javascript or vue object.

So clearly, the `nativeView` property does not return the real `nativeView`, I have searched everywhere to find a workaround but found none.

---
Check this playground:

https://play.nativescript.org/?template=play-js&id=RfrecN

It's an identical app but in plain javascript. It should make the problem clear.

**Comment by OsamaAbbas** [comment]
After some digging, it is here:

`button.nativeView.__nativeView`

This should be added to the docs I guess.

**Comment by OsamaAbbas** [comment]
And for WebView, it is: `webView.__nativeView`!

**Comment by OsamaAbbas** [comment]
Yes it is.

I looked into the source code, I found that this property `.nativeView` is set in many places. So, that's why it has a different value. But the real weird thing is this property `.__nativeView`, it is not even there in the whole source code! I could not figure where did it come from.

Back to the playground, I use something like this `for (let key in webView) console.log(key);` to list all properties of the object, that's how I found where the nativeView is in Buttons and WebViews.

**Comment by OsamaAbbas** [comment]
Please check this issue and its workaround:
https://github.com/NativeScript/NativeScript/issues/6437

As you can see, to solve it we need an access to the real `nativeView` object. Which is missing in SearchBar.

**Comment by OsamaAbbas** [comment]
According to CHANGELOG.md,

> BREAKING CHANGES
> All elements are now Vue components, in some cases where a ref is used to get the nativeView will have to be updated to use `this.$refs.element.$el.nativeView` instead of `this.$refs.element.nativeView`. There may be other breaking changes this introduces that are not known at this point.

Well, `this.$refs.element.$el` is undefined, at least in the elements that I have tested.

I'm confused, the documentation needs to be more clear here. I don't understand if `nativeView` refers to the native view in Android or iOS APIs, or to the original element in {N}, or to the Vue component itself!

Please check this and make it clear. I'm too will do my best to demystify it.

**Comment by rigor789** [comment]
That note is actually incorrect, but it is in git history, and automatically included in the changelog...

The `nativeView` you access through refs is the NativeScript view instance, which is a confusing name for it, as NativeScript view instances also have nativeView which usually points to the native, android/ios views. But changing it now would break a lot of things, so we will keep it this way, at least until 3.0.

**Comment by jwktje** [comment]
I'm having this issue too. There seems to be no consistent way to get at the nativeView through $refs.

**Comment by groenroos** [comment]
I think I'm running into this issue too on the iOS side for a Label element. Trying to use the workaround in the comments of NativeScript/NativeScript#8120, but assigning a value to `nativeView.attributedText` has no effect, and I wonder if this issue is related. Neither `nativeView.__nativeView` nor `nativeView.$el.nativeView` seem to exist.

**Comment by rigor789** [comment]
@groenroos use the `@loaded` event of the view: 

```html
<Label @loaded="doWhatever" />
```
```js
doWhatever(args) {
  // the ios native view
  console.log(args.object.ios)

  // the android native view
  console.log(args.object.android)
}
```

This is the safest way to do any modification to the native views when they are ready! 

Through refs, you would do 
```js
this.$refs.whatever.nativeView.ios
this.$refs.whatever.nativeView.android
```
but may require a `setTimeout` since the views may not be created right away, so generally don't recommend doing it that way.

**Comment by groenroos** [comment]
Absolute magic! Works a treat now, thanks @rigor789! 😄

I had seen the `nativeView.ios` in some examples, but it was always undefined for me. I assumed it was a deprecated feature or something, I don't know why the no.1 JS debug technique of "is it defined yet?" didn't occur to me!
