### ISSUE TITLE
iOS Build Release Crash Launch on Physical Device

### ISSUE THREAD

**Issue by teonator** [nativescript-vue/nativescript-vue#355]
### Version
2.0.2

### Reproduction link
[https://github.com/teonator/helloworld-nativescript-vue](https://github.com/teonator/helloworld-nativescript-vue)
### Platform and OS info
 iOS 12.0.1, NativeScript 4.2.4, macOS Mojave 10.14

### Steps to reproduce
1. `vue init nativescript-vue/vue-cli-template helloworld`
2. `cd helloworld`
3. `npm install`
4. `tns build ios --release --for-device --provision <uuid>`
5. Load the built helloworld.ipa using Xcode > Devices & Simulators to physical device.

### What is expected?
Launch on physical device

### What is actually happening?
Crash on launch

---
It seems only happened with Vue. I have tried the same process create a blank template with Angular using the same adhoc provisioning profile and id without crashing the app when launch on physical device.

**Comment by microwavesafe** [comment]
You need to add ```--bundle``` to your build step i.e.

```tns build ios --release --for-device --provision <uuid> --bundle```

**Comment by teonator** [comment]
Thanks. It is working!
