### ISSUE TITLE
instance cannot get access

### ISSUE THREAD

**Issue by farhanrahmadi** [nativescript-vue/nativescript-vue#358]
hei guys, last night i start my project using nativescript-vue 2.0 i cannot acces my instace 

here my script 

`<template>
    <Page>
        <ActionBar>
            <GridLayout width="100%" columns="auto, *">
                
                <Label class="title" text="Attendance App" align="center"  col="1"/>
            </GridLayout>
        </ActionBar>
        <RadSideDrawer ref="drawer">
            <StackLayout ~drawerContent backgroundColor="#ffffff">
                <Label class="drawer-header" text="Coming Soon"/>
            </StackLayout>
            <GridLayout v-if="attendanceData.img != '' " ~mainContent columns="auto,*" rows="auto,*">
                <Image :src="attendanceData.img" class="attendance-image" stretch="none" col="1" row="1" />
                <Label class="message" :text="attendanceData.time" col="0" row="2"/>
            </GridLayout>
            <GridLayout v-else ~mainContent column="auto,*" rows="auto,*">
              <StackLayout row="1">
                <Button text="Button" @tap="cameraClick(attendanceData)" class="main-button" />
              </StackLayout>
            </GridLayout>
        </RadSideDrawer>
    </Page>
</template>
<script>
import { Image } from "tns-core-modules/ui/image";
const Toast = require("nativescript-toast");
import * as camera from "nativescript-camera";
import { isEnabled, enableLocationRequest, getCurrentLocation, watchLocation, distance, clearWatch } from "nativescript-geolocation";
export default {
    data() {
      return {
        msg: 'Please Sign Your Attendance',
        attendanceData : {
        location: '',
        img: '',
        time: ''
      }
      }
    },
    methods: {
      cameraClick : (target) =>{
        // target.location = isEnabled().then(function (isEnabled) {
        //   if (!isEnabled) {
        //     var location = getCurrentLocation({desiredAccuracy: 3, updateDistance: 10, maximumAge: 20000, timeout: 20000}).
        //     then(function(loc) {
        //       if (loc) {
        //         return loc
        //       }
        //     }, function(e){
        //       console.log("Error: " + e.message);
        //     });
        //   }
        // }, function (e) {
        //   console.log("Error: " + (e.message || e));
        // })
        camera
        .takePicture({ width: 150, height: 150, keepAspectRatio: false })
        .then(
          imageAsset => {
            this.img = imageAsset;
            this.time = new Date().getTime();
            console.log(this.image);
          },
          error => console.log(error)
        )
        .catch(err => {
          console.log("Error -> " + err.message);
        });
      },
    }
  }
</script>`

it retturn img not defined 

but when i pass data as param  it defined like this 

`<template>
    <Page>
        <ActionBar>
            <GridLayout width="100%" columns="auto, *">
                
                <Label class="title" text="Attendance App" align="center"  col="1"/>
            </GridLayout>
        </ActionBar>

        <RadSideDrawer ref="drawer">
            <StackLayout ~drawerContent backgroundColor="#ffffff">
                <Label class="drawer-header" text="Coming Soon"/>
            </StackLayout>

            <GridLayout v-if="attendanceData.img != '' " ~mainContent columns="auto,*" rows="auto,*">
                <Image :src="attendanceData.img" class="attendance-image" stretch="none" col="1" row="1" />
                <Label class="message" :text="attendanceData.time" col="0" row="2"/>
        
            </GridLayout>
            <GridLayout v-else ~mainContent column="auto,*" rows="auto,*">
              <StackLayout row="1">
                <Button text="Button" @tap="**cameraClick(attendanceData)**" class="main-button" />
              </StackLayout>
            </GridLayout>
        </RadSideDrawer>
    </Page>
</template>
<script>
import { Image } from "tns-core-modules/ui/image";
const Toast = require("nativescript-toast");
import * as camera from "nativescript-camera";
import { isEnabled, enableLocationRequest, getCurrentLocation, watchLocation, distance, clearWatch } from "nativescript-geolocation";
export default {
    data() {
      return {
        msg: 'Please Sign Your Attendance',
        attendanceData : {
        location: '',
        img: '',
        time: ''
      }
      }
    },
    methods: {
      cameraClick : (target) =>{
        // target.location = isEnabled().then(function (isEnabled) {
        //   if (!isEnabled) {
        //     var location = getCurrentLocation({desiredAccuracy: 3, updateDistance: 10, maximumAge: 20000, timeout: 20000}).
        //     then(function(loc) {
        //       if (loc) {
        //         return loc
        //       }
        //     }, function(e){
        //       console.log("Error: " + e.message);
        //     });
        //   }
        // }, function (e) {
        //   console.log("Error: " + (e.message || e));
        // })
        camera
        .takePicture({ width: 150, height: 150, keepAspectRatio: false })
        .then(
          imageAsset => {
            this.img = imageAsset;
            this.time = new Date().getTime();
            console.log(this.image);
          },
          error => console.log(error)
        )
        .catch(err => {
          console.log("Error -> " + err.message);
        });
      },
    }
  }
</script>`

Thanks

**Comment by tralves** [comment]
Hey, @farhanrahmadi, this issue is unreadable. please format it properly. Thanks

**Comment by farhanrahmadi** [comment]
Sorry for the unconvinient my format please check my new post https://github.com/nativescript-vue/nativescript-vue/issues/359
