### ISSUE TITLE
Instace cannot get access

### ISSUE THREAD

**Issue by farhanrahmadi** [nativescript-vue/nativescript-vue#359]
### Version
2.0.0

### Script link
[https://gist.github.com/farhanrahmadi/02e48619df68f174a46093ea37405cd7](https://gist.github.com/farhanrahmadi/02e48619df68f174a46093ea37405cd7)
### Platform and OS info
Android

### Steps to reproduce
I need use camera and show the picture 

### What is expected?
when picture take it change the instance 

### What is actually happening?
the instance is define

**Comment by rigor789** [comment]
Based on the provided code, I don't really understand the question/issue. Please open a new issue with more details if you are still experiencing the problem.
