### ISSUE TITLE
Help - Problem using fonticons

### ISSUE THREAD

**Issue by bcazu** [nativescript-vue/nativescript-vue#364]
Hi
![image](https://user-images.githubusercontent.com/33225101/47260138-ff5a3280-d47a-11e8-8ae2-b4b7ce5b2212.png)

![image](https://user-images.githubusercontent.com/33225101/47260154-37fa0c00-d47b-11e8-84df-8012565d4279.png)

The problem is that the icons are not appearing.
![image](https://user-images.githubusercontent.com/33225101/47260162-58c26180-d47b-11e8-8cc2-d49740a19a05.png)

Please help me

**Comment by piyunior** [comment]
Hello good night, in the app.scss file did you add the correct settings?

**Comment by bcazu** [comment]
Yes.
.fa {
  font-family: FontAwesome, fontawesome-webfont;
}

**Comment by piyunior** [comment]
Include the css folder inside assets and if you still get an error, try removing the platforms and adding them again.

**Comment by piyunior** [comment]
![captura de pantalla de 2018-10-22 12-37-34](https://user-images.githubusercontent.com/19761096/47305380-4ff69a80-d5f7-11e8-81d6-cacc8c7e60e9.png)

This is in case you are using FontAwesome 5.

![captura de pantalla de 2018-10-22 12-38-43](https://user-images.githubusercontent.com/19761096/47305437-6f8dc300-d5f7-11e8-858f-9c00a8cdbd4f.png)

**Comment by bcazu** [comment]
> ![captura de pantalla de 2018-10-22 12-37-34](https://user-images.githubusercontent.com/19761096/47305380-4ff69a80-d5f7-11e8-81d6-cacc8c7e60e9.png)
> 
> This is in case you are using FontAwesome 5.
> 
> ![captura de pantalla de 2018-10-22 12-38-43](https://user-images.githubusercontent.com/19761096/47305437-6f8dc300-d5f7-11e8-858f-9c00a8cdbd4f.png)
Can you show me your main.js please?

**Comment by rigor789** [comment]
@bcazu the `css` folder is not copied to the app folder as webpack is not configured to copy it. Move it into assets, like @piyunior suggested, and in main js, update the path to be `./assets/css/fontawesome.css`.

Alternatively, tweak webpack config to copy the css folder (not recommended, as the assets folder is made just for this).

**Comment by piyunior** [comment]
![captura de pantalla de 2018-10-23 11-50-07](https://user-images.githubusercontent.com/19761096/47373439-dd022800-d6b9-11e8-8b37-ac411db710f9.png)

That's the configuration in the main.js with that should be enough for you to use the icons @bcazu. And thanks @rigor789 (Y)

**Comment by bcazu** [comment]
Sorry u.u not working:

![image](https://user-images.githubusercontent.com/33225101/47690146-ea884800-dbba-11e8-913a-ef5f98cc69a9.png)

![image](https://user-images.githubusercontent.com/33225101/47690162-f96efa80-dbba-11e8-9a3b-a5442725c2ed.png)

![image](https://user-images.githubusercontent.com/33225101/47690171-05f35300-dbbb-11e8-807c-e97617d4917c.png)

![image](https://user-images.githubusercontent.com/33225101/47690189-14416f00-dbbb-11e8-8aec-3118f34a75d2.png)

**Comment by bcazu** [comment]
Surprisingly I started another project and it worked very well
