### ISSUE TITLE
$navigateTo outside of vue component

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/nativescript-vue#365]
### What problem does this feature solve?
I created my own Api vue plugin which exntends Vue:
```
export default {
export default {
    install: (Vue) => {
        Vue.prototype.$api = api;
    }
};
```
In my api-module I catch all api errors, to check if the user session is over, so I would navigate to my login component.
It works with `Vue.prototype.$navigateTo`, but there are no extensions like `Vuex`'s `$store` (and others) available.

Is there a way to get it work?

**Comment by wendt88** [comment]
found a solution:
```
import { topmost } from 'ui/frame';

topmost().currentPage.__vuePageRef__.$navigateTo(...)
```

any other solution is welcome ;)
I hope the key `__vuePageRef__` does not changes, or a method, that returns the vue instance would be nice

**Comment by aldiand** [comment]
Have same problem, with your solution. you save my time 👍 💯  thank you so much

**Comment by Shuunen** [comment]
thanks @wendt88 worked like a charm, I just updated the import 👍 
```js
import { topmost } from 'tns-core-modules/ui/frame'

function navigateTo (page) {
  topmost().currentPage.__vuePageRef__.$navigateTo(page, {
    frame: 'mainContent'
  })
}
```

**Comment by brysem** [comment]
Based on @Shuunen awesome function, I created a typescript version.
```typescript
import { topmost } from 'tns-core-modules/ui/frame';
import Vue, { NavigationEntryVue } from 'nativescript-vue';
import { VueConstructor } from 'vue';

export const navigateTo = (component: VueConstructor, options?: NavigationEntryVue): void => {
  const currentComponent: Vue = (topmost().currentPage as any).__vuePageRef__;

  currentComponent.$navigateTo(component, options);
};
```

**Comment by Shuunen** [comment]
Got this message `topmost() is deprecated. Use Frame.topmost() instead.` so here is the updated JS version : 

```js
import { Frame } from 'tns-core-modules'

export function navigateTo (component, options) {
  Frame.topmost().currentPage.__vuePageRef__.$navigateTo(component, options)
}
```

**Comment by Shuunen** [comment]
I'm wondering what @rigor789 or other contributors think about this, maybe there's a better or cleaner way 💭

**Comment by rigor789** [comment]
@Shuunen I don't see why 
```js
import Vue from 'nativescript-vue'

Vue.prototype.$navigateTo(component, options)
```
wouldn't work - there was an old version that required a view instance to navigate - thus it's only available through the `prototype`, but it no longer depends on the `this` context.

**Comment by Shuunen** [comment]
Wow you're fast 😄 thanks for this shorter/simpler solution

**Comment by CristianHG2** [comment]
> found a solution:
> 
> ```
> import { topmost } from 'ui/frame';
> 
> topmost().currentPage.__vuePageRef__.$navigateTo(...)
> ```
> 
> any other solution is welcome ;)
> I hope the key `__vuePageRef__` does not changes, or a method, that returns the vue instance would be nice

Works perfectly on Android, but for some reason I am not able to make this work on iOS. Anybody else experiencing this?
