### ISSUE TITLE
$navigateTo nested Frame does show nothing

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/nativescript-vue#366]
### Version
2.0.2

### Reproduction link
[Playground](https://play.nativescript.org/?template=play-vue&id=p1JwCL&ReturnUrl=https:%2F%2Fidentity.telerik.com%2Fv2%2Foauth%2Ftelerik%2Fauthorize%3Fclient_id%3Duri%253Ans-playground%26redirect_uri%3Dhttps%253A%252F%252Fplay.nativescript.org%252Fprofile%252Fc%26response_type%3Dcode&username=wendt88@gmail.com&error_message=Wrong%20username%20or%20password.&v=4)
### Platform and OS info
Android

### Steps to reproduce
click at one of theses buttons in playground

### What is expected?
that above opens one of the contents
1 -> Hello world text content
2 -> Image

### What is actually happening?
Components get rendered (watch console),
but nothing gets shown
looking the elements on chrome in debug mode, there is only a `Frame` text:

![frame](https://user-images.githubusercontent.com/13959976/47490135-5e87c080-d848-11e8-977e-84bbfdf47820.PNG)

**Comment by rigor789** [comment]
I can't see buttons in the linked playground, can you check if you linked the correct one? 

As a side note, I'm not sure if nested frames are supported in NativeScript, can't find much info on that...

**Comment by wendt88** [comment]
Sorry, I updated now my link in the original post.
the only thing I could find on these was:
https://github.com/nativescript-vue/nativescript-vue/issues/213
and watching the code there is a frame option for the `$navigateTo` method.
looking to console the components gets initialized and also the history works

**Comment by wendt88** [comment]
Now I get it work by wrapping my content in a `<Page>`.
In my case I have a sidedrawer wich navigates the frame inside `mainContent`.
I navigate always to the same content passing various `pageId`'s as a property.
Navigating works, but if I go back, no [Vue-Lifecycle-Hook](https://vuejs.org/v2/api/#Options-Lifecycle-Hooks) gets triggered, so from my base component (containing the sidedrawer) doesn't know on which page (`pageId`) the user is.
as a workaround I navigate normaly from basecomponent to same basecomponent passing the `pageId`, which I pass to his subcomponent (the content)
the only thing is, that so my basecomponent containing the sidedrawer gets rerendered every time

**Comment by rigor789** [comment]
Back navigation doesn't actually trigger any Vue lifecycle events, as the instance in the backstack is not destroyed. Instances in the backstack are only destroyed when using `clearHistory: true` or navigating from an entry with `backstackVisible: false`.

Can you share what you need the lifecycle events for? Can you use `navigated` and `navigatedBack` events on the `<Frame>` instead? 

I'm not sure if we have these documented, but you can see when they are emitted here:

https://github.com/nativescript-vue/nativescript-vue/blob/cfbf83d619805108de2b0bbc46fec9b8a721fa82/platform/nativescript/runtime/components/frame.js#L109-L116

**Comment by pdipasqua** [comment]
Your code it's ok but you must add the page tag on your pages

<Page actionBarHidden="true">
</Page>

**Comment by wendt88** [comment]
the `navigated` and `navigatedBack` events solved my problem... there I have access to the props, thx!

**Comment by zslusnys** [comment]
May I ask why you need navigation within the same component (that is if I understood the problem correctly)? You were saying you use this as a workaround, maybe vuex would be of a value for you here?
