### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by psaren** [nativescript-vue/nativescript-vue#367]
### Version
2.0.0

### Reproduction link
[https://github.com/psaren/nativescript-vue-reproduction](https://github.com/psaren/nativescript-vue-reproduction)
### Platform and OS info
Android 7.0

### Steps to reproduce
just run "tns run android --bundle", the error show blow:

$ tns run android --bundle
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Starting Android emulator with image Nexus_5X_API_24
Waiting for emulator device initialization...
Executing before-watchPatterns hook from G:\study\nativescript\ns-project\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from G:\study\nativescript\ns-project\hooks\before-watch\nativescript-dev-webpack.js
Running webpack for Android...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Executing webpack failed with exit code 3.
Cannot read property 'kill' of undefined

### What is expected?
The app can run successfuly!

### What is actually happening?
App run failed!

**Comment by rigor789** [comment]
Seems like webpack is running out of memory. Do you have enough free memory when running the commands? (I'm not sure what "enough" would be, but just check if it's not too low)

**Comment by msaelices** [comment]
As @rigor789 mentioned, it seems a Webpack memory overflow error. As @psaren did not respond to the @rigor789 question, I will close this issue considering that it is not related to NS-Vue, unless @psaren re-open it again with more information about it.
