### ISSUE TITLE
Button press animation not working with border-radius

### ISSUE THREAD

**Issue by alexandrmiee** [nativescript-vue/nativescript-vue#370]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=3rSNIU](https://play.nativescript.org/?template=play-vue&id=3rSNIU)
### Platform and OS info
Android

### Steps to reproduce
Create button
set css border-radius

### What is expected?
worked press animation

### What is actually happening?
not showing

**Comment by ppritcha** [comment]
I have the same issue.  This is happening for me as well.

**Comment by rigor789** [comment]
This is expected/comes from NativeScript itself (nothing affecting this behavior is in NativeScript-Vue). See https://stackoverflow.com/a/53170548
