### ISSUE TITLE
tns preview not working

### ISSUE THREAD

**Issue by bcazu** [nativescript-vue/nativescript-vue#375]
Hi.
Thanks for your great effort in bringing new updates.
On this occasion I am trying to test tns preview but it does not work. I tried to generate a new project vue with tns create but I have the same problem.

I use Windows 10 / Android 6.0 / NativeScript 5.0 and my cellphone is Moto G3 Android 6.0
![image](https://user-images.githubusercontent.com/33225101/48390439-08cc6880-e6d0-11e8-962d-fd2293ba1153.png)

**Comment by rigor789** [comment]
Missing `--bundle` flag, so it tries to require `.vue` files without them being processed by webpack first.

**Comment by bcazu** [comment]
> Missing `--bundle` flag, so it tries to require `.vue` files without them being processed by webpack first.
I init a proyect whit tns create and exceute tns preview --bundle and work fine but I updated my proyect from nativeScript 4 to nativeScript 5 and excecute tns preview --bundle but look at this:
Entrypoint bundle = vendor.js bundle.js
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 175 bytes {bundle} [built]                                                                                                                        lt]
[./ sync recursive (root|page)\.(xml|css|js|ts|scss)$] . sync (root|page)\.(xml|css|js|ts|scss)$ 160 bytes {bundle} [built]
[./app.scss] 18.8 KiB {bundle} [optional] [built]
[./main.js] 2.22 KiB {bundle} [built]
[nativescript-vue] external "nativescript-vue" 42 bytes {bundle} [built]
[nativescript-vue-devtools] external "nativescript-vue-devtools" 42 bytes {bundle} [built]
[tns-core-modules/application] external "tns-core-modules/application" 42 bytes {bundle} [built]
[tns-core-modules/bundle-entry-points] external "tns-core-modules/bundle-entry-points" 42 bytes {bundle} [built]
[tns-core-modules/file-system] external "tns-core-modules/file-system" 42 bytes {bundle} [built]
[tns-core-modules/ui/frame] external "tns-core-modules/ui/frame" 42 bytes {bundle} [built]
[tns-core-modules/ui/frame/activity] external "tns-core-modules/ui/frame/activity" 42 bytes {bundle} [built]
[tns-core-modules/ui/styling/style-scope] external "tns-core-modules/ui/styling/style-scope" 42 bytes {bundle} [built]
    + 42 hidden modules
Webpack compilation complete. Watching for file changes.                                                                 work.
Webpack build done!
Plugin nativescript-socket.io is not included in preview app on device 10d2f03d-cbb4-4319-95e1-d30dc58f6642 and will notk.js work.
Start syncing changes for platform android.
Executing before-shouldPrepare hook from S:\documentos\Android\fontAw\hooks\before-shouldPrepare\nativescript-dev-webpacjsk.js                                                                                                                     work.
Skipping prepare.
Successfully synced changes for platform android.                                                                       k.js
Executing before-preview-sync hook from S:\documentos\Android\fontAw\hooks\before-preview-sync\nativescript-dev-webpack.js
Plugin nativescript-socket.io is not included in preview app on device 10d2f03d-cbb4-4319-95e1-d30dc58f6642 and will not work.                                                                                                                  nts\core\components\endpoint.js:8:31)
Start syncing changes for platform android.                                                                             ore\components\endpoint.js:126:32)
Executing before-shouldPrepare hook from S:\documentos\Android\fontAw\hooks\before-shouldPrepare\nativescript-dev-webpaces\networking\modules\web-node.js:59:17)k.js                                                                                                                    dex.js:728:3)
Skipping prepare.                                                                                                       b\request-base.js:676:8)
Successfully synced changes for platform android.                                                                       est-base.js:685:12)
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)dex.js:728:3)                                                                                                           b\request-base.js:676:8)
    at RequestBase._timeoutError (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\liest-base.js:685:12)b\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

**Comment by thearabbit** [comment]
Now work fine for me.
```
tns preview --bundle
```
