### ISSUE TITLE
Released app crashes on run

### ISSUE THREAD

**Issue by academici** [nativescript-vue/nativescript-vue#377]
### Version
2.0.2

### Reproduction link
[https://docs.nativescript.org/tooling/publishing/publishing-android-apps](https://docs.nativescript.org/tooling/publishing/publishing-android-apps)
### Platform and OS info
Android 6-8 / Nativescript 5.0, Ubuntu 18.04

### Steps to reproduce
1. Generate key
keytool -genkey -v -keystore iwant.keystore -alias iwant -keyalg RSA -keysize 2048 -validity 10000

2. Create simple app
tns create iwantApp --vue  --appid ru.iwant.app

3. Build release
tns build android --release --key-store-path ~/development/iwant/iwant.keystore --key-store-password my-secure-pass --key-store-alias iwant --key-store-alias-password my-secure-pass
Build successed

4. Run app

### What is expected?
App should run

### What is actually happening?
App crashed

**Comment by academici** [comment]
With template "--ts" is ok

**Comment by rigor789** [comment]
Missing `--bundle` flag in the build command.

**Comment by academici** [comment]
@rigor789, thanks!
