### ISSUE TITLE
Can't use Placeholder tag properly

### ISSUE THREAD

**Issue by mojimi** [nativescript-vue/nativescript-vue#382]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=VtljXK](https://play.nativescript.org/?template=play-vue&id=VtljXK)
### Platform and OS info
Android 8.0

### Steps to reproduce
Follow the instructions here : https://docs.nativescript.org/ui/placeholder

But instead use the "methods" property of a .vue template to bind the creatingView event of Placeholder tag

### What is expected?
That the creatingView event is called

### What is actually happening?
creatingView event is never called

**Comment by manojdcoder** [comment]
I'm unable to find the implementation of `creatingView` in your version, I have updated it and seems to work as expected.

https://play.nativescript.org/?template=play-vue&id=VtljXK&v=2

**Comment by mojimi** [comment]
@manojdcoder I simply forgot the @ tag, this can be closed, thanks.
