### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by YouSour** [nativescript-vue/nativescript-vue#385]
hi , i'm new with ns-vue , need help , i can't find any full example of using  search bar , any idea or example code for me ?  thank for advance :)

**Comment by Mxkkxa** [comment]
`<template>
    <Page backgroundColor="#9e9e9e"
          androidStatusBarBackground="#616161">
        <ActionBar title="SearchBar Demo"
                   android:flat="true"
                   backgroundColor="#9e9e9e"
                   color="#fff"
                   horizontalAlignment="center">

        </ActionBar>
        <StackLayout>
            <SearchBar v-model="searchQuery"
                       @textChange="onTextChanged"
                       @submit="onSubmit" />
        </StackLayout>
    </Page>
</template>

<script>
export default {
  data() {
    return {
      searchedText: ""
    };
  },
  methods: {
    onTextChanged() {
      console.log("text changed to", this.searchedText);
    },
    onSubmit() {
      console.log("submitted text is", this.searchedText);
    }
  }
};
</script>

<style>
</style>
`

**Comment by YouSour** [comment]
ok , thank you @Mxkkxa :+1:
