### ISSUE TITLE
Back button crash app - Frame with default page + clearHistory

### ISSUE THREAD

**Issue by PieterHartzer** [nativescript-vue/nativescript-vue#387]
### Version
2.0.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=x2QYfT&v=2](https://play.nativescript.org/?template=play-vue&id=x2QYfT&v=2)
### Platform and OS info
Android 8.0 / NativeScript 5.0.1 / MacOS 10.14.1 / NativeScript Playground 

### Steps to reproduce
1. Press the *"To page that will crash"* button.
1. Once the navigation is complete, press the back button on the phone/emulator
1. The app stops responding and after a while Android asks whether to wait or close.

### What is expected?
In the repro I expect the app not to crash.  When adding more components (stripped out for brevity) they should carry on functioning, for example tabs should change.

### What is actually happening?
The app stops responding and Android asks whether to close the app or wait longer.

---
I found the issue whilst creating an app that shows a login page.  Once logged in it will redirect to a 'Home' page which has tab navigation and each tab is a Frame with a component as a defaultPage.  The back button should not go back to the login page.  It turns out it crashes instead.  I created a trimmed down version as a repro but the full version (so far) can be found at https://play.nativescript.org/?template=play-vue&id=7D0PWy

**Comment by MatheusPimentel** [comment]
try delete the packages hooks, node_modules and platforms.
