### ISSUE TITLE
FormattedString not show in production build app

### ISSUE THREAD

**Issue by academici** [nativescript-vue/nativescript-vue#400]
### Version
2.0.2

### Reproduction link
```js
<TextView editable="false">
  <FormattedString>
    <Span text="simple text" />
  </FormattedString>
</TextView>
```
### Platform and OS info
Android 6-8, NativeScript 5.0, Ubuntu 18

### Steps to reproduce
---

### What is expected?
FormattedString content not showing

### What is actually happening?
---

**Comment by rigor789** [comment]
https://github.com/nativescript-vue/vue-cli-template/issues/105#issuecomment-428327597
