### ISSUE TITLE
QR-Code plugin

### ISSUE THREAD

**Issue by Patrick777777** [nativescript-vue/nativescript-vue#404]
hi, are there any qr-code generator plugins that work for nativscript-vue? i've tried zxing and some vue.js plugins, but none of them worked for me. when using zxing, i keep getting the error: "Cannot read property 'BarcodeFormat' of undefined", and the vue.js plugins probably didn't work, because their templates use some html tags like 'div', which won't work in nativescript-vue. is there a way to install the plugins correctly, or are there any custom nativescript-vue plugins i can use for qr-code encoding and decoding?

**Comment by DepickereSven** [comment]
I used this plugin [to create a QR code](https://github.com/kazuhikoarase/qrcode-generator).
I only tested that out in normal VueJs.

But I used [this library](https://market.nativescript.org/plugins/nativescript-barcodescanner) to read that generated QR code from the library I used in VueJs.
