### ISSUE TITLE
App crashes on first run

### ISSUE THREAD

**Issue by eladcandroid** [nativescript-vue/nativescript-vue#407]
### Version
2.0.2

### Reproduction link
[https://github.com/nativescript-vue/nativescript-vue](https://github.com/nativescript-vue/nativescript-vue)
### Platform and OS info
MacOS Mojave

### Steps to reproduce
tns create myapp
Choose Vue.js

### What is expected?
Application is running

### What is actually happening?
Application is crashing

---
package.json:

```javascript
{
    "nativescript": {
        "id": "org.nativescript.check2",
        "tns-android": {
            "version": "5.1.0"
        },
        "tns-ios": {
            "version": "5.1.0"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "nativescript-theme-core": "~1.0.4",
        "nativescript-vue": "~2.0.0",
        "tns-core-modules": "~5.1.0"
    },
    "devDependencies": {
        "@babel/core": "~7.1.0",
        "@babel/preset-env": "~7.1.0",
        "babel-loader": "~8.0.0",
        "nativescript-dev-webpack": "~0.18.0",
        "nativescript-vue-template-compiler": "~2.0.0",
        "node-sass": "~4.9.0",
        "vue-loader": "~15.4.0"
    },
    "readme": "NativeScript Application"
}
```

**Comment by rigor789** [comment]
Hi @eladcandroid, could you include the error message of the app crash? Based on the provided info I don't know how to help you!

**Comment by mfcarneiro** [comment]
@eladcandroid Are you running the `tns run android/ios --bundle`?

You installed all the requirement dependencies on this section of [getting started](https://nativescript-vue.org/en/docs/getting-started/vue-devtools/)? 

Just to know what you have yet done..

**Comment by eladcandroid** [comment]
I didn't use --bundle.. sorry.. closing this issue
