### ISSUE TITLE
EACCES on tns run android --bundle

### ISSUE THREAD

**Issue by norglim** [nativescript-vue/nativescript-vue#408]
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watchPatterns hook from /Users/milgron/apps/test/hooks/before-watchPatterns/nativescript-dev-webpack.js
Executing before-watch hook from /Users/milgron/apps/test/hooks/before-watch/nativescript-dev-webpack.js
Running webpack for Android...
Bundling application for entryPath ./main.js...
clean-webpack-plugin: /Users/milgron/apps/test/platforms/android/app/src/main/assets/app/**/* has been removed.
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Error: EACCES: permission denied, mkdir '/Users/milgron/apps/test/platforms'
Executing webpack failed with exit code 1.
Cannot read property 'kill' of undefined
# tns run

**Comment by acidbiscuit** [comment]
The error has nothing to do with `nativescript-vue` package.

Your `npm` process has write permissions for `/Users/milgron/apps/test/platforms`.  
There are plenty answers to this issue on stackoverflow and google in general, just search an error: `npm Error: EACCES: permission denied` and your OS name.
