### ISSUE TITLE
listview not rendering with typescript

### ISSUE THREAD

**Issue by bilnus1111** [nativescript-vue/nativescript-vue#410]
### Version
2.0.0

### Reproduction link
[https://github.com/nativescript-vue/nativescript-vue/issues/2](https://github.com/nativescript-vue/nativescript-vue/issues/2)
### Platform and OS info
win10, N5, android4.2

### Steps to reproduce
<listview for="item in listitems">
<v-template>
<label :text="item.name" />
<label :text="item.cp" />
</v-template>
</listview>

### What is expected?
display list of items

### What is actually happening?
[Vue warn]: Property or method "item" is not defined on the instance but referenced during render. Make sure that this property is reactive,

---
i'm using nativescript-vue with typescript templates in html files and logic in ts files and render with decorators.

**Comment by rigor789** [comment]
Typescript is not currently official supported - given that list view works in the official templates, the issues is very likely with the typescript setup you are using. Please open an issue in the template you are using instead.
