### ISSUE TITLE
ts-loader@5.3.3 requires a peer of typescript@ error

### ISSUE THREAD

**Issue by brobee** [nativescript-vue/nativescript-vue#411]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org](https://play.nativescript.org)
### Platform and OS info
mac os mojave

### Steps to reproduce
I want to install parse, localstorage, but I got peer error:
npm install nativescript-localstorage
npm WARN ts-loader@5.3.3 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN gamertube@1.0.0 No repository field.

### What is expected?
install without any error

### What is actually happening?
npm install nativescript-localstorage
npm WARN ts-loader@5.3.3 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN gamertube@1.0.0 No repository field.

**Comment by rigor789** [comment]
These are `WARN`ings, so if the project builds and works, you can safely ignore them.

**Comment by jermainerf** [comment]
I am getting this and what concerns me is the 1 high and 1 critical vulnerabilities:

> npm WARN ts-loader@5.3.3 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN minaudio@0.0.1 No repository field.
npm WARN minaudio@0.0.1 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

> added 986 packages from 521 contributors and audited 16819 packages in 58.241s
found 2 vulnerabilities (1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

And i've tried npm audit fix update install delete node_modules and try again in a different order rinse repeat. Does it really not matter? Critical seems like an important word.
