### ISSUE TITLE
[Fixed] TNS Preview error on IOS 12. 

### ISSUE THREAD

**Issue by ebellumat** [nativescript-vue/nativescript-vue#417]
Hi, I was start the quick start of the project, but when i will test on the device with TNS PREVIEW i have this error. I Don't know what i can fix, because its the template code, without changes.

I Run with ````tns preview --bundle`

![image](https://user-images.githubusercontent.com/26942680/51347229-a94f5800-1a86-11e9-95d1-b10e2ad7e2a8.png)
![image](https://user-images.githubusercontent.com/26942680/51347251-b5d3b080-1a86-11e9-8450-300a64b259a4.png)

**Comment by baranelitez** [comment]
I'm having the same problem.
