### ISSUE TITLE
Property suddenly unknown when navigating back to a page

### ISSUE THREAD

**Issue by ThomasKuhlmann** [nativescript-vue/nativescript-vue#420]
### Version
2.0.2

### Reproduction link
Not possible. I tried reproducing the issue in the playground (couldn't get the vue-wait package to work) and in a minimum reproduction (there the problem didn't show up). 

### Platform and OS info
os x, N5, ios 12.1 and android 9

### Steps to reproduce

1. Install [vue-wait](https://github.com/f/vue-wait) with the Vuex option
2. Create main page with frame and load e.g. Dashboard.vue as default `<frame id="content><dashboard /></frame>`
3. in main page, start a loader using `$store.dispatch('wait/start', 'fetch something')`
4. Inside Dashboard, show a conditional component, e.g. `<loader v-if="$wait.is('fetch something')"/>`
5. use `$navigateTo(Users, {frame: 'content})` to load a different  component in the main page frame, then use again `$navigateTo(Dashboard, {frame: 'content})` to load the Dashboard in its original frame
  
### What is expected?
The $wait property should remain accessible when leaving and then returning to a page

### What is actually happening?
The page doesn't load and the log shows an error message that $wait is suddenly unknown (even though it worked perfectly before leaving the page) : "TypeError: undefined is not an object (evaluating '_vm.$wait.is')"

**Comment by rigor789** [comment]
We can't identify an issue without a reproduction, if you are still having issues please open a new issue with more details.
