### ISSUE TITLE
<Modal> lacks the options for animated, stretched, etc.

### ISSUE THREAD

**Issue by calebsmithdev** [nativescript-vue/nativescript-vue#423]
### What problem does this feature solve?
To keep this on par with the NativeScript Core, we need to allow for other options in the `$showModal`, as documented here (https://docs.nativescript.org/api-reference/interfaces/_ui_core_view_base_.showmodaloptions). We currently only offer support for the `fullscreen` option.

### What does the proposed API look like?
I have adopted this in another plugin that extends the <Modal> component. Here is an example of what that looks like: https://github.com/mukaschultze/nativescript-windowed-modal/blob/master/src/vue-windowed-modal.ts - It should only be a few lines of code, but it would be really helpful  We would need to set the default variables for each option then set them to render accordingly in the `this.$el.nativeView.showModal`

**Comment by ThomasKuhlmann** [comment]
Just for reference, here is the original discussion in nativescript core: https://github.com/NativeScript/NativeScript/issues/6387

**Comment by msaelices** [comment]
@CalebJTSmith done: https://github.com/nativescript-vue/nativescript-vue/commit/f1d9aae4bf840502310713500ed2b5c88b7edea8

**Comment by VinhDangQuang** [comment]
Hi, I'm using $showModal to show popup, but how can I set cancelable ? I still click outside and popup is close

**Comment by afliw** [comment]
Any news on this? 

The `cancelable` option is really needed.

**Comment by rigor789** [comment]
@afliw it's already being used in the latest version, in fact all options that are supported by ns are passed through. The promise is resolved when the modal is closed, so for the close callback, just use `$showModal().then(res => { console.log(res) } )`

**Comment by afliw** [comment]
> @afliw it's already being used in the latest version, in fact all options that are supported by ns are passed through. The promise is resolved when the modal is closed, so for the close callback, just use `$showModal().then(res => { console.log(res) } )`

I'm on the latest I think (2.4.0), and the `cancelable` option is not working for me.

The `.on("close")` I was thinking of was to be used inside the modal, like:
`this.$modal.on("close")`

But I ended up using the `beforeDestroy` Vue component event (I'm using the modal with a SFC), so maybe is not needed.

**Comment by rigor789** [comment]
@afliw give the latest alpha a try!
