### ISSUE TITLE
Binding and watching arrays

### ISSUE THREAD

**Issue by Milesq** [nativescript-vue/nativescript-vue#427]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=CSTp1f&v=2](https://play.nativescript.org/?template=play-vue&id=CSTp1f&v=2)
### Platform and OS info
Android 8.1.0 / NativeScript 5.1.1 / Windows 10

### Steps to reproduce
Click on 'QR Code' button and scan this in NativeScript Playground official app.

### What is expected?
After click on foo change, text of first Label element should be equal two.

### What is actually happening?
Nothing

---
the commented fragment works

**Comment by onlined** [comment]
Vue cannot detect setting an element of array with subscripting:
https://vuejs.org/v2/guide/list.html#Caveats
