### ISSUE TITLE
GridLayout SpanRow not working

### ISSUE THREAD

**Issue by packytagliaferro** [nativescript-vue/nativescript-vue#429]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=eCTRHT](https://play.nativescript.org/?template=play-vue&id=eCTRHT)
### Platform and OS info
iOS 12.1.2

### Steps to reproduce
Copy and past spanning grid from https://nativescript-vue.org/en/docs/elements/layouts/grid-layout/#grid-layout-with-mixed-sizing-and-merged-cells

### What is expected?
labels to span across rows and cols

### What is actually happening?
the labels do not span

**Comment by hoatructhanhlam** [comment]
use `colSpan` and `rowSpan` instead of `colspan` and `rowspan`

**Comment by packytagliaferro** [comment]
@hoatructhanhlam good catch. I copied and pasted from the docs so somewhere along the line it got changed with VS Code. Maybe my formatting scripts. Thanks!
