### ISSUE TITLE
Emit event on textChange in combination with v-model crashes app

### ISSUE THREAD

**Issue by Niels-P** [nativescript-vue/nativescript-vue#430]
### Version
2.0.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=jUAVYi](https://play.nativescript.org/?template=play-vue&id=jUAVYi)
### Platform and OS info
iOS 12 / Nativescript Core 5.2.0

### Steps to reproduce
Have a child component with an input field that emits an event to the parent on textChange event. The app will crash once you fill in one character. This might have something to do with updating the v-model, not sure.

### What is expected?
That the input field sends the data gathered from the v-model trough an emit to the parent, without crashing the app.

### What is actually happening?
The app hangs for a short period of time and then crashes.

---
We are trying to split up the searchbar to a separate component, this is when the app crashed.

**Comment by rigor789** [comment]
I could only test on Android (for now), and the crash I got was due to `newItems` being undefined in `productSearch.vue` line 17. 

Defining it with `let newItems = {};` fixes the crash, so it seems to behave as expected.

**Comment by Niels-P** [comment]
You are 100% correct. Thank you, I will hit my colleague on the head 💯 .
