### ISSUE TITLE
dynamic style attribute does not works

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/nativescript-vue#432]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=8SYcPS](https://play.nativescript.org/?template=play-vue&id=8SYcPS)
### Platform and OS info
Any

### Steps to reproduce
add dynamic `:style` attribute to an element

### What is expected?
styled element

### What is actually happening?
style gets not applied on the element

---
my workaround:
```
Vue.directive('style', {
    inserted (el, binding) {
        if (binding.value) {
            el._style = binding.value;
            el.setAttribute('style', binding.value);
        }
    },
    update (el, binding) {
        if (binding.value !== el._style) {
            el._style = binding.value;
            el.setAttribute('style', binding.value);
        }
    }
});
```
then use `v-style="style"` instead of `:style="style"`

**Comment by rigor789** [comment]
See https://vuejs.org/v2/guide/class-and-style.html#Binding-Inline-Styles for the supported syntax.

**Comment by wendt88** [comment]
thx! I have to format my style string to a object like:
```
let styleObject = {};
style
    .split(';')
    .forEach(style => {
        if (style) {
            let [name, value] = style
                .split(':')
                .map(v => v.trim());
                if (name && value)
                    styleObject[name] = value;
        }
    });
```

**Comment by msaelices** [comment]
So, as using the `:style="someObject"` works, I think this is not an issue, right? I will close it but please re-open if I missed something.
