### ISSUE TITLE
v-model in v-if seems to alter wrong data

### ISSUE THREAD

**Issue by jarmani** [nativescript-vue/nativescript-vue#436]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=rYQWFE](https://play.nativescript.org/?template=play-vue&id=rYQWFE)
### Platform and OS info
Andoid 6 / IOS 12 / NativeScript 5.2

### Steps to reproduce
Type some value in Tab 1 TextField, go in Tab 2 type some value as well. Go back on Tab 1

### What is expected?
Data from Tab 1 should not be changed

### What is actually happening?
Data from Tab 1 are changed

---
If you add additional layout in tab 2, it works as expected

**Comment by rigor789** [comment]
You are using `v-if`'s that essentially have the same child element structure, so vue tries to optimize the tab switching by reusing the elements - which leads to your issue of the second tab altering the value of the first tab (first tabs content is shown for the second tab when switching to it, and vue does clear the value, but the event listeners are a bit tricky to clean up). You need to hint vue to not reuse these elements, by adding a `key` attribute like so
https://play.nativescript.org/?template=play-vue&id=rYQWFE&v=2

(Another thing that can optimize the code is to use `v-if` and `v-else-if`, so vue knows there is only one element visible at any given time)
