### ISSUE TITLE
TabView Component Prop Bug

### ISSUE THREAD

**Issue by cpreston321** [nativescript-vue/nativescript-vue#437]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=PrMIJ5&v=2](https://play.nativescript.org/?template=play-vue&id=PrMIJ5&v=2)
### Platform and OS info
Mac OS Mojave Ver. 10.14.3

### Steps to reproduce
1. Make a new a nativescript vue project with tabs.
2. Open App.vue then change " android:tabTextColor=""#whatever_color" -> tabTextColor="#whatever_color" for ios and andriod"
3. Compile and will crash when view is loaded.

### What is expected?
This is supposed to change the color for ios and android.

### What is actually happening?
The app is crashing with error -> JS ERROR TypeError: undefined is not an object (evaluating 'tabSelectedItemTextColor.ios')

**Comment by montythemack** [comment]
What was the resolution here? I am having the same problem.
