### ISSUE TITLE
How to watch when route change?

### ISSUE THREAD

**Issue by thiagohagy** [nativescript-vue/nativescript-vue#448]
I'm using Nativescrpt Mapbox, but every time I will navigateTo some another compoment, the app crashes,
I need to watch my navigation change to destroy the map before leave the component

**Comment by lochstar** [comment]
You don't need to watch the route for this, but if you want to I suggest storing the current route path in a variable that you can then watch.

You need to call `mapbox.destroy()` when removing the map. You can place this in your `beforeDestroy` hook for the map component, or call it on `@navigatingFrom` from a parent component that has the map reference.

**Comment by thiagohagy** [comment]
humm, interesting, I'll try this aproach, tnks man
