### ISSUE TITLE
[require("tns-core-modules/platform")] - Android Crashes when you load info about device

### ISSUE THREAD

**Issue by cpreston321** [nativescript-vue/nativescript-vue#451]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=v2zJSb](https://play.nativescript.org/?template=play-vue&id=v2zJSb)
### Platform and OS info
Nativescript Vue 2.02 and Android 9.0

### Steps to reproduce
Just run the playground with the example on an android device.

### What is expected?
Supposed to come back with info about device 

### What is actually happening?
throws error

---
Works perfect on IOS but not android..

**Comment by rigor789** [comment]
Please include the error message you are getting. 

I suspect you are calling the `platform` module too early in the app lifecycle (android and ios have slightly different boot procedures, so it's very possible that it works on one and doesn't work on the other). Please try moving your call inside the `mounted` hook of your root instance and see if that fixes the crash.

**Comment by rigor789** [comment]
Solved in #458
