### ISSUE TITLE
Manual navigation not working with loaded page

### ISSUE THREAD

**Issue by shinde-sagar** [nativescript-vue/nativescript-vue#452]
Hello Team,

In nativescript-vue manual navigation not working with loaded page. 
e.g page1 -> page2 -> page3 
I can't navigate from page3 -> page1 directly using this.$navigate() function.

**Comment by tralves** [comment]
That's pretty vague... Show us some code. I am interested in where you have `<frame>`s and the navigation code.

**Comment by shinde-sagar** [comment]
I didn't use frame tag in my code. I used page tag.
<page>
..data
</page>

<page>
..data2
</page>
this.$navigateTo(page1);
this.$navigateTo(page2);

**Comment by tralves** [comment]
I don't know what to tell you besides: you are doing something wrong.

**Comment by shinde-sagar** [comment]
How to use frame in nativescript-vue i'm new to nativescript-vue.

**Comment by shinde-sagar** [comment]
> I don't know what to tell you besides: you are doing something wrong.

**Comment by rigor789** [comment]
@shinde-sagar Please refer to the Docs - it has examples for different scenarios: https://nativescript-vue.org/en/docs/elements/components/frame/#app

**Comment by shinde-sagar** [comment]
Thanks All Issue Solved!
