### ISSUE TITLE
Re: Navigation and Frame

### ISSUE THREAD

**Issue by max-pro** [nativescript-vue/nativescript-vue#453]
I'm new to nativescript-vue. I created frame inside App.vue and set defaultpage

<Frame defaultPage="components/home/home.vue"></Frame>

but it showing blank screen.
I created multiple screens now i want to merge them using navigate but its not working.

**Comment by rigor789** [comment]
Without any information we can't really help you.

The issue list is mostly reserved for bug reports and feature requests.

For usage questions, please use the following resources before resorting to opening an issue:

- Read the [docs](https://nativescript-vue.org/en/docs/introduction/)
- Ask on the [#vue channel in slack](https://developer.telerik.com/wp-login.php?action=slack-invitation)
