### ISSUE TITLE
tns android build fails with 2.1.0 expecting --bundle option

### ISSUE THREAD

**Issue by NerdyProjects** [nativescript-vue/nativescript-vue#454]
### Version
2.1.0

### Reproduction link
unnecessary

### Platform and OS info
nativescript-vue 2.1.0 NativeScript 5.2.4

### Steps to reproduce
Follow the tutorial from https://nativescript-vue.org/en/docs/getting-started/quick-start/ to build a new nativescript-vue application:
* vue init nativescript-vue/vue-cli-template <project-name>
* cd <project-name>
* npm install (or yarn)
* tns run android --bundle

### What is expected?
Builds and runs

### What is actually happening?
nativescript-vue throws an error expecting --bundle to be passed: `Unable to apply changes on device: 9885e6485838483144. Error is: Nativescript-vue doesn't work without --bundle option. Please specify --bundle option to the command and execute it again.`

---
Downgrade to 2.0.2 fails, but if I reinstall with 2.0.2 directly it works properly. After upgrading to 2.1.0, it fails again.

issue creation frontend did not allow me to select version 2.1.0

**Comment by rigor789** [comment]
That's doesn't sound right! @Fatme might know why it throws the error when the `--bundle` flag is specified. 

References https://github.com/nativescript-vue/nativescript-vue/commit/265f416d5d1bbe6ea3e36f68dddc5e512bf3d970

**Comment by jjstrat3** [comment]
I was also experiencing this issue after running a fresh `npm install` for something else I was doing.  We had `nativescript-vue` set to `^2.0.2` in our package.json, so removing the caret and doing `npm install` again fixed for me as well.

**Comment by ExcelNet-Public** [comment]
Forcing to 2.0.2 works here as well until they get 2.1.x fixed.  This seems like the most basic of test though (can win init / run a new project) and a bit surprised it was released in this broken of a state.

**Comment by rigor789** [comment]
I've tagged `2.0.2` as ˙latest˙ on npm - hopefully that should be a fix for now. Unfortunately this one slipped through in today's release.

**Comment by rigor789** [comment]
## Update

`2.2.0` has been released with a fix in acbc18b9d7104c2479a0d99f93e47efe254e90c7

**Comment by ExcelNet-Public** [comment]
Seems you are losing to the bot - I knew AI would take over some day, just not this quickly!  :)  

The fix however does seem to address this problem for us.  Thanks for clearing this up!

**Comment by NerdyProjects** [comment]
Thanks, also fixed for me.

**Comment by rigor789** [comment]
@ExcelNet-Public I can keep trying though! :) Bots...

@NerdyProjects great to hear!

**Comment by msaelices** [comment]
I've just triaged this issue and checked that is working well, using the current latest 2.2.1 version. So I will close this issue. Please reopen if you reproduce the error again.
