### ISSUE TITLE
Does nativescript has any UI framework like Bootstrap or Vutify?

### ISSUE THREAD

**Issue by syedsimanta03** [nativescript-vue/nativescript-vue#463]
Does nativescript has any UI framework like Bootstrap or Vutify?

This will be better if we have any styling uI stuff?

**Comment by rigor789** [comment]
There is no such framework currently. I've personally been using tailwind (via nativescript-tailwind) to quickly build my UI's with great success. It's up to the NativeScript community to build a UI library (preferrably for all frameworks) at this point, however that might change in the future.
