### ISSUE TITLE
ListView/RadListView with ObservableArray; [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object.

### ISSUE THREAD

**Issue by wpatter6** [nativescript-vue/nativescript-vue#464]
### Version
2.2.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=b1M71v&v=2](https://play.nativescript.org/?template=play-vue&id=b1M71v&v=2)
### Platform and OS info
Android, NSVue: 2.2.0, Vue: 2.5.17

### Steps to reproduce
Just run the playground link above and view the device logs.

### What is expected?
The console would not display any warnings about prop type checks

### What is actually happening?
The console is showing [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object.  This happens with both ListView and RadListView components.

---
This should be a simple fix for the vue ListView and RadListView components; the prop type should be Array | ObservableArray since the latter is a class.

**Comment by msaravitz** [comment]
Maybe this should be a new issue but also, using an ObservableArray in a computed property and then using the computed property as the items generates this warning but also crashes the application with Maximum call stack size exceeded.

`computed: {
itemComputed () {
return new ObservableArray(someArrayVar)
}
 }`
I'm able to get around this by using a watcher and updating the item variable but it would be nice to just use the computed.

**Comment by rigor789** [comment]
@msaravitz can you elaborate your use-case a little bit?

Why do you need an ObservableArray specifically, since a vue array will be reactive by default.

**Comment by msaravitz** [comment]
@rigor789 There might be a different solution but so far, whenever I use a vue array in the radlist and use any of the radlist features like pull to refresh and swipe actions, the rows get weird margins and overlapping elements after scrolling. This occurs even when heights are explicitly set and even in the simplest layouts. Once I switched to an observable array everything looked and works just as expected.

**Comment by odai-alali** [comment]
@rigor789 I'm [using ObservableArray](https://docs.nativescript.org/vuejs/ns-ui/ListView/getting-started#using-observablearray) with RadListView too and I noticed another problem. When implementing load on demand the list redraws when adding new items to the array causing a white flash effect. Using ObservableArray solves this problem and the new items are added to the list as expected. However, in itemTap event the `e.item` is always undefined. I had to use this workaround (see `onItemTap` implementation)
```js
// in my news vuex module
state: {
  newsList: new ObservableArray([])
}
// I'm getting the same warning at first but the list works as expected
```
```html
<RadListView 
          ref="listView"
          for="item in $store.state.news.newsList"
          pullToRefresh="true"
          @pullToRefreshInitiated="onPullToRefreshInitiated"
          @itemTap="onItemTap"
          loadOnDemandMode="Auto"
          :loadOnDemandBufferSize="2"
          @loadMoreDataRequested="onLoadMoreItemsRequested">
        <v-template>
          <GridLayout rows="300" class="news-card" >
            <FlexboxLayout :class="{ 'm-10': true, 'p-10': true, 'news-card__image': true, 'news-card__image--default': !item.Image }" row="0" flexDirection="column-reverse" :backgroundImage="item.Image ? item.Image : defaultImage">
              <StackLayout>
                <Label :text="item.Type.Title" :class="`news-card__type news-card--${item.Type.Key}`" horizontalAlignment="left" textWrap="true"/>
                <Label :text="item.Date" :class="`news-card__date news-title news-card--${item.Type.Key}`" horizontalAlignment="left" textWrap="true"/>
                <Label :text="item.Title" :class="`font-weight-bold news-card__title news-card--${item.Type.Key}`" textWrap="true"/>    
              </StackLayout>
            </FlexboxLayout>    
          </GridLayout>
        </v-template>
      </RadListView>
```

```js
onItemTap(e) {
  // e.item is always undefined     
  const item = this.$store.state.news.newsList.getItem(e.index)
  this.$navigateTo(NewsDetailsScreen, {
    props: {
      item
    }
  });
}
```

I think this should be labeled as a bug.
