### ISSUE TITLE
tns run ios --bundle, gets stuck at copying template files, unable to apply changes on device

### ISSUE THREAD

**Issue by wheelercreek** [nativescript-vue/nativescript-vue#466]
### Version
2.0.0

### Reproduction link
[http://sorry-random-link.com](http://sorry-random-link.com)
### Platform and OS info
IOS iPhone 6 (and/or emulator),  NativeScript 5.3.0, MacOS Mojave 10.14.3

### Steps to reproduce
Following the quickstart guide, I get to "tns run ios --bundle", it gets to "Webpack build done!.. Copying template files..." and then hangs there. 

### What is expected?
I should get a working local dev environment. 

### What is actually happening?
Unable to apply changes on device: 1F99966C-0EDD-493A-BDF9-7E7406669C18. Error is: request to https://registry.npmjs.org/tns-ios failed, reason: connect EPERM 104.16.18.35:443 - Local (0.0.0.0:0).

This message just sits there and the program doesn't go on. 

---
It was giving me a permission error "Could not remove file.." but following another suggestion I removed hooks, node_modules folders and ran  `npm install`.  That seems to have fixed that issue but now I have this one. 

If I try to ping 104.16.18.35,  I just get request timeout messages.

**Comment by tralves** [comment]
That IP is for npmjs.org. That is weird. Either you or npmjs.org are/were having connection issues.

**Comment by wheelercreek** [comment]
![Screen Shot 2019-04-02 at 5 32 26 PM](https://user-images.githubusercontent.com/997414/55445177-db913180-556e-11e9-96fc-3bd8671f5b91.png)

Ping to the domain name seems okay..  and the domain comes up in a browser.  I deleted the folders and package-lock.json, and ran it again.  Still hitting an error with trying to request from that domain:  

![Screen Shot 2019-04-02 at 5 42 57 PM](https://user-images.githubusercontent.com/997414/55445218-227f2700-556f-11e9-92b8-5eefd8bedab3.png)

It's been stuck like this for a few minutes..  I wonder if it's some kind of memory issue?  Looking at my Activity monitor, "kextd" process is using 1.97 GB of memory..

**Comment by wheelercreek** [comment]
I just updated to Mojave from Sierra a week ago.. and things have been a little weird.  So I don't know if something else is going on..

**Comment by wheelercreek** [comment]
I ended up doing a complete system restart and creating a whole new project from the beginning.. it worked this time!
