### ISSUE TITLE
How to read in real time from a firebase database?

### ISSUE THREAD

**Issue by staincodes** [nativescript-vue/nativescript-vue#488]
Usually when I create an application with vue I write this code.
```
<template>
    <div id="app">
        <ul>
              <li v-for="valueRef of values" v-bind:key="valueRef['.key']">{{valueRef}}</li>
       </ul>
    </div> 
</template>

<script>
import { valueFire } from './firebase'


export default {
    data(){
        return{

        }
    }, 
firebase: {
   values: valueFire
}
    




}
</script>
<style lang="scss">
</style>
```
Sorry for the stupid question. But how do I implement code like this on nativescript-vue?

**Comment by tralves** [comment]
Read the [docs](https://nativescript-vue.org/en/docs/introduction/).

See the [`nativescript-plugin-firebase`](https://market.nativescript.org/plugins/nativescript-plugin-firebase).
