### ISSUE TITLE
v-model not working with TextField

### ISSUE THREAD

**Issue by seergiue** [nativescript-vue/nativescript-vue#497]
### Version
2.2.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=z0coGU](https://play.nativescript.org/?template=play-vue&id=z0coGU)
### Platform and OS info
iOS 12.3, Nativescript-vue 2.2.2, Tns 5.0.0, Windows 10

(For Android it works)

### Steps to reproduce
Add a textfield with a v-model, and then a button. Type something on the textfield, then on tapping the button output in the console the field value using the v-model property

### What is expected?
Console output is showing textfield text typed

### What is actually happening?
Console output is empty

**Comment by rigor789** [comment]
You are binding your v-model to `form.email` but logging `this.form.name` - which never changes.

**Comment by degustadev** [comment]
Hey @rigor789 thanks for answering. I'm afraid you are not right. This is how vue works, on the template you access data directly without `this`, but on the script you must use it to refer to the current instance.

**Comment by DrunkenPoney** [comment]
Also, don't use `this` in your bound attributes like `v-model` so in your case you would have to change `v-model="this.form.email"` to `v-model="form.email"`

**Comment by seergiue** [comment]
@rigor789 @DrunkenPoney Thanks for answering. I've tried with the following: https://play.nativescript.org/?template=play-vue&id=z0coGU&v=6 and still not working, if I remove `this` from `console.log(this.form.name)` the app crashes because this refers to the current object giving access to the data property.

**Comment by rigor789** [comment]
@seergiue You're still logging `form.name` but changing `form.email` with `v-model`. Logging name will always be empty if you don't change it.

**Comment by seergiue** [comment]
@rigor789 wow ok, I'm stupid haha

**Comment by rigor789** [comment]
@seergiue Hey, don't be hard on yourself, it happens! :)
