### ISSUE TITLE
https://www.nativescript.org dosen't open in my browser (chrome & firefox) last versions, although https://docs.nativescript.org opens normally ... what is the problem?

### ISSUE THREAD

**Issue by xxyyzz2050** [nativescript-vue/nativescript-vue#502]
https://www.nativescript.org dosen't open in my browser (chrome & firefox) last versions, although https://docs.nativescript.org opens normally ... what is the problem?

**Comment by rigor789** [comment]
This project is located at https://nativescript-vue.org.

I just checked and both of you links open fine - make sure your network doesn't block the sites.
