### ISSUE TITLE
Typescript uninspect arg in confim() function

### ISSUE THREAD

**Issue by zzhenryquezz** [nativescript-vue/nativescript-vue#504]
### Version
2.0.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=55NFPr](https://play.nativescript.org/?template=play-vue&id=55NFPr)
### Platform and OS info
android

### Steps to reproduce
Is just an error that the typescript expects a string but receive an object, don't trigger an error in the app just appoint a syntax error.
```
confirm({
    title: ''"
})

### What is expected?
Dont't show syntax errors in vscode

### What is actually happening?
Show syntax errors in vscode and in console too.

---
Check in a local setup

<!-- generated by nativescript-vue-issue-helper. DO NOT REMOVE -->

**Comment by zzhenryquezz** [comment]
## Extra informations: 
These errors are also causing trouble in `tns build android`.
The command doesn't work because of they and webpack exit the console with code 2 
I just could make the command work converting all Typescript code to a normal Javascript code.

**Comment by msaelices** [comment]
@zzhenryquezz When we create the project using the Javascript configuration, the build system expects a JS code in all the app, so mixing JS and TS code is not supported.

If you want to use TS code in your app, I suggest you to create the NS-Vue app using the vue-cli template like this:

```
vue init nativescript-vue/vue-cli-template <project-name>
```

And select the Typescript language. Then you can use TS code in your Vue components.

**Comment by msaelices** [comment]
@zzhenryquezz I will close this issue but let me see if there is a problem using the `vue-cli-template` and TS.

**Comment by zzhenryquezz** [comment]
Well i used the cli to make the project and i also choose the typescript option, but i don't see in this project for a while so i will check again and see if the error is still happening.
