### ISSUE TITLE
Different results when app is installed via "tns run" and "tns preview"

### ISSUE THREAD

**Issue by zhiyong-ft** [nativescript-vue/nativescript-vue#505]
### Version
2.2.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=HdDm9M&v=786](https://play.nativescript.org/?template=play-vue&id=HdDm9M&v=786)
### Platform and OS info
Android 8/NativeScript 5.4.0/Windows 10

### Steps to reproduce
1) Download the sample code: Building a Good-Looking Login Form from playground
2) cd into folder, npm install, tns install, tns preview or tns build
3) Run the results app on an android phone
4) Tap the input form, either email or password

### What is expected?
Software keypad is expected ,as result of tns preview, not to cover the button at the bottom of login page. However, in the result of app from tns build android --bundle, software keypad covers the botton button in login page.

### What is actually happening?
There might be some difference in the android build settings in server and the version shipped to local development environment.

**Comment by msaelices** [comment]
@zhiyong80 I've just reproduced your error. It's an error related to the NS Playground platform, so I will forward it to the NS team.

**Comment by elena-p** [comment]
Hi @zhiyong80, the app link you provided is not working with the latest official preview app - version 1.22.0. Here is an updated link - https://play.nativescript.org/?template=play-vue&id=HdDm9M&v=2260

**Comment by msaelices** [comment]
@zhiyong80 @elena-p the updated link is working and I can reproduce the issue again

**Comment by msaelices** [comment]
@zhiyong80 @elena-p I've also found that the `button` is covered also with the `tns preview`. I've tried removing the `platforms` folder and manually add an `android:windowSoftInputMode="adjustResize"` in the Android manifest, but no success.
