### ISSUE TITLE
Timepicker doesn't work as expected

### ISSUE THREAD

**Issue by DepickereSven** [nativescript-vue/nativescript-vue#509]
### Version
2.2.2

### Reproduction link
This link is only for `:hour` and `:minute`
[https://play.nativescript.org/?template=play-vue&id=dZAlXG&v=7](https://play.nativescript.org/?template=play-vue&id=dZAlXG&v=7)

This one is for `v-model`
https://play.nativescript.org/?template=play-vue&id=dZAlXG&v=10

### Platform and OS info
Android 8.1.0 / NativeScript 4.0 / Windows 10

### Steps to reproduce
Just boot it up normally, nothing special

### What is expected?
If you change the time and you press the button now. the time should be changed back to the current time.

### What is actually happening?
sometimes nothing. If a minute pass, he will change the minute time.  that is when you use the `:minute` and `:hour` example if you use the `v-model` example nothing will change

---
I tried to use the v-modal https://nativescript-vue.org/en/docs/elements/components/time-picker/ but that does completely nothing. What I mean with is you can set it value but I won't change.

**Comment by msaelices** [comment]
@DepickereSven I've tried your code and it seems wrong. The `selectedTime` variable is expected to be a Javascript `Date` object instead of a string one. So for example, the `setTimeToNow` method code should be only `this.selectedTime = new Date();`

**Comment by msaelices** [comment]
@DepickereSven  I will close this issue for now as I get your code working changing the variable type to a Date object. If you think I've missed something, please re-open the issue and tell me.

**Comment by DepickereSven** [comment]
Thanks if that is the solution.
But It doesn't make any sense that I need to create a date object for a `timepicker`. 
If I use `datepicker` I can use `this.selected = moment().format('L')`.
So is possible to make it more friendly because it's about the time and not the date?
That you get something back like "11:45" instead of this format `"1899-12-31T10:11:00.000Z"`
