### ISSUE TITLE
Not able to update data in Listview in Tabview

### ISSUE THREAD

**Issue by maikenmadsen1992** [nativescript-vue/nativescript-vue#515]
### Version
2.3.0-rc.1

### Reproduction link
https://play.nativescript.org/?template=play-vue&id=9Fk7AS&v=10
### Platform and OS info
Still under development

### Steps to reproduce
Make a <ListView> with a for loop example item in itemList. The itemList have to be empty. Make a watch or something else af add items til the itemList. If you are at the first tab nothing appen, if you press tab 2 and back to tab 1 the data would be added.

### What is expected?
The listView should have data from the props and watch for changes and then update/add to the existing <ListView)

### What is actually happening?
The listView doesn't update.

**Comment by rigor789** [comment]
@maikenmadsen1992 When trying your playground it errors out because the ObservableArray has not been imported. After importing it, it runs fine, but I can't see any tabs in the code. Can you confirm you've linked the correct playground?

**Comment by maikenmadsen1992** [comment]
I have updated the playground link, i'm so sorry I uploaded something wrong :-S

**Comment by maikenmadsen1992** [comment]
I have also made another playground with a much simpler example: https://play.nativescript.org/?template=play-vue&id=7hhWp4&v=2

When the user press the button the listView have to update and show the new data without having to press tab 2 and back to tab 1.

**Comment by rigor789** [comment]
If you enable logs in `app.js`, you can see 
```
ERROR: [Vue warn]: Property or method "selectedIndex" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <HelloWorld>
<Frame>
<Root>
```

If I change

```html
 <TabView :selectedIndex="selectedIndex" @selectedIndexChange="indexChange">
```

to just

```
 <TabView>
```

It works as expected.

**Comment by maikenmadsen1992** [comment]
Thank you so much! now it's working! that was the weirdest thing. :-)
