### ISSUE TITLE
Height changes after modal open close when use custom router

### ISSUE THREAD

**Issue by KonstantinObuhov** [nativescript-vue/nativescript-vue#516]
### Version
2.2.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=2LN1CF&v=2](https://play.nativescript.org/?template=play-vue&id=2LN1CF&v=2)
### Platform and OS info
iOS

### Steps to reproduce
In the screen tulip scroll down and tap a button to open modal and then close it and you'll see that
height has changed you'll not be able to open modal again.

### What is expected?
Not to change the height and not to hide navigation when open and close modal.

### What is actually happening?
After open modal and then close it the height changed.

Related to this
https://github.com/NativeScript/nativescript-angular/issues/1532

**Comment by rigor789** [comment]
Based on the linked issue in NS Angular - I've replaced 

```js
this.$showModal
```
with
```js
this.$root.$showModal
```
And that seems to fix it.

**Comment by KonstantinObuhov** [comment]
Thx! For the roter plugin and for your reply. I can confirm that it works.

**Comment by KonstantinObuhov** [comment]
````
import {isIOS} from 'tns-core-modules/platform';
.
.
.
computed: {
     modalContext() {
         return isIOS ? this.$root : this;
     }
},

And then you can do this.modalContext.$showModal
````

**Comment by KonstantinObuhov** [comment]
> Based on the linked issue in NS Angular - I've replaced
> 
> ```js
> this.$showModal
> ```
> 
> with
> 
> ```js
> this.$root.$showModal
> ```
> 
> And that seems to fix it.

It seems that workaround fixes the problem only when you staying on tulip page.
If you switch to rose page and then to the tulip page and after that try to open modal it doesn't open at all.

**Comment by KonstantinObuhov** [comment]
Actually, this one https://github.com/nativescript-vue/nativescript-vue/issues/394 is also related to.

**Comment by KonstantinObuhov** [comment]
There is an approach to fix it and it seems like a nativescript bug https://github.com/NativeScript/NativeScript/issues/7290
