### ISSUE TITLE
Navigation problem: going back and forth between components

### ISSUE THREAD

**Issue by sebastiansaenz** [nativescript-vue/nativescript-vue#519]
### Version
2.2.2

### Reproduction link
[https://github.com/sebastiansaenz/anatomia/tree/master/app/components](https://github.com/sebastiansaenz/anatomia/tree/master/app/components)
### Platform and OS info
NativeScript 5.4.2, iOS Simulator (iPhone 6 12.2)

### Steps to reproduce
- Run ``tns run ios --bundle`` and run in Simulator
- Tap "Começar", then choose first item of list, then choose again first item of list, continue Quiz until the end and, lastly, tap "Voltar para a lição". In the "Lição" view press "Voltar". It goes back and forth between those two last views instead of going to the "Main" component.

QuizComplete.vue

```
<template>
    <Page actionBarHidden="true">
        <GridLayout columns="*" rows="*">
            <FlexboxLayout flexDirection="column" alignItems="center" justifyContent="center">
                <Label class="label" :text="Math.round(score)   '%'" />
                <Label class="label" :text="score > 60 ? $t('quizcomplete:text:welldone') : $t('quizcomplete:text:practice')" />
                <Button class="button" :text="$t('quizcomplete:button:backtolesson')" @tap="goToLesson" />
            </FlexboxLayout>
        </GridLayout>
    </Page>
</template>

<script>
    export default {
        props: {
            score: Number,
            lesson: {}
        },
        data() {
            return {

            }
        },
        methods: {
            goToLesson() {
                this.$navigateTo(this.$routes.Lesson, {
                    props: {
                        lesson: this.lesson
                    },
                    transition: {
                        name: 'slideBottom'
                    }
                })
            }
        }
    };
</script>
```

Lesson.vue

```
<template>
    <Page>
        <ActionBar :title="lesson.name">
            <NavigationButton :text="$t('actionbar:back')" android.systemIcon="ic_menu_back"
                @tap="goBack" />
        </ActionBar>
        <AbsoluteLayout ref="rootLayout">
            <ListView for="chapter in lesson.chapters" @itemTap="onItemTap" class="list-group"
                left="10" top="10" height="97%" width="100%" marginBottom="48">
                <v-template>
                    <Label :text="chapter.name" @tap="goToComponent(chapter)" class="list-group-item" />
                </v-template>
            </ListView>
        </AbsoluteLayout>
    </Page>
</template>

<script>
import { mapState } from 'vuex'

    export default {
        computed: {
            ...mapState([
                'lessons'
            ])
        },
        props: {
            lesson: {}
        },
        data() {
            return {

            }
        },
        methods: {
            goToComponent(chapter) {
                this.$navigateTo(this.$routes.Chapter, {
                    props: {
                        chapter: chapter,
                        lesson: this.lesson
                    }
                })
            },
            goBack() {
                this.$navigateTo(this.$routes.Lessons, {
                    props: {
                        lessons: this.lessons
                    }
                })
            }
        }
    };
</script>
```

### What is expected?
To go to Main component

### What is actually happening?
Going back and forth between Lesson and QuizComplete

---
I have tried some console.log inside the goBack function but it's not even called when "Voltar" is pressed. Also, the routing is working perfectly in Android.

**Comment by msaelices** [comment]
@sebastiansaenz This behavior is completely right.

Every time you call `$navigateTo()`, the current page (before navigating) will be stored in the back stack, so tapping on the back button will go to this page, unless you add a `backstackVisible: false` option in the call (see [docs](https://docs.nativescript.org/api-reference/interfaces/_ui_frame_.navigationentry#backstackvisible)).

So, for all of the pages that you consider should not be navigable if you press back, you have to add the `backstackVisible: false` in the call which navigates to all these pages.

**Comment by msaelices** [comment]
@sebastiansaenz  I will close this issue, but if you think I'm wrong or miss something, please re-open it and let me know.

**Comment by sebastiansaenz** [comment]
Thank you @msaelices for your answer but I keep having the same problem.

I've tried adding ``backstackVisible: false`` to the options of ``$navigateTo()`` and also tried with ``clearHistory: true`` but it keeps getting me back to the last component I visited. In fact, with ``clearHistory: true`` my back button doesn't even show.

This is the modified code in ``$navigateTo()``:

```
goToLesson() {
                this.$navigateTo(this.$routes.Lesson, {
                    props: {
                        lesson: this.lesson
                    },
                    backstackVisible: false,
                    // clearHistory: true,
                    transition: {
                        name: 'slideBottom'
                    }
                })
            }
```
This is a screenshot of the Lesson view when I set ``clearHistory: true``:

![imagen](https://user-images.githubusercontent.com/52339334/60730024-86244200-9f1a-11e9-97d5-208bbd4a0f94.png)

**Comment by msaelices** [comment]
Ok,

**Comment by msaelices** [comment]
@sebastiansaenz I've tested the app and the behavior is exactly what your code is doing. Let's see...

In the `QuizComplete.vue` component, in the `Voltar para a lição` handler, which is the `goToLesson()` method, you are doing a `this.$navigateTo(this.$routes.Lesson)` so the app will add the current view as a navigation entry. This means that if the user clicks to the native "back" button, it should go to the previous screen, which is `QuizComplete.vue` actually.

The key point here is that the iOS version `back` button is the native button included by iOS and does not go to the `Lesson.goBack()` method and do the native action of going back in the navigation history, which goes to the QuizComplete page. See https://stackoverflow.com/questions/41863216/nativescript-behavior-of-the-go-back-button

When you try the app on Android, the back button is not the Android native so it will call the `Lesson.goBack()`, which will do the navigation as you expect.

So the correct fix is in your app as there is no bug in NS-vue binding or the NS core library. I suggest you to hide the native back button (with `clearHistory`) and paint a button as is suggested here: https://docs.nativescript.org/ui/action-bar#ios-specifics

**Comment by msaelices** [comment]
@sebastiansaenz I've forked your repo and created this PR which I think fixes your problem: https://github.com/sebastiansaenz/anatomia/pull/1

**Comment by sebastiansaenz** [comment]
thank you @msaelices ! it's working perfectly fine now (except for some UI weird thing, but I will fix that on my own).
