### ISSUE TITLE
Going back and forth between components (not solved)

### ISSUE THREAD

**Issue by sebastiansaenz** [nativescript-vue/nativescript-vue#521]
### Version
2.2.2

### Reproduction link
[https://github.com/sebastiansaenz/anatomia/tree/master/app/components](https://github.com/sebastiansaenz/anatomia/tree/master/app/components)
### Platform and OS info
NativeScript 5.4.2, iOS Simulator (iPhone 6 12.2)

### Steps to reproduce
- Run ``tns run ios --bundle`` and run in Simulator
- Tap "Começar", then choose first item of list, then choose again first item of list, continue Quiz until the end and, lastly, tap "Voltar para a lição". In the "Lição" view press "Voltar". It goes back and forth between those two last views instead of going to the "Main" component.

QuizComplete.vue

```
<template>
    <Page actionBarHidden="true">
        <GridLayout columns="*" rows="*">
            <FlexboxLayout flexDirection="column" alignItems="center" justifyContent="center">
                <Label class="label" :text="Math.round(score)   '%'" />
                <Label class="label" :text="score > 60 ? $t('quizcomplete:text:welldone') : $t('quizcomplete:text:practice')" />
                <Button class="button" :text="$t('quizcomplete:button:backtolesson')" @tap="goToLesson" />
            </FlexboxLayout>
        </GridLayout>
    </Page>
</template>

<script>
    export default {
        props: {
            score: Number,
            lesson: {}
        },
        data() {
            return {

            }
        },
        methods: {
            goToLesson() {
                this.$navigateTo(this.$routes.Lesson, {
                    props: {
                        lesson: this.lesson
                    },
                    backstackVisible: false,
                    clearHistory: true,
                    transition: {
                        name: 'slideBottom'
                    }
                })
            }
        }
    };
</script>
```

Lesson.vue

```
<template>
    <Page>
        <ActionBar :title="lesson.name">
            <NavigationButton :text="$t('actionbar:back')" android.systemIcon="ic_menu_back"
                @tap="goBack" />
        </ActionBar>
        <AbsoluteLayout ref="rootLayout">
            <ListView for="chapter in lesson.chapters" @itemTap="onItemTap" class="list-group"
                left="10" top="10" height="97%" width="100%" marginBottom="48">
                <v-template>
                    <Label :text="chapter.name" @tap="goToComponent(chapter)" class="list-group-item" />
                </v-template>
            </ListView>
        </AbsoluteLayout>
    </Page>
</template>

<script>
import { mapState } from 'vuex'

    export default {
        computed: {
            ...mapState([
                'lessons'
            ])
        },
        props: {
            lesson: {}
        },
        data() {
            return {

            }
        },
        methods: {
            goToComponent(chapter) {
                this.$navigateTo(this.$routes.Chapter, {
                    props: {
                        chapter: chapter,
                        lesson: this.lesson
                    }
                })
            },
            goBack() {
                this.$navigateTo(this.$routes.Lessons, {
                    props: {
                        lessons: this.lessons
                    }
                })
            }
        }
    };
</script>
```

### What is expected?
To go to Main component

### What is actually happening?
Going back and forth between Lesson and QuizComplete if ``clearHistory`` is not set and also navigation button not showing in Lesson after navigating from QuizComplete if ``clearHistory`` is set to ``true`` (``backstackVisible: false`` doesn't change anything in the behavior).

---
Important: I've recently opened an issue with this problem but it was closed before I was able to test any of the solutions in the answer I had, so please **wait at least one day before closing the issue (unless my issue should be closed for any other reason) because I can't re-open it as I'm not a collaborator in the repo**.

I have tried some console.log inside the goBack function but it's not even called when "Voltar" is pressed. Also, the routing is working perfectly in Android.

**Comment by msaelices** [comment]
Close this ticket because is a dup of the #519 one, which I've just reopened.
