### ISSUE TITLE
Reactive <v-template> inside a ListView

### ISSUE THREAD

**Issue by msaelices** [nativescript-vue/nativescript-vue#525]
### Version
2.3.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=rUVzXD](https://play.nativescript.org/?template=play-vue&id=rUVzXD)
### Platform and OS info
Both

### Steps to reproduce
1. Run the sample app.
2. Click on the "Reverse" button
3. See that the first label is reactive but not the labels inside the <v-template> insider the ListView

### What is expected?
The labels inside the ListView should be reactive

### What is actually happening?
The labels inside the ListView are not reactive

See the screencast:

![listview-reactivity-issue mov](https://user-images.githubusercontent.com/136875/61392230-a6f77a80-a8be-11e9-941d-a4c5095c0d1d.gif)

### Implementation details

NS Core reactivity is based on its [data binding](https://docs.nativescript.org/core-concepts/data-binding) mechanism, which is usually performed in the `bindingContext`. The NS-vue binding BTW does not make use of this variable, delegating the reactivity to the Vue.js library. This is working in examples like that:

```
<template>
   ... 
   <Label :text="text" />
   ...
</template>
<script>
export default {
   data: {
      return {
         text: 'Hello world',
      }
   },
   mounted: {
      setTimeout(() => { this.text = 'Bye world' }, 5000);
   }
}
</script>
```
After 5 seconds, the `text` Vue data is changed and Vue triggers the logic to know if this change affects to the template, which is the case, and finally calls to the `setAttribute('text', 'Bye world')` (see [implementation](https://github.com/nativescript-vue/nativescript-vue/blob/master/platform/nativescript/renderer/ViewNode.js#L94)), which does the trick changing the NativeScript component attribute.

The problem appears when we change an attribute referenced inside a `<v-template>` node in a `ListView` component.

But, why most of the apps are working ok with the `ListView`? Because we usually change the elements in the list, which is passed in the `items` attribute, and we have this hack [here](https://github.com/nativescript-vue/nativescript-vue/blob/master/platform/nativescript/runtime/components/list-view.js#L38) for refreshing the list:
```
watch: {
    items: {
      handler(newVal) {
        this.$refs.listView.setAttribute('items', newVal)
        this.refresh()
      },
      deep: true
    }
  },
```

**Comment by farfromrefug** [comment]
@msaelices i just started to face the same issue.
This needs a fix. The "dirty" solution as @msaelices said is really dirt and goes against cell reuse

**Comment by VladimirAmiorkov** [comment]
This should be addressed as soon as possible. From my understanding it is in the plan for the next major release of `nativescript-vue`. Currently there are many related issues in both `ListView` and `RadListView` which source of this behavior.

**Comment by rcoundon** [comment]
Can anyone help with an alternative here?  We have a custom component rendered multiple times within a ListView that seemingly doesn't trigger reactivity.  I.e. an array of data for the custom component is retrieved from an API and a custom component created for each item in that array.
It sits within a v-template which is in turn inside a ListView but the UI is never updated to show the data.

**Comment by Lehren** [comment]
Definitely need something for this. A manual `refresh()` call is clunky and can worsen app responsiveness

**Comment by mobitu** [comment]
Is there any timeline about addressing this issue?

**Comment by spcfdoho** [comment]
Hi,
currently i solved the issue using observableArray. I was using `<v-template>` inside RadListView and stumbled upon the same issue . I needed to change one property when item was selected.
So basically what you should do is this.
`
    onItemSelected({ index }) {
      // eventName, object, index, groupIndex, view
      const currentSelectedItem = this.items.getItem(index);
      currentSelectedItem.selected = true;
      this.items.setItem(index, currentSelectedItem);
      
    },
`
- here `items` is an observableArray
- So what you need to do is basically get the item, change property you want and set it back at the same position.
- Bear in mind that in RadlistView, if you are using staggered layout there might be lot of rearrangement if the property you set is going to change the size of template layout you defined.

**Comment by StephenCarboni** [comment]
This is a big problem

**Comment by rigor789** [comment]
> 
> 
> This is a big problem

@StephenCarboni  Not that big, since it's simple to work around this limitation. If you have ideas how to solve it without re-rendering the whole list on every component data change, please do share them, but it's not simple to account for all possible cases. Applying a workaround when necessary is less error-prone, and has the least performance impact.

**Comment by msl2000** [comment]
Hi, just wanted to see if there has been any news of making Listviews more reactive by nature? I have a Listview that the compares the index of the array item with the currently selected index and highlights it when it is true. This listview acts as a custom datepicker tab bar for another listview. When you scroll through another listview, it snaps the custom tab bar to the current date and this is where my problem with reactivity comes into play. I use the refresh() function to refresh make sure the tab bar snaps into place and the correct array item gets highlighted but it is soooooo unperformant which makes sense because of the continuous scrolledEvent function being fired and the listview refreshing constantly. Is there any way for the listview to just update on the fly like vue was intended to?

**Comment by farfromrefug** [comment]
@msl2000 use an ObservableArray and update items as they get selected/unselected. This is what i do and it is very performant!
