### ISSUE TITLE
ActionBar doesn't work when navigate in tabview with frame on ios

### ISSUE THREAD

**Issue by KonstantinObuhov** [nativescript-vue/nativescript-vue#536]
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=6K9gjF&v=4](https://play.nativescript.org/?template=play-vue&id=6K9gjF&v=4)
### Platform and OS info
ios

### Steps to reproduce
Open help link on an ios device or emulator after that in any tab tap open wizard and try to navigate within modal you will notice that action bar doesn't work correctly.

### What is expected?
When opening a modal and after navigating within modal action bar should work correctly. 

### What is actually happening?
When opening a modal and after navigating within modal action bar doesn't change the title and doesn't render the ios system back button.

**Comment by KonstantinObuhov** [comment]
It happens because of wrapping TabView with <GridLayout>!

**Comment by louislamme** [comment]
@KonstantinObuhov I am facing the same issue, I tried replacing the `<GridLayout>` by `<DockLayout>` do you have any temporary solutions?

**Comment by KonstantinObuhov** [comment]
@louislamme Unfortunately not I've removed everything and my App component looks like this
https://yadi.sk/i/u3hXUtmm_JKz_w

If you ask me I was trying to implement fullscreen loader or layout that over the tabs.

**Comment by louislamme** [comment]
@KonstantinObuhov Thanks for your reply. It seems there's no way to fix it right now. I also replace the modal with typical navigateTo method and it works. :P

**Comment by msaelices** [comment]
@louislamme I've found a workaround which is working, as you can see here https://github.com/nativescript-vue/nativescript-vue/commit/e76908cccd62b62055f9c23b9b72aa694a56711a

Instead of calling `this.$showModal` in the child component, try to do it in the root one. So instead of opening the modal, emit an event so the root component could listen to the Vue event and opening the modal instead.

**Comment by msaelices** [comment]
I've fixed the issue in this PR https://github.com/nativescript-vue/nativescript-vue/pull/558

But I'm not sure if the fix may have collateral effects. Probably @rigor789 may know it.

**Comment by louislamme** [comment]
> ead of opening the modal, emit an event so the root component could listen to the Vue event and op

@msaelices  Thank you! Let me try your suggestion. 😃
