### ISSUE TITLE
Error after migration to 2.4.0

### ISSUE THREAD

**Issue by anandbhaskaran** [nativescript-vue/nativescript-vue#537]
### Version
2.4.0

### Reproduction link
[https://gist.github.com/anandbaskaran/b1971482de0d93ed0eea6f75c32bf630](https://gist.github.com/anandbaskaran/b1971482de0d93ed0eea6f75c32bf630)
### Platform and OS info
Windows 10

### Steps to reproduce
I have updated all the npm dependencies. Then I run `tns migrate` to migrate the application to be compatible with the latest version. Then i run `tns debug android`

**Error 1:** CleanWebpackPlugin is not a constructor. 
_Solution:_ `const { CleanWebpackPlugin } = require("clean-webpack-plugin");` instead of `const CleanWebpackPlugin = require("clean-webpack-plugin");`

**Error 2:** Module not found: Error: Can't resolve 'nativescript-theme-core/css/core.light.css' . 
_Reason:_ There is no more `core.light.css`. 

**Error 3:** clean-webpack-plugin only accepts an options object. 
_Reason:_ The param structure is changed in the latest version (https://github.com/johnagan/clean-webpack-plugin/blob/master/README.md)

### What is expected?
Thing runs smooth

### What is actually happening?
Need debugging to get it working

**Comment by rigor789** [comment]
We haven't updated the template and the webpack config to use latest of everything. Given you've updated every dependency, it is expected to have breaking changes (such as the `CleanWebpackPlugin`). 

Would you mind opening a PR to the https://github.com/nativescript-vue/vue-cli-template repo with the updates to `webpack.config.js` and the theme changes?
