### ISSUE TITLE
Can't use Icon Font in ActionItem

### ISSUE THREAD

**Issue by gerricom** [nativescript-vue/nativescript-vue#539]
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=SHsqwy](https://play.nativescript.org/?template=play-vue&id=SHsqwy)
### Platform and OS info
NativeScript 6.0, iOS 12, Android 7.1

### Steps to reproduce
Run the playground example, which I provided. Look at the two ActionItems in the ActionBar.

### What is expected?
I'm expecting a FontAwesome icon as ActionItem icon. 

### What is actually happening?
I'm getting either a missing character icon or the text of the icon unicode is shown.

---
I build an example with vanilla NativeScript too: https://play.nativescript.org/?template=play-tsc&id=uQoFto
This works as intended. How can I accomplish the same with nativescript-vue?

**Comment by rigor789** [comment]
Using `icon.decode="font://&#xf135;"` seems to do the trick!

**Comment by gerricom** [comment]
Ah, you are right! I've tested various combinations, but I must have missed this one. Thank you!
