### ISSUE TITLE
npm run dev doesn't work on windows

### ISSUE THREAD

**Issue by samayo** [nativescript-vue/nativescript-vue#54]
Ok, I have installed the everything including nativescript and `tns doctor` shows me the 'no issues detected' message. Hence, as per the guide on the readme I followed these steps

```
git clone https://github.com/rigor789/nativescript-vue
cd nativescript-vue
npm install 
npm run dev
```
All the commands worked just fine until the last one, and this is the error I get when I run it. 
 

> $ npm run dev
> 
> nativescript-vue@0.1.7 dev C:\users\samayo\vue-apps\nativescript-vue
> rollup -c -w --o samples/app/nativescript-vue.js
> 
> bundling...
> Error: Could not load C:\users\samayo\vue-apps\nativescript-vue\node_modules\vue\src\core//util/index (imported by C:\users\samayo\vue-apps\nativescript-vue\platform\nativescript\runtime\index.js): ENOENT: no such file or directory, open 'C:\users\samayo\vue-apps\nativescript-vue\node_modules\vue\src\core\util\index'
>  

I think this is related to windows, since I see some path conflict in the error:  `..src\core//util/index` so, I tried to remove the library that is causing the issue in `\nativescript\runtime\index.js`
```js
import { start } from 'application'
import { warn } from 'core/util/index'
import { patch } from './patch'
```
When I removed the second import, the error shows up again, this time with "can not load ./patch" 

So, this error is related to import and paths and I can't find a fix for it.

**Comment by MisterBrownRSA** [comment]
Don't think this is relevant anymore ? @rigor789
