### ISSUE TITLE
How can I run the nativescript-awesome-loaders plugin along with nativescript-vue

### ISSUE THREAD

**Issue by anhvandev** [nativescript-vue/nativescript-vue#549]
### Version
2.4.0

### Reproduction link
[https://github.com/anhvandev/doan_001](https://github.com/anhvandev/doan_001)
### Platform and OS info
Android 5.0.2 / NativeScript 6.0 / Windows 10

### Steps to reproduce
`yarn install`
`yarn run:and`

### What is expected?
Find out how to integrate this plugin into nativescript-vue, as well as similar plugins.

### What is actually happening?
I don't know how to integrate this plugin with nativescript-vue.
I am currently registering it as an element as a guide.
`import {AwesomeLoaders} from 'nativescript-awesome-loaders';`
`Vue.registerElement('AwesomeLoaders', () => require('nativescript-awesome-loaders').AwesomeLoaders);`
I am calling it in app/components Layouts/Login.vue component
![ảnh](https://user-images.githubusercontent.com/49545158/64514584-187b0480-d315-11e9-9f3c-ffc9e8624449.png)

**Comment by rigor789** [comment]
Seems like this plugin exposes typescript files. ts-loader is configured in the webpack config, but you have to manually install typescript. (this is because js projects don't actually need typescript, and it would just increase the project size for most people).

```bash
# try
npm install --save-dev typescript
# or with yarn
yarn add typescript --dev
```

**Comment by anhvandev** [comment]
> 
> 
> Seems like this plugin exposes typescript files. ts-loader is configured in the webpack config, but you have to manually install typescript. (this is because js projects don't actually need typescript, and it would just increase the project size for most people).
> 
> ```shell
> # try
> npm install --save-dev typescript
> # or with yarn
> yarn add typescript --dev
> ```
> 
> **Edit**:
> 
> I just checked and the package does have compiled js files too. Seems like the resolve order in the webpack config is wrong.
> 
> https://github.com/anhvandev/doan_001/blob/d7bad4f21bcf18826438fd2c32f4184c83d572bf/webpack.config.js#L102
> 
> Change the order to
> 
> ```js
> extensions: [".vue", ".js", ".ts", ".scss", ".css"],
> ```

Thanks you.
I will try it.
