### ISSUE TITLE
Nativescript-vue doesn't work without --bundle option. Please specify --bundle option to the command and execute it again   (--bundle problem for ios device using vue.js)

### ISSUE THREAD

**Issue by KYuliia** [nativescript-vue/nativescript-vue#552]
Can someone help me? Have error when write command <tns run ios --bundle> :
Nativescript-vue doesn't work without --bundle option. Please specify --bundle option to the command and execute it again.
Did this operation with it  but not help me :
- reinstall nativescript (local and global)
- update to latest version (6.1.0)
- tns doctor  : run good ( no error or warning )

**Comment by rigor789** [comment]
Duplicate of https://github.com/nativescript-vue/nativescript-vue/issues/454
