### ISSUE TITLE
Android 9 ( v-for not working ) ( watch child component not working )

### ISSUE THREAD

**Issue by monstrikus** [nativescript-vue/nativescript-vue#560]
"V-for" does not work in android 9! When rendering the "page". "v-for" once draws all the elements of the list. When changing the array, does not draw! as if nothing had happened!

Android 9! when changing the "props" of the child component "watch" does not work. No reaction. The console is silent.

Android 9, GEN_RU_A5_2019_V1.0,
model: ZTE Blade A5 2019

**Comment by tralves** [comment]
`v-for` is definitely working on Android 9. Please provide a code sample of what you are doing in the [playground](https://play.nativescript.org/).

**Comment by monstrikus** [comment]
tralves, Thank You. I saw it working,

**Comment by tralves** [comment]
No problem!
