### ISSUE TITLE
RadListView's features are not completed (grouping, sortingm filtering)

### ISSUE THREAD

**Issue by mannok** [nativescript-vue/nativescript-vue#570]
### Version
2.4.0

### Reproduction link
[http://no-reproduction-is.required](http://no-reproduction-is.required)
### Platform and OS info
Android 9.0

### Steps to reproduce
          <RadListView ref="listView" for="item in arr1" @itemTap="onItemTap">
            <RadListView.itemTemplate>
              <StackLayout orientation="vertical">
                
                <Label fontSize="20" :text="'item.text'" />
              </StackLayout>
            </RadListView.itemTemplate>
            <RadListView.groupTemplate>
              <GridLayout ios:height="50">
                <Label text="{{ category }}" class="groupLabel" />
              </GridLayout>
            </RadListView.groupTemplate> 
          </RadListView>

### What is expected?
Should run without error

### What is actually happening?
RadListView.itemTemplate & RadListView.groupTemplate cannot be found

---
seems that grouping in RadListView is not implemented (or just I dont know how to use it).
What can I do to use the grouping feature of RadListView?

**Comment by rigor789** [comment]
RadListView's Vue specific docs can be found here: https://docs.nativescript.org/vuejs/ns-ui/ListView/getting-started

Group templates I'm not sure about, @msaelices might have a clue!

**Comment by msaelices** [comment]
@mannok sorry for the delay. Template grouping is implemented in the Vue layer. Please see the following example:

https://github.com/NativeScript/nativescript-ui-samples-vue/blob/master/listview/app/examples/TemplateGroup.ts

**Comment by msaelices** [comment]
@mannok for the next time, the issues for RADListView and all the NS UI components are tracked in this other repo: https://github.com/NativeScript/nativescript-ui-feedback/issues/new

**Comment by msaelices** [comment]
@mannok I've closed the issue as there is no feedback on your part. Feel free to ask me to re-open it if some issue is still happening.
