### ISSUE TITLE
getFrameById() is deprecated. after updating to NS 6.2.0

### ISSUE THREAD

**Issue by KEYHAN-A** [nativescript-vue/nativescript-vue#575]
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/](https://play.nativescript.org/)
### Platform and OS info
Android 9 / Nativescript 6.2.0 / macOS 10.15 

### Steps to reproduce
I'm trying to use $navigateTo() but I get this line logged in the console when I @tap on my element :
JS: 'getFrameById() is deprecated. Use Frame.getFrameById() instead.'

### What is expected?
Navigate to the other page

### What is actually happening?
getting this line in the console and nothing happens:
JS: 'getFrameById() is deprecated. Use Frame.getFrameById() instead.'

---
here is my method:
```
goToDetailPage() {
      this.$navigateTo(MarketDetails, {
        animated: true,
        transition: {
          name: "slide",
          curve: "ease"
        },
        props: { item: this.item, index: this.index }
      });
    },
```

**Comment by zeke8402** [comment]
Hey @KEYHAN-A , I just had the exact same problem, it turned out that the component I was trying to navigate to was not encased in `<Page>` tags. So, let me know if your component, `MarketDetails`, maybe missing the `<Page>` tag that it should be wrapped in.

Hope that helps!

**Comment by KEYHAN-A** [comment]
@zeke8402 
actually I do have <page> tag in MarketDetails page,
figured out NavigateTo works when you use <ListView> but I need to use a custom list,
I'll post here if I find what the problem is.

**Comment by KEYHAN-A** [comment]
And also there's this issue with `<ListView>` navigation:
when I tap on items, nothing happens, then when I try to go to the other tab all of a sudden all pages start to navigate one by one, `See the GIF below`

![Nov-13-2019 12-00-29](https://user-images.githubusercontent.com/6815523/68748313-462e4380-060d-11ea-8db5-d997ea0568b1.gif)

**Comment by pierresaid** [comment]
I resolved this by changing 

this
```javascript
new Vue({
  store,
  render: h => h('frame', [h(App)])
}).$start()
```
to this in the `main.js`
```javascript
new Vue({
  template: `
      <Frame>
          <App />
      </Frame>`,
  components: {
      App
  }
}).$start();
```

**Comment by coffeeneed** [comment]
Why is this issue closed when it's not resolved? I also experience this error when invoking a function with with $navigateTo. My app simply doesn't work anymore. I do not use ListView and I do have <Page></Page> in my markup. Help, please. I'm clueless here and we need to work in our app.

PS: I have searched my code for "frame" also, but I don't have that word mentioned in my code, so there has to be something deeper.

**Comment by rigor789** [comment]
@coffeeneed have you installed the latest version of nsvue this has been released in? https://github.com/nativescript-vue/nativescript-vue/releases/tag/v2.5.0-alpha.3
