### ISSUE TITLE
Topmost() is deprecate (first build after upgrade to v.6.2)

### ISSUE THREAD

**Issue by ezlo-anatoliiv** [nativescript-vue/nativescript-vue#579]
The same bug for Vue like in 
https://github.com/NativeScript/nativescript-angular/issues/2054

**Comment by coffeeneed** [comment]
I have the problem. This is very critical for us. My button ($navigateTo) wont work!

**Comment by rigor789** [comment]
@coffeeneed please don't spam issues, will in fact slow down the response time, because we have to read it in multiple places - and take the time to reply in each of them. 

Fix has been released in https://github.com/nativescript-vue/nativescript-vue/releases/tag/v2.5.0-alpha.3
