### ISSUE TITLE
Types of navigateTo is missing the property 'frame'

### ISSUE THREAD

**Issue by tuliodiaz** [nativescript-vue/nativescript-vue#587]
### Version
2.4.0

### Reproduction link
[ https://github.com/nativescript-vue/nativescript-vue/blob/master/index.d.ts]( https://github.com/nativescript-vue/nativescript-vue/blob/master/index.d.ts)
### Platform and OS info
All platforms

### Steps to reproduce
See definition of **navigateTo** property **options** in -> https://github.com/nativescript-vue/nativescript-vue/blob/master/index.d.ts

frame is NOT defined in options

see docs ->  https://nativescript-vue.org/en/docs/routing/manual-routing/#navigating-within-a-frame

### What is expected?
**navigateTo** accept **frame** as part of the **options**

### What is actually happening?
typescript is alerting me frame is not existing in options

**Comment by koraykupe** [comment]
I randomly get this error when using navigateTo:
`undefined is not an object (evaluating 'frame.navigate)`
May it be related to that?

**Comment by tarunama** [comment]
@tuliodiaz 
Issue is already fixed. Could you close this ?

**Comment by rigor789** [comment]
Fixed in 2.5.0.
