### ISSUE TITLE
When using $navigateTo I get "getFrameById() is deprecated. Use Frame.getFrameById() instead.'"

### ISSUE THREAD

**Issue by coffeeneed** [nativescript-vue/nativescript-vue#591]
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/?template=play-js&id=xsfX&v=4](https://play.nativescript.org/?template=play-js&id=xsfX&v=4)
### Platform and OS info
vue cli 4.1.1, Windows 10 64, TNS 6.2.2, Android 9

### Steps to reproduce
I upgraded to 6.2.2 a couple of days ago and everything worked well until now.

I only have this:
    showUsers() {
                  this.$navigateTo(this.users);
    },

And the button look like this:

    <GridLayout columns="130, *" rows="auto" class="menu-item" @tap="showUsers()">
    <Image col="0" src="~/assets/images/app/menu-icons/users.png" width="40" horizontalAlignment="left" />
    <Label col="1" verticalAlignment="center">User summary</Label>
  </GridLayout>

In other words, nothing extraordinary at all. This is very worrying for me, as my app is not working at the moment and a lot of people are dependent on updates. Very critical for me and I guess for everyone else.

User page look like this:
<template>
	<Page class="page">
		<ActionBar title="FootyBoss - Assign roster" class="action-bar" />

      <FlexboxLayout v-if="users" flexDirection="column" style="padding:10 10 10 10;">
      <Image src="~/assets/images/app/headers/results.png" class="header" style="width:35%" />
      </FlexboxLayout>
       
	</Page>

</template>

### What is expected?
It's expected that the page changes and button working.

### What is actually happening?
Nothing happens. Absolutely nothing. The consol says:
JS: 'getFrameById() is deprecated. Use Frame.getFrameById() instead.'

---
I can't stress this enough. Please help me out here! PS I was not abled to reproduce this on the playground, thus pasting a "bogus" URL in that input field. I'm so sorry. I hope you can help me out in any case.

**Comment by rigor789** [comment]
Please provide a working playground link - the one you've posted comes up as an error:

> Project not found
We can’t find the project you are looking for - it’s either deleted or the url is wrong.

**Comment by coffeeneed** [comment]
Hello. As I mentioned I could not reproduce it in Playground, even though I tried. The form needed an input field there, so I had to "fake it". So sorry about that! The code is, however, really simple:


<template>
	<Page class="menu-page" actionBarHidden="true">
		<ActionBar class="action-bar" />
                                    <RadSideDrawer ref="drawer" drawerLocation="Right">
                  <side-drawer></side-drawer>
                  <StackLayout ~mainContent>
                  <top-area :openDrawer="openDrawer"></top-area>
                  <ScrollView>

<StackLayout id="main-menu">
    <GridLayout columns="130, *" rows="auto" class="menu-item" @tap="userSummary()">
    <Image col="0" src="~/assets/images/app/menu-icons/user.png" width="40" horizontalAlignment="left" />
    <Label col="1" verticalAlignment="center">User summary</Label>
  </GridLayout>

</StackLayout>
 </ScrollView>
</StackLayout>
        </RadSideDrawer>


	</Page>
</template>

<script>

import Users from './users/allUsers'
  export default {
    data() {
      return {
        userPage: User
      }
    },

  methods: {
    userSummary() {
                  this.$navigateTo(this.userPage)
    },

  }
</script>

<style scoped>
.user { color:tomato }
</style>


Hope this is worth something in the debugging.

**Comment by rigor789** [comment]
The only issue I can spot is `userPage: User`. It's missing an `s` from the end, should be `Users`.

Although, you don't really need to have it in `data()` because you are not navigating from the `<template>` block. 

`this.$navigateTo(Users)` should be enough in your method.

If it still doesn't work, change it to `this.$navigateTo(Users).catch(error => console.log(error))` and see if you have any errors that prevent the page from rendering.

**Comment by tdhman** [comment]
I have the same problem when using `$navigateTo` with Nativescript 6.2.0+.
As @rigor789 suggested, when using catch, I got this error `[TypeError: Cannot read property 'id' of undefined]` and I don't know where it came from. The page that I navigate to has `<Page>` tag.

**Comment by frohmanthenoob** [comment]
@coffeeneed Do you put a frame element in your mainContent?

In my case, i forget to add page element as base node in one of my page. When navigateTo that page console showing the same error.

**Comment by coffeeneed** [comment]
My instantiation looks like this:
```
new Vue({
  store,
  filters,
  render: h => h('frame', isUserId ? [h(router['home'])] : [h(router['login'])] )
}).$start()
``
However, I still get this error.
@frohmanthenoob Do you use Nativescript with Vue? I have all my code (logic, template, etc) in the same file. In other words, for instance I have User.vue file with everything in it. What do you mean when referring to _mainContent_?

All my pages has <Page>-element in them, but no Frame-element. Any ideas?

**Comment by coffeeneed** [comment]
@rigor789 
My method now looks like this:
**this.$navigateTo(Users).catch(error => console.log(error))**

However, it does not print any errors. And obviously I should mention that the User page is indeed rendering and loading, but the deprecation error still occurs.

Anyone?

**Comment by rigor789** [comment]
@coffeeneed the deprecation warning has been fixed in the alpha release ([v2.5.0-alpha.3](https://github.com/nativescript-vue/nativescript-vue/releases/tag/v2.5.0-alpha.3)), but it's just a warning - you can safely ignore it for now (could become an issue if you upgrade to a newer NS version where it's going to get removed completely).

**Comment by oxo0300** [comment]
@rigor789 Do you know when you will make the final release. The new update to 6.2 is definitely causing major issues. Any workaround. In my console.error in the catch, I get this

CONSOLE ERROR TypeError: undefined is not an object (evaluating 'frame.id')

**Comment by farfromrefug** [comment]
I think to help pointing out the issue you can try logging not only the error but also error.stack which is not printed by default

**Comment by rigor789** [comment]
@oxo0300 I'm using the latest alpha with 6.3 without any issues. As for your error, do you have a `<Frame>` in your app? You need at least one frame, either in a template or a render function.

Share a repo/playground of your issue if still running into it. And perhaps check the `error.stack` as @farfromrefug mentioned - but I'm certain it's because you are missing a Frame element.

**Comment by oscarlomas09** [comment]
I am also experiencing the same issue. Using this.$navigateTo outputs:
`'\'getFrameById() is deprecated. Use Frame.getFrameById() instead.\''`
`'[TypeError: Cannot read property \'id\' of undefined]'`

Here are my declarations:
app.js
`
`

**Comment by oscarlomas09** [comment]
I am also experiencing the same issue. Using this.$navigateTo outputs:
`'\'getFrameById() is deprecated. Use Frame.getFrameById() instead.\''`
`'[TypeError: Cannot read property \'id\' of undefined]'`

Here are my declarations:
app.js
```javascript
import Vue from "nativescript-vue";
import App from "./components/App.vue";

import store from "./store";
Vue.config.silent = false;

new Vue({
  store: store,
  render: h => h("frame", [h(App)])
}).$start();
```
login.vue
```html
<template>
  <Page class="page" actionBarHidden="true">
    <ScrollView>
          ...
    </ScrollView>
  </Page>
</template>
<script>
import Login from "./Login";
const platform = require("tns-core-modules/platform");
const application = require("tns-core-modules/application");
export default {
  mounted() {
    this.width = platform.screen.mainScreen.widthDIPs;
    this.height = platform.screen.mainScreen.heightDIPs;
    if (application.ios) {
      this.platform = "ios";
    } else if (application.android) {
      this.platform = "android";
    }
    this.$store.commit("INITIALIZE", {
      platform: this.platform,
      width: this.width,
      height: this.height
    });
    if (!this.$store.getters.isLoggedIn) {
      console.log("oops");
      this.$navigateTo(Login).catch(error => console.log(error));
    } else {
      console.log("what?");
    }
  },
  data() {
    return {
      platform: "",
      isSearching: false,
      width: 0,
      height: 0,
      loginPage: Login
    };
}
</script>
```
app.vue
```html
<template>
  <Page class="page" actionBarHidden="true">
    <ScrollView>
          ...
    </ScrollView>
  </Page>
</template>
```
I haven't implemented the login system because the routing is not working. By default, `isLoggedIn=false`

**Comment by rigor789** [comment]
@oscarlomas09 I suspect the issue in your case is that you're calling `$navigateTo` too early, before the frames are ready. Try moving your navigation call to the `loaded` event of your page for example. (`@loaded="onLoaded"` and then in the `onLoaded` method, you can safely call `$navigateTo`) instead of `mounted`.

**Comment by oscarlomas09** [comment]
@rigor789 Maybe I should try it. However, I am also getting this error if I put it in an event such as `@tap="goToLogin"`

**Comment by rigor789** [comment]
@oscarlomas09 that's odd, mind sharing a repo?

**Comment by pirrera** [comment]
Hello to all.
By updating to the latest version a little bit of everything, I ran into an error returned by the $ navigateTo () function.
Of course, the problem occurs both locally and on the playground


https://play.nativescript.org/?template=play-vue&id=c1kEJs&v=2

**Comment by maximus1010101** [comment]
Hello, I also have a problem with navigation. It's work on the ios, but navigation does not work correctly on the adnroid. The behavior is the same as in #575 issue. Navigation starts after clicking on the next element.

**Comment by NeevorPL** [comment]
<fanfare.wav>
Got same problem. I cannot $navigateTo anywhere because of this error.
I console.logged stack trace and saw something like.

> JS: 'getFrameById() is deprecated. Use Frame.getFrameById() instead.'
> JS: [Vue warn]: Error in nextTick: "TypeError: Cannot read property '$scopedSlots' of undefined"
> JS: 'TypeError: Right-hand side of \'instanceof\' is not an object
> JS:     at assertType (file: node_modules\nativescript-vue\dist\index.js:3249:17)
> JS:     at assertProp (file: node_modules\nativescript-vue\dist\index.js:3208:25)
> JS:     at validateProp (file: node_modules\nativescript-vue\dist\index.js:3142:4)
> JS:     at loop (file: node_modules\nativescript-vue\dist\index.js:4402:16)
> JS:     at initProps (file: node_modules\nativescript-vue\dist\index.js:4435:32)
> JS:     at initState (file: node_modules\nativescript-vue\dist\index.js:4376:20)
> JS:     at VueComponent.Vue._init (file: node_modules\nativescript-vue\dist\index.js:4813:4)
> JS:     at new VueComponent (file: node_modules\nativescript-vue\dist\index.js:13603:11)
> JS:     at createComponentInstanceForVnode (file: node_modules\nativescript->vue\dist\index.js:5678:9)
> JS:     at init (file: node_modules\nativescript-vue\dist\index.js:5509:44)'
F

Then I was enlightened that validateProp and assertType is trying to check my prop type.
I was changed one of my prop definition from `msgId: {type: [String, null], default: null}` to `msgId: String` and... error and warning never occurred... yet... ;)

**Comment by rafftre** [comment]
I experienced the same problem using the tns-template-tab-navigation-vue template with the BottomNavigation and NS 6.3. I resolved it inserting the id on each Frame (<Frame id="myFrameId">), passing that id to the call $navigateTo(Component, { frame: "myFrameId", ... }), and to the call $navigateBack({ frame: "myFrameId" }).

I always get "getFrameById() is deprecated" log, but the app works fine.

Hope this can help in some way.

**Comment by NeevorPL** [comment]
> I resolved it inserting the id on each Frame ()[...]

I have only main Frame. I'm navigating through `Pages` only.

**Comment by overbost** [comment]
I have the same problem after packages update.
Tried with frame id/ref and not work for me.

I solved just downgrade nativescript and nativescript-vue (in project folder):
`$ npm install tns-core-modules@6.1
$ npm install nativescript-vue@2.4.0`

check packages installed
`$ npm ls | grep nativescript-vue
$ npm ls | grep tns
$ tns --version`

set Vue silent to false, for complete debugging
remove platform folder

**this is a workaround for me**

**Comment by rigor789** [comment]
@overbost `nativescript-vue@2.5.0` is the latest version that fixes this warning

**Comment by overbost** [comment]
> @overbost `nativescript-vue@2.5.0` is the latest version that fixes this warning

My npm install the 2.5 alpha version and make more errors...

**Comment by rigor789** [comment]
@overbost there is a stable 2.5.0 version, not the alpha. If you have issues with that please open a separate issue describing the problem with details we can look into!
