### ISSUE TITLE
How to think about the fact that H5 released by Apple store is not allowed to be put on the market, does it have an impact on native script?

### ISSUE THREAD

**Issue by djroad** [nativescript-vue/nativescript-vue#594]
How to think about the fact that H5 released by Apple store is not allowed to be put on the market, does it have an impact on native script?

**Comment by tralves** [comment]
What are you talking about, @djroad? What is H5?

**Comment by djroad** [comment]
@tralves  is  html5......but！nativescript is not html5     i konw~

**Comment by tralves** [comment]
Ok. There is no problem publishing NS apps on the App Store now and no reason to think Apple will change that.
