### ISSUE TITLE
$navigateTo not working on vue with WebView after opening another activity on android

### ISSUE THREAD

**Issue by tdhman** [nativescript-vue/nativescript-vue#596]
### Version
2.4.0

### Reproduction link
[https://github.com/tdhman/android-webview-nav](https://github.com/tdhman/android-webview-nav)
### Platform and OS info
Android 9
tns-android 6.1.2
tns-core-modules 6.1.2

### Steps to reproduce
1. Open and run project for android
2. Tap on scan QR code / open media button to start other activity
3. Then scan a valid QR code to return back to the Nativescript application or wait for media to be downloaded and played then press back button to go back to the Nativescript application
4. Click on navigate to go to other page vue --> the navigation is not working!

### What is expected?
- When clicking on navigate button, it should navigate to the other page.

### What is actually happening?
- The button is clicked but the navigation is not done.

---
On the other hand, if we don't click on scan / open media button first, but click on navigate button, the navigation is working.
Also, if I remove the webview component and repeat the above steps, the navigation is working too!
Hence I think the problem is somehow related to the webview component on the view.

Thanks a lot for any help!

**Comment by tdhman** [comment]
I also got another scenarios that the $navigateTo does not work properly on Android.
- Run & open the above sample application
- Press the lock button on android device to lock the device while the application is still open
- Now, unlock the device, the application is showing but when I press the button to navigate, nothing happens.
---
The button is clicked, I can see the console.log of the click but the navigation does not work. I can click on other buttons (scan or open media for example), they works too!
---
I think the problem is sure from $navigateTo method.

**Comment by rigor789** [comment]
@tdhman I think I know what the issue is - and we have addressed it in https://github.com/nativescript-vue/nativescript-vue/commit/a2b0cd6dc19689cc1f5fbbacec79c5e7a49fcbee

Please try the latest alpha version, and see if the issue still persists! (Despite it being an alpha, it is stable and should cause no problems if upgraded to. We just haven't had the chance to tag a stable release yet).

**Comment by tdhman** [comment]
@rigor789 After updating to the latest alpha version, the issue is resolved. Thanks a lot!
