### ISSUE TITLE
v-if with computed properties only work once. 

### ISSUE THREAD

**Issue by mrwhy-orig** [nativescript-vue/nativescript-vue#597]
### Version
2.4.0

### Platform and OS info
Android 9, NativeScript 6.1.2, Windows 10

### Steps to reproduce
Create a template where you use a v-if with a computed property. Mine is like this:

```
<Page class="page">
        <ActionBar class="action-bar">
            <Label class="action-bar-title" text="Home"></Label>
        </ActionBar>
        <StackLayout>
            <Button @tap="disconnectFromWebsocket" text="Disconnect" v-if="conn"></Button>
            <Button @tap="connectToWebsocket" text="Connect" v-else></Button>
        </StackLayout>
    </Page>
```

If i tap the Connect Button and the computed property changes the button changes. If I tap the disconnect button, the computed property changes (i checked) but the button stays unchanged.

Actually if I define a local variable and change it with a watcher on the computed property, the local variable get changed but the v-if doesn't get triggered. 
If I define a local variable and set it locally in my connection method / disconnection method, it is working as expected.

### What is expected?
The Button should change every time the computed property changes.

### What is actually happening?
It is working only for the first change.

**Comment by mrwhy-orig** [comment]
So I figured that actually the watch method is responsible for it. I tried to watch the connection status (computed property with a store getter) and run a method to get some data from the connection. It seems that after the first change the watch is still working but not the v-if with the computed property.

`

`

**Comment by rigor789** [comment]
Try adding a key property to both buttons. I suspect Vue tries to optimize the condition, and reuses the same button for both, but ns fails to update properly. A simple static key should be fine `key="disconnectBtn"`.

**Comment by mrwhy-orig** [comment]
Thanks, that is working!
