### ISSUE TITLE
Page doesn't dispose/destroy on navigateBack and navigateTo with clearHistory:true

### ISSUE THREAD

**Issue by mylmz10** [nativescript-vue/nativescript-vue#599]
### Version
2.4.0

### Reproduction link
NS Vue
[https://play.nativescript.org/?template=play-vue&id=G2qs7u](https://play.nativescript.org/?template=play-vue&id=G2qs7u)

NS JS
[https://play.nativescript.org/?template=play-js&id=BUPvNn]https://play.nativescript.org/?template=play-js&id=BUPvNn 
### Platform and OS info
Android 8

### Steps to reproduce
Open the Playground URL
Tap the "navigate" button
Starts a timer on the console
Navigate back or tap the "Go Home" button
Timer continues on console

### What is expected?
Dispose page and stop timer for the linked project

### What is actually happening?
Page doesn't dispose and page doesn't destroy

---

Why isn't setInterval and setTimeout be cleared automatically on pageunload event ?

**Comment by rigor789** [comment]
The problem is that you are setting an interval, but never stopping it. You should save the interval id, and clear it in the `beforeDestroy` hook. 

https://play.nativescript.org/?template=play-vue&id=G2qs7u&v=2

**Comment by mylmz10** [comment]
Thanks @rigor789. You right, I should clear the interval but I expect the timer module to clear it.

**Comment by rigor789** [comment]
It can't - even in the browser, you have to clear the interval manually.

**Comment by mylmz10** [comment]
Thanks
