### ISSUE TITLE
Child element order not maintained with v-if

### ISSUE THREAD

**Issue by danny1461** [nativescript-vue/nativescript-vue#608]
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=2rEhAr](https://play.nativescript.org/?template=play-vue&id=2rEhAr)
### Platform and OS info
Android

### Steps to reproduce
When actions are taken to cause a re-render of a page, elements that were previously hidden by v-if are appended to the parent at the wrong location. 

### What is expected?
Order of the elements from the source code should be preserved even as the data causing the re-renders changes.

### What is actually happening?
It appears that a basic remove/append operation is occurring; so elements being brought into existence are appearing at the end of the container instead of where they are in the source template.

---
This is the same minimal production code in Vue for web. Note that the last button remains the last button always.

https://codesandbox.io/s/jovial-bash-fq8by

**Comment by rigor789** [comment]
I have seen this before, but I can't remember being able to track down the issue. However, there is a workaround that seems to solve it by using `v-else-if` or `v-else`: https://play.nativescript.org/?template=play-vue&id=2rEhAr&v=2

This might not be a solution in all cases, but worth giving it a try.

**Comment by danny1461** [comment]
That definitely does work and helps me move past my current issue in this case. Now the log shows "InsertBefore" for that element and it appears where it should.

**Comment by teddysasmita** [comment]
StackLayout is not rendering its children properly in 2.6.2.

**Comment by rigor789** [comment]
@teddysasmita mind sharing an example?

**Comment by teddysasmita** [comment]
I am sorry for the late response. Below is the code that I used.
The performance is indeed increase. Thank you so much for all the great works.

<template>
  <Page class="Page" @navigatedTo="navigatedTo">
    <ActionBar title="Welcome">
      <NavigationButton ios:visibility="collapsed" icon="res://menu" @tap="onDrawerButtonTap"></NavigationButton>
      <ActionItem
        icon="res://menu"
        android:visibility="collapsed"
        @tap="onDrawerButtonTap"
        ios.position="left"
      ></ActionItem>
    </ActionBar>
    <ScrollView class="page__content">
      <StackLayout>
        <Image width='80%' src="res://login" stretch="aspectFit" />
        <ActivityIndicator :busy="busy"></ActivityIndicator>
        <StackLayout v-if="!registered">
          <StackLayout class="m-5">
            <Button class="-primary -rounded-sm" @onTap="login">Masuk</Button>
          </StackLayout>
          <StackLayout class="m-5">
            <Button class="-primary -rounded-sm" @onTap="registerLogin">Daftar</Button>
          </StackLayout>
          <StackLayout class="m-5">
            <Button class="-rounded-sm" @onTap="enterAsGuest">Sbg Tamu</Button>
          </StackLayout>
        </StackLayout>
      </StackLayout>
    </ScrollView>
  </Page>
</template>.
