### ISSUE TITLE
Can't open modal within modal due to ViewHierarchy error on IOS.

### ISSUE THREAD

**Issue by aranmohyeddin** [nativescript-vue/nativescript-vue#612]
### Version
2.5.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=mQF8k3&v=3](https://play.nativescript.org/?template=play-vue&id=mQF8k3&v=3)
### Platform and OS info
Android 8 / nativescript 6.5 / 5.4.15-arch1-1

### Steps to reproduce
 * Click on Button (A modal should pop up)
 * Click on Button (Nothing will happen and you will get an error

### What is expected?
 You should see a new popup open.

### What is actually happening?
You get the error: 

> ViewHierarchy: parent is already presenting view controller close the current modal page before showing another one!

---
Closing modal 1 and openning modal 2 / using navigation are not viable workarounds for this issue if what you intend for the user is to see modal 1 when they close modal 2 and

 * you are have multiple navigations in both modal 1 and modal 2
 * you use a custom modal component that has a close button etc and handles closure in certain ways.
 * some of your modals return dynamic values upon their closure
 * you have hooks to run on modal's closure for both modal 1 and modal 2
 * you report closure of modal 1 to server for usage analysis.
 * many other things that other people might do but I'm not doing in my app.

Please see [this](https://github.com/NativeScript/NativeScript/issues/8447#issue-584781492) issue in nativescript repository.
Please see [this](https://stackoverflow.com/a/60798393/5120089) stackoverflow question.

**Comment by rigor789** [comment]
Likely related to this change: https://github.com/nativescript-vue/nativescript-vue/pull/558

To confirm, can you manually change the `$showModal` method in `node_modules/nativescript-vue@2.5.0/dist/index.js:14165` to call 
```js
this$1.$el.nativeView...
```
instead of `$root`.

**Comment by drewjbartlett** [comment]
Yeah, I'm having this same issue after updating to this version.

**Comment by ethnovode** [comment]
Thanks Rigor, this fix is working for me!

> Likely related to this change: #558
> 
> To confirm, can you manually change the `$showModal` method in `node_modules/nativescript-vue@2.5.0/dist/index.js:14165` to call
> 
> ```js
> this$1.$el.nativeView...
> ```
> 
> instead of `$root`.

**Comment by rigor789** [comment]
Good to know. However I'm a little unsure what to do about it - if we revert the change, we break the other now fixed issue, if we keep it this way - we introduce this limitation. 🙄

**Comment by drewjbartlett** [comment]
What issues have you fixed with this @rigor789

**Comment by rigor789** [comment]
@drewjbartlett  https://github.com/nativescript-vue/nativescript-vue/issues/536

**Comment by rigor789** [comment]
I think the best approach would be to add a new `target` option to `$showModal` that opens the modal on that specific element. It could either accept a vue component `target: this` or an element `this.$el` or even a `nativeView`.

```js
import Modal from "./Modal";
this.$showModal(Modal, {
 fullscreen: true,
 target: this
})
```

**Comment by aranmohyeddin** [comment]
That would be awesome.

**Comment by drewjbartlett** [comment]
I think that'd be great! I'm happy to help contribute if you need the help. @rigor789

**Comment by rigor789** [comment]
@drewjbartlett if you want to, sure submit a PR - I'll get it merged/released. 

What I'm thinking is adding the `target` to the options object here: 
https://github.com/nativescript-vue/nativescript-vue/blob/cdb9188677c24a076c5d9d4fa3c6bd1fcd5002a2/platform/nativescript/plugins/modal-plugin.js#L68-L71
and setting it to `this.$root` by default but allow overriding by user. To do that, we would add the `target` to the first empty object in `Object.assign` - `{}` and then change the `this.$root` to `options.target`

https://github.com/nativescript-vue/nativescript-vue/blob/cdb9188677c24a076c5d9d4fa3c6bd1fcd5002a2/platform/nativescript/plugins/modal-plugin.js#L88

That would be the rough approach - I would like to allow passing in a Vue component instance, an element, or a nativeView. A similar thing was done for the `frame` option in the `$navigateTo` methods: 
https://github.com/nativescript-vue/nativescript-vue/blob/cdb9188677c24a076c5d9d4fa3c6bd1fcd5002a2/platform/nativescript/plugins/navigator-plugin.js#L23-L38

**Comment by romandragan** [comment]
Same for me

**Comment by drewjbartlett** [comment]
@rigor789 - I have a working PR, however there doesn't seem to be a clear way to test this in the contributing guides. Maybe we can chat about that on my PR? I'll open shortly.
