### ISSUE TITLE
How to debug on a connected real device?

### ISSUE THREAD

**Issue by huyaxiong** [nativescript-vue/nativescript-vue#617]
I have written some code in local, it works well on the simulator, but when I run it on my iPhone 7 device, it suddenly crashs when it just opened, tried several times, still not working, and theres no logs shown on the console, so how should I debug, how should I figure out why it crashes?

**Comment by rigor789** [comment]
Generally, if you reopen the app after crash it should (not always) display the previous error log.

Given you haven't provided a reproduction, I can't help, as I'm not familiar with your codebase, system etc.

[If you still have issues, please open a new issue using the issue helper - with more details and a reproduction. ](https://new-issue.nativescript-vue.org/?repo=nativescript-vue/nativescript-vue)

🚨 🚨 🚨 
https://new-issue.nativescript-vue.org/?repo=nativescript-vue/nativescript-vue
