### ISSUE TITLE
Can't use ScrollView methods

### ISSUE THREAD

**Issue by gabyseg** [nativescript-vue/nativescript-vue#620]
### Version
2.5.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=EibJad](https://play.nativescript.org/?template=play-vue&id=EibJad)
### Platform and OS info
IOS 13.4

### Steps to reproduce
Try to use the method of ScrollView : scrollToVerticalOffset

### What is expected?
It should have scroller up to 200px

### What is actually happening?
this.$refs.page.nativeView.scrollToVerticalOffset is not a function

---
Thank you for your help

**Comment by rigor789** [comment]
You need to use the `ref` of the ScrollView to access it's `nativeView` and `scrollToVerticalOffset`

So given `<ScrollView orientation="vertical" ref="t" id="t">`
```js
this.$refs.t.nativeView.scrollToVerticalOffset(300, false);
```
should scroll the ScrollView, but you need to do it at a later point than `mounted` as it's not guaranteed that the view is ready and rendered at this point. You can use a `loaded` event or a `setTimeout`.

**Comment by gabyseg** [comment]
Thank you it works perfectly with a loaded event
