### ISSUE TITLE
Which percentage Do Nativescript-Vue cover  Nativescript API engine?

### ISSUE THREAD

**Issue by biapar** [nativescript-vue/nativescript-vue#621]
Which percentage Do Nativescript-Vue cover  Nativescript API engine?

**Comment by rigor789** [comment]
Please clarify your question (even better on Slack/Discord) - not quite sure what you are asking!

**Comment by biapar** [comment]
Hi, I mean if all iOS or Android Api can be used with NativescriptVue.

**Comment by rigor789** [comment]
Yes you can use any platform APIs directly in NativeScript (and NativeScript-Vue).

For example in ObjC you would write the following:
```objc
NSURL *url = [NSURL URLWithString:@"http://example.com"];
NSURLRequest *request = [NSURLRequest requestWithURL:url];
[NSURLConnection sendAsynchronousRequest:request queue:nil completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
    NSLog(@"request complete");
}];
```

And to write it in JavaScript in NativeScript, you would write:

```js
var url = NSURL.URLWithString("http://example.com");
var request = NSURLRequest.requestWithURL(url);
NSURLConnection.sendAsynchronousRequestQueueCompletionHandler(request, null, function(response, data, connectionError) {
    console.log("request complete");
});
```

More details here: https://docs.nativescript.org/core-concepts/ios-runtime/Overview

The same approach work with android as well, for example
```js
var clickListener = android.view.View.OnClickListener({
    onClick: function (view) {
        // Do something on click
    }
});
```
Will create a native `OnClickListener` that works in js.

Read more about the android runtime here: https://docs.nativescript.org/core-concepts/android-runtime/overview

---

In most apps however, you wouldn't need to write code like that, only when you want to use an API that hasn't been wrapped/implemented in NativeScript - and even then, you will often find plugins that have done the work.
