### ISSUE TITLE
make a Translucent tabview 

### ISSUE THREAD

**Issue by jechazelle** [nativescript-vue/nativescript-vue#629]
Hello, I would like to know how can I make Translucent tabview with nativescript vuejs please ?
I watch this viedo https://www.youtube.com/watch?v=F5ZHtJDgM5A, but it's an angular project and no vuejs.

I don't have the (loaded) event on Tabview with nativescript vuejs.
Do you have an idea please ?

Thank you !

**Comment by rigor789** [comment]
It's `@loaded` in Vue. The rest is the same (minus the types if using plain js).

**Comment by jechazelle** [comment]
Thank you @rigor789 for the answer, I tried with @loaded

`<TabView @loaded="tabViewLoaded($event)">`

And my code : 

```
import { isAndroid, isIOS } from 'tns-core-modules/platform';
...
methods: {
    tabViewLoaded(args) {
        let tabView = args.object;

        if(isIOS) {
            let tabBarController = tabView.ios
console.log(tabBarController)
            tabBarController.tabBar.barStyle = UIBarStyle.Black
        }
    }
}
```

But it doesn't work

The console.log return : 
```
{ [super]: {},
  _owner: {},
  _willSelectViewController: { [super]: {}, owner: {} } }
```

Do you have an idea ?

**Comment by rigor789** [comment]
Awesome! Just realized I accidentally hit the close button when I left my previous comment!
