### ISSUE TITLE
CSS changes are not working properly

### ISSUE THREAD

**Issue by vhristov5555** [nativescript-vue/nativescript-vue#63]
1. Go to the CSS of your project
2. Make change to the CSS (a new line is enough)
3. Save
Actual: An error will be thrown on Android
![img_2929](https://user-images.githubusercontent.com/7846198/31491343-b110bb9a-af4f-11e7-95e3-cc6167a43865.jpg)
Expected: The CSS to be applied without restarting the App
Comment: If you made a second change and save the app will be restarted and the change is going to be applied.

**Comment by vhristov5555** [comment]
Update:
With nativescript 3.3 
if you change the css this error is thrown:
"System.err: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err:     at android.view.ViewGroup.addViewInner(ViewGroup.java:4417)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4258)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4198)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4171)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1007)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:816)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)"

**Comment by vhristov5555** [comment]
I have tried it in "0.7.8". The android app doesn't crash, but the CSS is not applied until you restart the app.
I don't think this issue should be closed until the changes are applied correctly.
The progress is in good direction but the issue is not solved.

**Comment by rigor789** [comment]
The latest release should fix this https://github.com/nativescript-vue/nativescript-vue/releases/tag/v0.7.12

**Comment by rigor789** [comment]
I believe this issue is now fixed, closing it for now but if it still occurs let me know and we will reopen it!
