### ISSUE TITLE
 When using $navigateTo I get "getFrameById() is deprecated. Use Frame.getFrameById() instead.'"

### ISSUE THREAD

**Issue by baermathias** [nativescript-vue/nativescript-vue#633]
### Version
2.5.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=wixSoz](https://play.nativescript.org/?template=play-vue&id=wixSoz&v=1)
### Platform and OS info
Galaxy S8 Android

### Steps to reproduce
Create two components and load one of them into another to navigate there. This is the same error as issue #591, which was closed but still exist. Check the reproduction link.

### What is expected?
Navigation to another component

### What is actually happening?
error message

**Comment by rigor789** [comment]
I don't see the warning `getFrameById() is deprecated` in the playground, however there's an issue that prevent your "Login" button from navigating, the target `MainApp.vue` has no `<Page>` element as it's root, so NativeScript can't navigate to it. 

If I add the `<Page>` tag, it works as expected, and I see no warnings: https://play.nativescript.org/?template=play-vue&id=wixSoz&v=2
