### ISSUE TITLE
How to get rid of the logs from nativescript-vue?

### ISSUE THREAD

**Issue by huyaxiong** [nativescript-vue/nativescript-vue#635]
When I run app in debug mode, theres a bunch of logs from nativescript-vue which is very annoying, so how could I get rid of them of is there any config I can turn it off ?
![image](https://user-images.githubusercontent.com/6245250/81134947-ee9fdd80-8f88-11ea-87b7-6881e5e39ab2.png)

**Comment by rigor789** [comment]
```js
// set to true to silence Vue completely (warnings etc)
Vue.config.silent = false

// set to true to only silence the renderer logs (warnings will still show up - new since 2.5.0)
Vue.config.suppressRenderLogs = true
```
