### ISSUE TITLE
Configure ActionBar default background color.

### ISSUE THREAD

**Issue by huyaxiong** [nativescript-vue/nativescript-vue#638]
If I didnt specify any backgourd color on ActionBar, the default backgound color would be green, and each time I have a new page with ActionBar, I have to set backgourd color for ActionBar as well which is inconvenient for me, So could u provide a config option to change the default backgound color of ActionBar one time and all, thanks.

**Comment by emog** [comment]
@huyaxiong - You could add a class or element in your css file and reuse it.

**Comment by huyaxiong** [comment]
> @huyaxiong - You could add a class or element in your css file and reuse it.

I could do so, but everytime I swape pages, I could see the ActionBar is green at the beginning even I set a different color.
![19931591001661_ pic](https://user-images.githubusercontent.com/6245250/83394327-fd17d280-a42a-11ea-9269-52db66daf8a6.jpg)

**Comment by rigor789** [comment]
There's a css rule in `App.vue` where the color is set. You should be able to change that.

**Comment by rigor789** [comment]
#659
