### ISSUE TITLE
Whats the differences between $navigateTo and $showModal? 

### ISSUE THREAD

**Issue by huyaxiong** [nativescript-vue/nativescript-vue#646]
I didnt find any explanation in the document, so I am confused with these two functions, In which scenario I should use $showModal? Please help me understand them, thanks.

**Comment by rigor789** [comment]
You can use modals when you want to show a screen (or multiple) to the user that is completely unrelated to the current navigation flow. For example, you have a screen with a form where the user enters data, and you create a button to choose something from a list - in this case you would show the list in a modal - when the user chooses something you pass it back with `$modal.close(data)` and the user can continue to enter the rest of the data. The navigation history/flow is unaffected (imagine a form with multiple steps, you wouldn't want the choosing to affect the navigation history).

Not sure if this explains it well... Perhaps this image can explain how navigation works (modals are not shown here, but with the above it may be easier to understand where they fit)
![NativeScriptVue-Navigation](https://user-images.githubusercontent.com/879060/82649958-45a8e200-9c1a-11ea-8fc6-484a362b4f33.png)

**Comment by huyaxiong** [comment]
> You can use modals when you want to show a screen (or multiple) to the user that is completely unrelated to the current navigation flow. For example, you have a screen with a form where the user enters data, and you create a button to choose something from a list - in this case you would show the list in a modal - when the user chooses something you pass it back with `$modal.close(data)` and the user can continue to enter the rest of the data. The navigation history/flow is unaffected (imagine a form with multiple steps, you wouldn't want the choosing to affect the navigation history).
> 
> Not sure if this explains it well... Perhaps this image can explain how navigation works (modals are not shown here, but with the above it may be easier to understand where they fit)
> ![NativeScriptVue-Navigation](https://user-images.githubusercontent.com/879060/82649958-45a8e200-9c1a-11ea-8fc6-484a362b4f33.png)

"You can use modals when you want to show a screen (or multiple) to the user that is completely unrelated to the current navigation flow."
You summarize it quite well, thanks for your explanation!

**Comment by huyaxiong** [comment]
> You can use modals when you want to show a screen (or multiple) to the user that is completely unrelated to the current navigation flow. For example, you have a screen with a form where the user enters data, and you create a button to choose something from a list - in this case you would show the list in a modal - when the user chooses something you pass it back with `$modal.close(data)` and the user can continue to enter the rest of the data. The navigation history/flow is unaffected (imagine a form with multiple steps, you wouldn't want the choosing to affect the navigation history).
> 
> Not sure if this explains it well... Perhaps this image can explain how navigation works (modals are not shown here, but with the above it may be easier to understand where they fit)
> ![NativeScriptVue-Navigation](https://user-images.githubusercontent.com/879060/82649958-45a8e200-9c1a-11ea-8fc6-484a362b4f33.png)

BTW, How could I pass the data back through the $modal.close(data) method? Like I navigate to page A and opened modal B, when I close the modal B, how could I receive the data from modal B on page A? I tried using props, but it doesnt working and I cant find any related description on the document. Please help.

**Comment by rigor789** [comment]
@huyaxiong https://nativescript-vue.org/en/docs/routing/manual-routing/#returning-data-from-the-modal

The `$showModal` function is a promise, anything you pass to `$modal.close(data)` will resolve the promise.

**Comment by huyaxiong** [comment]
> https://nativescript-vue.org/en/docs/routing/manual-routing/#returning-data-from-the-modal

Thank you!
