### ISSUE TITLE
Remove debugger statement

### ISSUE THREAD

**Issue by sebj54** [nativescript-vue/nativescript-vue#650]
### Version
2.6.3

### Reproduction link
[https://github.com/nativescript-vue/nativescript-vue/tree/master/samples/app](https://github.com/nativescript-vue/nativescript-vue/tree/master/samples/app)
### Platform and OS info
Any

### Steps to reproduce
Just launch any app and open Chrome Devtools.

### What is expected?
Not being interrupted when debugging :grin:

### What is actually happening?
interruption when debugging

---
Debugger statement is here:

https://github.com/nativescript-vue/nativescript-vue/blob/master/platform/nativescript/compiler/directives/model.js#L13

**Comment by rigor789** [comment]
Fixed in https://github.com/nativescript-vue/nativescript-vue/releases/tag/v2.6.4

I completely forgot to remove those... Oops! 🙄

**Comment by sebj54** [comment]
No problem, it happens! 
Thanks for the quick fix! :+1:
