### ISSUE TITLE
Please add support for using vue filters.

### ISSUE THREAD

**Issue by huyaxiong** [nativescript-vue/nativescript-vue#651]
### What problem does this feature solve?
I could easily adjust the displayed text format.

### What does the proposed API look like?
e.g.

If I want to display text like $9.99

`<Label :text="amount | currency('$', 2)"></Label>`

or I want to display date like 1990-09-09

`<Label :text="date | date('yyyy-MM-dd')"></Label>`

The date or currency filter may come from the third party, but we don't support using them right now.

**Comment by rigor789** [comment]
It's fully supported.

**Comment by huyaxiong** [comment]
> It's fully supported.

Sorry, my bad!
