### ISSUE TITLE
Tab View Template

### ISSUE THREAD

**Issue by ilkan** [nativescript-vue/nativescript-vue#656]
### Version
2.6.4

### Reproduction link
[https://market.nativescript.org/plugins/tns-template-tab-navigation-vue](https://market.nativescript.org/plugins/tns-template-tab-navigation-vue)
### Platform and OS info
Android 9.0

### Steps to reproduce
Create Template
Open App
Click Any Item
Nothing happens

### What is expected?
Go to ItemDetail

### What is actually happening?
When I click In Search, I can see item details

**Comment by ilkan** [comment]
Adding Frame id solves the problem

In TabContent

`<TabContentItem>
            <Frame id="homeContent">
                <Home />
            </Frame>
        </TabContentItem>`

In Method
```
this.$navigateTo(ItemDetails, {
                    frame: "homeContent",
                })
```

**Comment by rigor789** [comment]
I'd like to get this fixed shortly - will keep it open until actually fixed in the template. 

Related https://github.com/NativeScript/nativescript-app-templates/pull/156
Related https://github.com/NativeScript/nativescript-app-templates/pull/155

**Comment by rigor789** [comment]
The template has been updated and should be working properly now!
