### ISSUE TITLE
When navigating back, the ActionBar's background would reset to green.

### ISSUE THREAD

**Issue by huyaxiong** [nativescript-vue/nativescript-vue#659]
I have set background color for ActionBar like this 
`<ActionBar backgroundColor="#164d9b" title="Setting"/>`
when I enter the page, ActionBar's background color is correct, but every time when I tap the back button on the ActionBar to navigate back, the background color of ActionBar would reset to green. I didnt find any settings on this. pls help!

and I am using 
`
nativescript-vue@2.6.1`
`
nativescript-vue-navigator@1.2.0,
` 

this is how I navigating
`this.$navigator.navigate('/settings')`

the screenshots are at below

navigate to setting page
![image](https://user-images.githubusercontent.com/6245250/83411728-60196180-a44b-11ea-8b55-cbd4c4c48426.png)

navigate back
![image](https://user-images.githubusercontent.com/6245250/83411878-abcc0b00-a44b-11ea-8564-f65f451c1518.png)

**Comment by rigor789** [comment]
I can't reproduce the issue. Please provide a project if having trouble and PLEASE follow the issue helper, as it's difficult to help without the information we ask for.

https://play.nativescript.org/?template=play-vue&id=5Z5Jac

ActionBar is red for both pages.

**Comment by rigor789** [comment]
Even with inline `background` set (in this case different colors) it works fine and even fades between the two colors: https://play.nativescript.org/?template=play-vue&id=XmgjsL&v=2

**Comment by huyaxiong** [comment]
I notice that it would only happen when I navigate back from a page with action bar has set a background color to a page without action bar("actionBarHidden" on Page tag)

I just did a small change to your demo, I remove the red background from the action bar at the first page, when I navigate back from the second page, u could see that blue background of action bar is gone, in my case, the background of action bar became green.

https://play.nativescript.org/?template=play-vue&id=CWiYGt&v=2

@rigor789

**Comment by rigor789** [comment]
@huyaxiong I see what you mean. The color it switches to comes from `App.vue` in your case which sets it to green.

If you set it to the same color as the one on the navigated page it shouldn't change the color. 

The color changing is an iOS feature as far as I'm aware - and in the case the ActionBar is hidden, it doesn't do any fading - but applies the styles from the previous page - in your case it switches to Green because that's what you have defined in `App.vue`

**Comment by huyaxiong** [comment]
@rigor789 You are right, I did find that background of action bar has been defined in App.vue and I didn't notice that before, It puzzled me for several days, thank you so much.
