### ISSUE TITLE
Wrong type definition for $navigateBack

### ISSUE THREAD

**Issue by cgoboncan-ebsi** [nativescript-vue/nativescript-vue#662]
### Version
2.6.4

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=PUbKRL&v=2](https://play.nativescript.org/?template=play-vue&id=PUbKRL&v=2)
### Platform and OS info
All

### Steps to reproduce
Pass a NavigationEntry object to this.$navigateBack

### What is expected?
No typescript error when passing a NavigationEntry object to this.$navigateBack

### What is actually happening?
Typescript compiler error:
Expected 0 arguments, but got 1.

---
In index.d.ts, the  type alias should be added:
```export type navigateBack = (options?: NavigationEntryVue, backstackEntry: BackstackEntry) => void```

NativeScriptVue and NativeScriptVueConstructor interfaces should be changed from:
```
$navigateBack: () => void
``` 
to
```
$navigateBack: navigateBack
```

**Comment by rigor789** [comment]
@cgoboncan-ebsi good catch! Would you mind submitting a PR?

**Comment by cgoboncan-ebsi** [comment]
Sure! I'll try to get to it next week or have someone on my team get on it soon.

**Comment by rigor789** [comment]
Perfect, thank you!

**Comment by rigor789** [comment]
Released in v2.7.0
