### ISSUE TITLE
Build Failed when trying run in xcode

### ISSUE THREAD

**Issue by iagocavalcante** [nativescript-vue/nativescript-vue#667]
### Version
2.6.1

### Reproduction link
[https://github.com/iagocavalcante/egua-da-vaga](https://github.com/iagocavalcante/egua-da-vaga)
### Platform and OS info
iOS 9.0 / natiscript 6.7.4 / macOS Caralina 10.15.5

### Steps to reproduce
- create new project
- run tns build ios
- open project in xcode
- try to run in xcode

### What is expected?
Run project in simulator with xcode

### What is actually happening?
Build failed because MDFInternationalization not found

---
I have already this same app in the playstore.

This is the error
<img width="849" alt="Captura de Tela 2020-06-15 às 15 16 10" src="https://user-images.githubusercontent.com/5131187/84691853-39fbc300-af1b-11ea-98b1-ddb56abe5423.png">

**Comment by rigor789** [comment]
Make sure you are opening the `xcworkspace`

**Comment by iagocavalcante** [comment]
yes, i'm open the `eguadavaga.xcworkspace`

<img width="270" alt="Captura de Tela 2020-06-15 às 16 47 31" src="https://user-images.githubusercontent.com/5131187/84699472-f3609580-af27-11ea-816a-42fffc7b1d76.png">

**Comment by rigor789** [comment]
delete `platforms` and do `tns prepare ios` to rebuild it - see if that helps!

**Comment by iagocavalcante** [comment]
Okay, i'll try this now.

**Comment by iagocavalcante** [comment]
It's work now, but this is strange, remove the `platforms` folder before and try to run the `tns build ios `. Thanks for the help.

**Comment by rigor789** [comment]
Not sure what happened, but glad it's working now! 

The difference between `tns prepare` and `tns build` is just that the first one prepares the project, but doesn't actually build it...

**Comment by iagocavalcante** [comment]
Thanks for the help. NS-vue is awesome.
