### ISSUE TITLE
Cloned app does not render

### ISSUE THREAD

**Issue by nevendyulgerov** [nativescript-vue/nativescript-vue#721]
### Version
2.7.1

### Reproduction link
No link can be provided for this issue because you need multiple projects installed on your environment.
### Platform and OS info
Android API 29 / Nativescript 6.5.1 / Windows 10 OS

### Steps to reproduce
1. Clone an existing project in a new folder
2. Install cloned project dependencies
3. Start the project with tns run android

### What is expected?
The app is started successfully. The app looks the same as the original one from which it was cloned.

### What is actually happening?
The app is not started successfully. The app does not look the same as the original one from which it was cloned. The app renders an empty page without any styles. Images, labels, texts are not displayed.

---
To reproduce the issue, you need to have two projects installed on your environment. The original one and the cloned one. The second should be an identical clone of the first one.

No link to minimal reproduction can be provided, because you need multiple apps installed on your environment.

**Comment by rigor789** [comment]
If you are not using NativeScript 7, make sure `nativescript-vue` and `nativescript-vue-template-compiler` are both set to `~2.7.1` in the `package.json`.

If it was set to `^2.7.1` - it will end up installing `2.8.1` which is for NS7 -changing it to `~2.7.1` should fix that.

After changing the values, make sure to delete `platforms`, `hooks`, `node_modules` and `package-lock.json` and then re-run the app.

**Comment by nevendyulgerov** [comment]
The suggested solution works, thanks @rigor789 !
