### ISSUE TITLE
Version 2.8.1 is published in NPM and breaking (but not released yet in github)

### ISSUE THREAD

**Issue by gabemule** [nativescript-vue/nativescript-vue#722]
### Version
2.8.1

### Platform and OS info
Any

### Steps to reproduce
By deleting the package-lock.json it will upgrade to the latest version in NPM repositories, which is 2.8.1 (but in github still in 2.8.0). Upgrading to 2.8.1 the app breaks and shows only a white screen at startup. By downgrading it seems to work fine.

### What is expected?
The app to open normally

### What is actually happening?
The app is opening in a white blank page 

---

It looks like the version published in 2.8.1 has some compiled files changes that causes the error, the version is not tagget in the repository yet, and the commit seems to have only a few doc changes (and two assets zip and tar), however if i downgrade to 2.8.0 it works normally

**Comment by burner03** [comment]
Thanks for posting this I was going crazy trying to figure out why my app suddenly decided to blow up.

**Comment by luiguild** [comment]
I confirm this behavior

**Comment by rigor789** [comment]
2.8.0 and above is for NativeScript 7 - if you are using older NativeScript, make sure to change the version in your package.json to `~2.7.1`.

Updated the release in GitHub from the [CHANGELOG](https://github.com/nativescript-vue/nativescript-vue/blob/master/CHANGELOG.md)
