### ISSUE TITLE
WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead

### ISSUE THREAD

**Issue by Dahkenangnon** [nativescript-vue/nativescript-vue#729]
### Version
2.8.1

### Reproduction link
[https://play.nativescript.org/](https://play.nativescript.org/)
### Platform and OS info
Android 7.0 / nativescript-vue 2.8.1 / Windows 10

### Steps to reproduce
1. Create a native script vue project
2. cd % project_dir%
3. tns run | tns debug %plateform%

### What is expected?
The app launch properly

### What is actually happening?
Get this error and in loop:
/ [..................] \ rollbackFailedOptional: WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.

---
Sorry for the link provided. As i have no link to propose and the form required a link.

**Comment by rigor789** [comment]
Node version? Npm Version? Or if using Yarn - yarn version?

**Comment by Dahkenangnon** [comment]
Node: v12.18.3
Npm: 6.14.6
Yarn: 1.22.5

**Comment by Dahkenangnon** [comment]
`
![2020-10-11_00h30_07](https://user-images.githubusercontent.com/57219141/95666395-66d28680-0b59-11eb-9914-23df6ff86f82.gif)

`

**Comment by Dahkenangnon** [comment]
# Output of tns doctor
C:\Users\Dah-kenangnon\Music\dev\vuemobile\apps\expios> tns doctor
√ Getting environment information

No issues were detected.
√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 7.0.10 version and is up to date.
√ Component @nativescript/core has 7.0.11 version and is up to date.
× Component @nativescript/ios is not installed.
× Component @nativescript/android is not installed.

**Comment by rigor789** [comment]
That's just a warning though - did you wait enough for the install to finish?
