### ISSUE TITLE
How to go about creating an NPM component library

### ISSUE THREAD

**Issue by Nizari** [nativescript-vue/nativescript-vue#744]
### What problem does this feature solve?
We want to have an npm package so we can write reusable components. How can this be achieved?

### What does the proposed API look like?
We know that with vue-cli you can build for a library. Can that work here as well?

**Comment by rigor789** [comment]
Easiest way is to just create `.vue` files, and publish them as a package - any ns-vue project uses webpack to compile, so pulling pure vue files should work just fine. We do that for example here: https://github.com/nativescript-vue/nativescript-vue-multi-drawer

We have a `components` folder, and an `index.js` that just exports an install function so we can `Vue.use(` the library, though that's not necessary if you just want to import components directly, that works too.

**Comment by brysem** [comment]
Thanks @rigor789, excellent advice. It works!
