### ISSUE TITLE
how to background service nativescript vue

### ISSUE THREAD

**Issue by taothai** [nativescript-vue/nativescript-vue#759]
How. to make task background nativescript vue  or example

**Comment by joulgs** [comment]
any prevision?

**Comment by liamcharmer** [comment]
@joulgs  @taothai did you guys get any luck?

**Comment by joulgs** [comment]
@liamcharmer I abandoned the project, today I work with react native

**Comment by liamcharmer** [comment]
> @liamcharmer I abandoned the project, today I work with react native

Ah that's fair enough, how do you find react native in comparison?

**Comment by joulgs** [comment]
so far I haven't applied a practical tool that runs in the background, but before starting my current project I tested it without much difficulty with the help of [this package](https://github.com/Rapsssito/react-native-background-actions) and it's much easier to find content in the community.
