### ISSUE TITLE
___CSS_LOADER_EXPORT___ is not defined in NativeScript 7

### ISSUE THREAD

**Issue by tdhman** [nativescript-vue/nativescript-vue#765]
Hello,

I just upgraded my project from NativeScript 6.5.x to 7.0.0, but I got the following error when building the application on iOS.

```
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: ___CSS_LOADER_EXPORT___ is not defined
 at 
	../node_modules/@nativescript/webpack/helpers/style-hot-loader.js!../node_modules/@nativescript/webpack/helpers/apply-css-loader.js!../node_modules/css-loader/dist/cjs.js?!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/sass-loader/dist/cjs.js!../node_modules/vue-loader/lib/index.js?!./components/Profile/MainProfile.vue?vue&type=style&index=0&id=3e51dbc2&lang=scss&scoped=true&(file:///var/containers/Bundle/Application/XXXXXXX.app/app/bundle.js:315:5)
	at __webpack_require__(file:///var/containers/Bundle/Application/XXXXXX.app/app/runtime.js:75:30)
```
In my application, I use a custom ui vue component with custom css.
The same error here (https://github.com/nativescript-vue/nativescript-vue/issues/715#issuecomment-696603238) but there is no solution yet.

Platform & OS info:
- NativeScript 7 / Xcode 12.2 / iOS 14 / CLI 7.0.8 / 
- @nativescript/webpack 3.0.8

**Comment by rigor789** [comment]
Post package.json - you likely have outdated dependencies

**Comment by tdhman** [comment]
> Post package.json - you likely have outdated dependencies

@rigor789 You're right. I check the package.json then remove outdated packages and this issue is disappeared. Thanks a lot for the suggestion.
However, I got another issue when running app from Xcode, I don't know where in the project that it references to iOS v8 runtime
```
Runtime initialization took 31ms
Assertion failed: (false), function Assert, file /Users/nathanael/Source/core/ns-v8ios-runtime/NativeScript/runtime/Helpers.mm, line 683.
```
