### ISSUE TITLE
Props break reactivity

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/nativescript-vue#778]
### Version
2.8.3

### Reproduction link
[https://github.com/wendt88/ns-vue-bug](https://github.com/wendt88/ns-vue-bug)
### Platform and OS info
Both

### Steps to reproduce
Clone repo and run
Or:
* `ns create test --vue`
* create a new component with props and some async variable changes
* add a navigation from Home component to the newly created component

### What is expected?
In the axample 3s after navigating to `Test`-component, the `ActivityIndicator` should hide

### What is actually happening?
The `ActivityIndicator` keeps spinning

---
By removing the `props`-config inside `component/Test.vue` it works as expected.
Tried also an empty `props` section, and a lot of combinations without success

**Comment by MarkRez** [comment]
I also ran into this.
It looks like this happens in components using <Page> component.

**Comment by rigor789** [comment]
Seems to be related to having `Test` added to the `data` of `Home.vue`, changing `Home.vue` to

```vue
<template>
    <Page>
        <ActionBar>
            <Label text="Home"/>
        </ActionBar>

        <GridLayout>
            <Button text="Go to Test" @tap="nav" />
        </GridLayout>
    </Page>
</template>

<script>
    import Test from './Test';
    export default {
        data () {
            return {
            };
        },
        methods: {
            nav() {
                this.$navigateTo(Test, {
                    props: {
                        text: 'Hi'
                    }
                })
            }
        }
    };
</script>
```

Works fine. I know we have some examples in docs that add components to data, but I believe this is a bad practice (and we need to fix docs) - as it introduces unknown side-effects & generally slows things down, because every property is observed by vue.

**Comment by wendt88** [comment]
thx!
