### ISSUE TITLE
Add a way to pass a native view reference to parent component as a prop

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue#80]
There are many UI plugins that require passing in a view as a property, in xml this is achieved the following way:

```xml
<nsDrawer:RadSideDrawer id="sideDrawer">
  <nsDrawer:RadSideDrawer.drawerContent>
    <StackLayout>
      <!-- etc -->
    </StackLayout>
  </nsDrawer:RadSideDrawer.drawerContent>
</nsDrawer:RadSideDrawer>
```

When registering custom UI elements that use the same approach, the problem is that in ns-vue
```html
<RadSideDrawer id="sideDrawer">
  <StackLayout>
    <!-- etc -->
  </StackLayout>
</RadSideDrawer>
```
tries to append the StackLayout as a child element, and results in nothing displaying.

My initial idea is to add a custom directive that will handle this, using a similar syntax to the default `v-bind:`, `:` or `v-on`, `@` directives.

Naming things is hard, so please help me find a good name and syntax for the proposed directive.

The new syntax would look something like 

```html
<RadSideDrawer id="sideDrawer">
  <StackLayout v-view:drawerContent>
    <!-- etc -->
  </StackLayout>
</RadSideDrawer>
```

And it would probably make sense to add a shorthand version as well

```html
<RadSideDrawer id="sideDrawer">
  <StackLayout ~drawerContent>
    <!-- etc -->
  </StackLayout>
</RadSideDrawer>
```

Leave your suggestion as a comment to what the name of the directive should be!

My initial idea is `v-view:parentPropName`, `~parentPropName` for the shorthand version.

# Checklist

- [x] Add `v-view` directive and `~` as the alias
- [ ] Document usage in docs
- [x] Decide if `v-view` is the right name for the directive. 
- [x] Add `.array` modifier
- [x] Add array mode shorthand alias

# Allow setting a parent array property

So looks like we need to allow multiple children to be added to the parent's prop using an array. Either extend the module to detect arrays (this will likely break in many cases), or create a dedicated directive for setting the array.

Possible short syntax: `~~`, `~[]`, `~.array` etc (comment below if you have an idea)

Example:
```
<Parent>
  <Child ~parentProp.array />
  <Child ~parentProp.array />
  <Child ~parentProp.array />
</Parent>
```
The long syntax would use a directive modifier: `v-view:prop.array`.

**Comment by rigor789** [comment]
You can play around with the directive in this playground: https://play.nativescript.org/?template=play-vue&id=5A3eP-ShmM0QEHiMDDfY0

**Comment by rigor789** [comment]
You can add an action bar if you wrap the RadSideDrawer in a Page. 

https://play.nativescript.org/?template=play-vue&id=6o7FUvfPHw04BqIOY5sz

**Comment by guyaumetremblay** [comment]
Oh fine it works! Don't know what I did wrong when I tested it.
Tested with showOverNavigation="true" and it works too.

**Comment by rigor789** [comment]
Moved to https://github.com/nativescript-vue/nativescript-vue.org/issues/5

**Comment by Fabiyo-90** [comment]
I am on android, once I press the button "back" and that the application is found in pause "onPause ()", and then I click on the icon of the application to engage "surResume ()" then the application bug. Once stop "onStop ()", click on the icon while it normally starts. Bug related to the life cycle of an Android application.
