### ISSUE TITLE
Downgrade to Nativescript 6

### ISSUE THREAD

**Issue by RayburnTrading** [nativescript-vue/nativescript-vue#835]
### Version
2.8.4

### Reproduction link
[http://example...](http://example...)
### Platform and OS info
Android 8  / Nativescript 6 / MacOS Catalina

### Steps to reproduce
I updated Nativescript to v7 and when I create a new Nativescript-Vue app I get `No project found at or above` when I run `tns run android` from the app directory.

I have since ran `npm uninstall -g nativescript` and then `npm i nativescript@6.3.2 -g`.

But the package created by `vue init nativescript-vue/vue-cli-template <project-name>` is giving me an  NS7 app.

TNS Doctor gives me the following:

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 12.2.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.3.2 and the latest available version is 7.2.1.

Package.json:

`{
  "name": "ns-test",
  "main": "main.js",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "license": "MIT",
  "dependencies": { 
    "@vue/devtools": "^5.3.3",
    "nativescript-socketio": "^3.3.1",
    "nativescript-vue-devtools": "^1.4.0",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-vue": "^2.8.1",
    "@nativescript/core": "^7.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "babel-loader": "^8.1.0",
    "@nativescript/webpack": "^3.0.4",
    "nativescript-vue-template-compiler": "^2.8.1",
    "nativescript-worker-loader": "~0.12.1",
    "sass": "^1.26.10",
    "vue-loader": "^15.9.3"
  }
}`

### What is expected?
Should be a NS6 app.

### What is actually happening?
Is creating a NS7 app.

---
I'd prefer to use NS7 but a clean downgrade to NS6 would be OK. Apologies for the lack of min repro link...

**Comment by rigor789** [comment]
```
vue init nativescript-vue/vue-cli-template#ns6 myProject
```
