### ISSUE TITLE
Confirm() dialog doesn't appear on iOS for NS8

### ISSUE THREAD

**Issue by mreall** [nativescript-vue/nativescript-vue#849]
### Version
2.9.0

### Reproduction link
[https://github.com/mreall/nativescript-vue-confirm-dialog-bug](https://github.com/mreall/nativescript-vue-confirm-dialog-bug)
### Platform and OS info
iOS 14.4 emulator and iOS 14.4.1 device / NativeScript 8 / MacOS 11.2.3

### Steps to reproduce
Open the app and tap the "Open confirm dialog" button. You'll notice the console log showing the onTap method is called, but the dialog box doesn't appear.

### What is expected?
The confirm dialog box should appear.

### What is actually happening?
The confirm dialog doesn't appear.

**Comment by fjohnston** [comment]
I'm having the same problem with NS8 on iOS.

I added a `.catch()` to the `confirm()` and got the following: `TypeError: Cannot read property 'rootViewController' of undefined`

```
confirm('confirm')
.catch(err => {
  console.log(err) // TypeError: Cannot read property 'rootViewController' of undefined
})
```

**Comment by sc85** [comment]
I came across the same issue and found a workaround.

Import Dialogs from @nativescript/core and use `Dialogs.confirm` instead of `confirm` directly.

```
import { Dialogs } from '@nativescript/core';
Dialogs.confirm(...).then(...);
```

**Comment by mreall** [comment]
I tested with @nativescript/core@8.0.7 and it's working, even without @sc85's workaround (btw, thanks @sc85 for posting).
