### ISSUE TITLE
"webpack 5.31.2 compiled with 1 error" in a fresh ns-vue project(and in every other project I have)

### ISSUE THREAD

**Issue by kubilaycaglayan** [nativescript-vue/nativescript-vue#851]
### Version
2.9.0

### Reproduction link
[https://nativescript-vue.org/en/docs/getting-started/quick-start/](https://nativescript-vue.org/en/docs/getting-started/quick-start/)
### Platform and OS info
iOS 14, iPhone 11 Pro

### Steps to reproduce
Follow the quick start guide https://nativescript-vue.org/en/docs/getting-started/quick-start/

### What is expected?
After running `ns run ios` project builds successfully.

### What is actually happening?
"webpack 5.31.2 compiled with 1 error"

```
ERROR in ./node_modules/@nativescript/core/ui/core/view-base/index.js 199:8
Module parse failed: Unexpected token (199:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         return this._isLoaded;
|     }
>     get class() {
|         return this.className;
|     }
 @ ./node_modules/@nativescript/core/ui/label/index.ios.js 3:0-53 30:20-36
 @ ./node_modules/@nativescript/core/ui/dialogs/dialogs-common.js 107:22-47
 @ ./node_modules/@nativescript/core/ui/dialogs/index.ios.js 5:0-167 8:0-33 8:0-33 48:18-33 52:21-34 68:29-44 68:61-80 68:96-112 83:29-44 85:27-48 86:34-50 87:38-58 105:15-35 106:22-38 107:26-46 108:19-33 132:71-89 133:53-68 136:58-74 139:58-75 142:58-73 145:30-47 153:25-47 157:25-53 161:25-49 181:20-37 185:35-52 221:60-80
 @ ./node_modules/@nativescript/core/globals/index.js 260:50-74
```

---
It happens on new projects, created with ns create command, and also for old projects too.

Since it is easily reproducible by following the quick start guide, I didn't share my specific working project information. If you can't produce the bug, please let me know and I will surely provide more information for you. Thanks for your time and help.

**Comment by jhz-dev** [comment]
+1.

I'm facing the same issue.

I used the getting started docs and is happening to me as well

https://nativescript-vue.org/en/docs/getting-started/quick-start/

**Comment by shilik** [comment]
+1.
and it happened suddenly. It took me all night to figure out what could be cause but in vain.
I have to use my NS7 version project, and it works.

**Comment by kubilaycaglayan** [comment]
This error seems to be fixed on its own. I no longer have the problem.
