### ISSUE TITLE
Add Vue3 support

### ISSUE THREAD

**Issue by enigma972** [nativescript-vue/nativescript-vue#856]
### What problem does this feature solve?
Make support for Vue3

### What does the proposed API look like?
no

**Comment by baermathias** [comment]
@enigma972 
Check out this issue https://github.com/nativescript-vue/nativescript-vue/issues/583
Also check out this https://github.com/rigor789/nativescript-vue-next

**Comment by Cersin** [comment]
no news for a long time...

**Comment by rigor789** [comment]
Been working on it recently 👀 
https://twitter.com/LinguaBrowse/status/1593804440561389568

**Comment by rigor789** [comment]
It's now available in **beta**!

https://twitter.com/igor_randj/status/1599830172143788032
