### ISSUE TITLE
use plugin npm without plugin nativescript

### ISSUE THREAD

**Issue by mohamadibrahem** [nativescript-vue/nativescript-vue#902]
i want use this pkg https://github.com/runkids/vue2-timeago

    i try that but don't work

**Comment by minhnhut** [comment]
@mohamadibrahem Be aware that Nativescript DOM is different. You can not use normal HTML tags like h1, h2, p, span, ... . The package you mentioned it was written for web which rely on HTML tags.

I think you want to display how many hour ago from the given time. It can be achieved easily by using moment.js. Try something like this:

```
import moment from "moment"

const getHumanDiff = (isoDateString) => {
    const now = moment();
    const targetDate = moment(isoDateString)
    if (targetDate.isSame(now, "day")) {
        return "Today at " + targetDate.format("hh:mm A")
    }
    return targetDate.format("DD-MMM-YY ") + targetDate.format("hh:mm A")
}

Vue.prototype.$formatDateTime = function(isoDateString) {
  return getHumanDiff(isoDateString)
}
``` 

In your Page:

```
<template>
   <Page>
      <Label :text="$formatDateTime('2021-09-24 12:00:00')" />
   </Page>
</template>
```
