### ISSUE TITLE
Nativescript-vue navigation frame not working

### ISSUE THREAD

**Issue by Vaubanson** [nativescript-vue/nativescript-vue#924]
Hello All,
I am using NativeScript and Vue to create an application. When it is started, the login page is displayed. But when I click on the button to go to the home page, the navigation does not work. Here is the Playground link to my application: [https://play.nativescript.org/?template=play-vue&id=Tsu827&v=6
](https://play.nativescript.org/?template=play-vue&id=Tsu827&v=6
)
Could someone help me? I've been stuck on it for two days now.

**Comment by rigor789** [comment]
You never render the `main.vue` file with the `home` frame.

You have `h('frame', [h(Auth)])` which is the same as:

```
<Frame>
  <Auth> (page) -> you are trying to $navigateTo in the home frame here, but it doesn't exist.
```

Common approach for this is the following setup:
```
<frame id="root">
  <AuthPage> -> $navigateTo(AppPage, { frame: root })
</frame>
---> after which you get this
<frame id="root">
  <AppPage>
    <Home> (tabs)
      <frame id="home">...</frame>
      <frame id="search">...</frame>
    </Home>
  </AppPage>
</frame>
```
