### ISSUE TITLE
style is lost after v-if switches back

### ISSUE THREAD

**Issue by mrh1997** [nativescript-vue/nativescript-vue#926]
When one of the branches of an if-statement in the template sets a style explicitly the CSS selector will not work any more when switching back. 

The In the following sample code I switch between two buttons (red and blue one). But after switching back to the blue button the button is displayed grey (default color). For some reason the CSS selector does not work any more:

```vue
<template>
    <Page>
        <ActionBar title="Home" />
        <StackLayout class="home-panel">
            <Button v-if="!on" text="ON" @tap="switchColor()"/>
            <Button v-else text="OFF" @tap="switchColor()" backgroundColor="red"/>
        </StackLayout>
    </Page>
</template>

<script>
    export default {
        data() { return { on: false } },
        methods: {
            switchColor: function() {
                this.on = !this.on;
            }
        }
    };
</script>

<style scoped>
    Button {
        background-color: blue;
        color: white
    }
</style>```

I could reproduce the problem with nativescript 8.0.0, nativescript-vue 2.9.0 on android (as well as ine the current playground version).

**Comment by saibbyweb** [comment]
You can explicitly set the `backgroundColor` of the other button to `blue` like this:

```
 <Button v-if="!on" text="ON" @tap="switchColor()"  backgroundColor="blue" />
```

and it should be fine. Tested on iOS 15.3 --> [Playground link](https://play.nativescript.org/?template=play-vue&id=AVDcOA)

**Comment by mrh1997** [comment]
Of course this workaround works, but it means the power of CSS styling via selectors cannot be leveraged.

**Comment by rigor789** [comment]
@mrh1997 you can also remove the inline `backgroundColor="red"` and use just CSS.

The issue I believe without digging too deep is that `backgroundColor="red"` is being "removed" by the toggle (the same Button is reused when switching), but the removal uses the `unsetValue` which makes the button gray - since css now has a lower specificity than the inline attribute.

**Comment by mrh1997** [comment]
With "just CSS" you mean `style="background-color=red"`? I tested this out. It made the situation worse. Now the color is not switched at all (it permanently is red)

**Comment by rigor789** [comment]
For example this:
```html
<Button v-if="on" text="ON" @tap="switchColor()" class="toggle-on"/>
<Button v-else text="OFF" @tap="switchColor()"  class="toggle-off"/>

<style>
.toggle-on { background-color: green; }

.toggle-off { background-color: red; }
</style>
```

Though in this specific case, it's probably a lot easier to just do:
```html
<Button 
  @tap="on = !on" 
  :text="on ? 'ON' : 'OFF'" 
  :class="on ? 'toggle-on' : 'toggle-off'"
/>
```

**Comment by mrh1997** [comment]
These workarounds works.
