### ISSUE TITLE
Accessing $this (vue instance) in Application Lifecycle Events

### ISSUE THREAD

**Issue by saibbyweb** [nativescript-vue/nativescript-vue#927]
As listed in the docs, https://v7.docs.nativescript.org/core-concepts/application-lifecycle#use-application-events , there are multiple lifecycle events fired in a NS app (launch, suspend, resume etc). The thing is they only work when written outside a Vue instance. 

For example, this doesn't work. The event is never fired.
```
<script>
export default {
    mounted() {
         Application.on(Application.resumeEvent, (args) => { console.log('App resumed, lets access', this.foo) });
    },
    data() {
        return {
            foo: 'bar'
        }
    }
}
</script>
```
and this works fine but I cant access vue instance properties now

```
<script>
Application.on(Application.resumeEvent, (args) => { console.log('App was resumed but cant access foo now') });
export default {
    data() {
        return {
            foo: 'bar'
        }
    }
}
</script>
```

Is it even possible?

**Comment by rigor789** [comment]
You can try `created()` instead of `mounted()` - the issue is likely that `mounted` is called after the even has already happened...

**Comment by saibbyweb** [comment]
Tried in `created()` as well, didn't work. Do you think it has anything to do with `Application Run` internally: https://v7.docs.nativescript.org/core-concepts/application-lifecycle#application-run

Quoting from the docs, `Any code after the run call will not be executed.`. Is creating the root Vue instance with:

```
new Vue({
  render: h => h('frame', [h(App)])
}).$start()
```

equivalent to `Application Run`, as example 1 above (which doesn't work) runs `after` the root instance is created and example 2 (which works) runs `before` the root instance is created.

**Comment by saibbyweb** [comment]
My bad, just noticed something. `resumeEvent` works in `created()` but `launchEvent` doesn't.

**Comment by rigor789** [comment]
`launchEvent` happens before any Vue instance is created

**Comment by rigor789** [comment]
See how you may still handle these events, and make reactive state changes... https://play.nativescript.org/?template=play-vue&id=xeOAC7&v=1

**Comment by saibbyweb** [comment]
Great. Thanks a ton for this. NSVUE is awesome, have a great day ahead.

**Comment by saibbyweb** [comment]
Hey @rigor789 , I noticed something. I am only able to get the launch event if I setup the launchEvent listener in the `created()` hook of the `root` Vue Instance (just like you have in your Playground). I tried setting it up in the `created()` of the `App` component. Didn't work. That's the default behaviour, right?

```
new Vue({
  store,
  created() {
    /* works fine here */
  },
  render: h => h('frame', [h(App)]) // doesnt work in created() of App.vue
}).$start()
```

**Comment by rigor789** [comment]
That's normal, root `created()` is called as soon as it hits `new Vue(`, but the rest are only called after the `$start()` calls the nativescript `Application.run()` methods, so that's a bit after the launchEvent - generally I would either handle the launch event in the `main.js/ts` file outside of any Vue scope, or the root's `created()` event. I'm not sure what you are trying to do with it, so how you do further processing depends on the use-case.

**Comment by saibbyweb** [comment]
In my `main.js`, I first check for the login state of the user and render the `App` component accordingly. A loose example would be:

```
import Login from "./Login.vue";
import MainScreen from "./MainScreen.vue
const App = isLoggedIn ? MainScreen : Login; // getting isLoggedIn from persisted state

new Vue({
  render: h => h('frame', [h(App)])
}).$start()
```

In both these components, I wish to execute some specific code at `launchEvent`, now I totally understand I can do something like this:

```
new Vue({
created() {
    Application.on(Application.launchEvent, (args) => { 
        if(isLoggedIn)
            doThis();
        else
            doThat();
    });
},
render: h => h('frame', [h(App)])
}).$start()
```

further `doThis()` & `doThat()` will consist of `iOS` and `android` specific code. <b>If possible </b>, I would prefer to keep the code to be executed confined to the component file itself. I am kinda looking for `@loaded` event which fires only once. If I minimise the app & comeback to it, `@loaded` is fired again.

Also, how does `mounted()` react to different app events. Is there any (edge) case when `mounted()` gets called twice?

**Comment by rigor789** [comment]
You may be overthinking this - you could just do any checks you need in the `created` callbacks. 

Another thing you can do is render a "Loading" component as the root view, which then handles the loggedIn/loggedOut states and redirects accordingly.

**Comment by saibbyweb** [comment]
Totally understand there are multiple ways to approach this problem. My app is working perfectly fine, I was just curious if it can be done within individual SFCs. Spoilt by web, I guess ( accessing anything, anywhere :D ). Again, thanks for your time.
