### ISSUE TITLE
AXIOS NOT WORK in Nativescript-Vue

### ISSUE THREAD

**Issue by bobwatcherx** [nativescript-vue/nativescript-vue#930]
i have problem with my project
axios GET Jsonplaceholder not work

<script>
import axios from 'axios'

THEN i have error message
like this:

**BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "tty": require.resolve("tty-browserify") }'
	- install 'tty-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "tty": false }
 @ ./node_modules/debug/src/node.js 32:23-48
 @ ./node_modules/debug/src/index.js 9:1-38
 @ ./node_modules/follow-redirects/debug.js 7:14-30
 @ ./node_modules/follow-redirects/index.js 7:12-30
 @ ./node_modules/axios/lib/adapters/http.js 9:17-49 10:18-51
 @ ./node_modules/axios/lib/defaults.js 24:14-40
 @ ./node_modules/axios/lib/axios.js 7:15-36
 @ ./node_modules/axios/index.js 1:0-39
 @ ./node_modules/@nativescript/webpack/dist/loaders/nativescript-worker-loader/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./app/components/Home.vue?vue&type=script&lang=js& 34:0-25
 @ ./app/components/Home.vue?vue&type=script&lang=js& 1:0-209 1:225-228 1:230-436 1:230-436
 @ ./app/components/Home.vue 2:0-56 3:0-51 3:0-51 9:2-8
 @ ./app/app.js 5:0-36 8:31-35

13 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.66.0 compiled with 13 errors in 3468 ms**

**Comment by rigor789** [comment]
See https://github.com/NativeScript/NativeScript/issues/9613#issuecomment-943550227

**Comment by bobwatcherx** [comment]
> See [NativeScript/NativeScript#9613 (comment)](https://github.com/NativeScript/NativeScript/issues/9613#issuecomment-943550227)

error solved , but i have new error aggain

eror in ANDROID DEVICES is 
`ReferenceError : navigator is not defined `
